### ISSUE TITLE
Update Canova-Hansen test function

### ISSUE THREAD

**Issue by robjhyndman** [robjhyndman/forecast#101]
Hi Rob:

While answering the question in [this post](http://stackoverflow.com/questions/27554942/) I have updated the function that computes the Canova and Hansen test for stability of seasonal cycles. A previous version was available in an old package called "uroot". As the function "SD.test" in the "forecast" package is based on this function I thought you could be interested in this update.

I have improved the code and the way the Newey-West covariance matrix is obtained.

I attach the code and some examples including a small simulation to obtain critical values and compare them with the values reported in the original paper.

I have also created a more efficient implementation of the function that returns the trigonometric representation of seasonal dummies. I attach a script comparing some timings. Two of the versions perform relatively well; in practice, for a single series the gain in speed is negligible but I would prefer any of these new versions.

Kind regards

javi
http://jalobe.com

Code at: https://www.dropbox.com/s/kajhfmc89kru02h/CH-test.R?dl=0

**Comment by robjhyndman** [comment]
Apply using uroot::ch.test

**Comment by mitchelloharawild** [comment]
Resolved in 7a9de0ed08d005e5098781734b59515bd0d8a867
