### ISSUE TITLE
Auto.arima fails with seasonality test CH

### ISSUE THREAD

**Issue by rainierms19** [robjhyndman/forecast#103]
Hi,

I have a similar problem as the issue with the title "auto.arima with Canova-Hansen test fails with too many zeroes on the series#31"

Here's my code:

library(forecast)
weight<-c(28464.46, 27644.63, 26354.98, 26775.77, 46016.38, 31334.05, 
25799.93, 21439.09, 23527.61, 23953.83, 22996.17, 23807.77, 18278.14, 
21759.95, 21800.35, 23031.64, 21159.13, 20937.39, 17579.46, 22002.49, 
22685.28, 23225.34, 22049.49, 22334.83, 25063.67, 21976.78, 25041.38, 
24527.44, 24067.71, 25616.17, 27682.09, 25259.43, 25167.09, 24075.53, 
23762.14, 25797.79, 23495.41, 23714.94, 25569.91, 21762.34, 22774.47, 
23461.94, 23135.84, 23428.48, 21305.59, 22034.48, 22576.62, 23363.56, 
22760.9, 20970.42, 22248.9, 25362.03, 22396.8, 21303.68, 22178.12, 
22879.87, 22429.35, 22136.29, 21314.31, 23006.9, 18762.03, 22585.03, 
18432.34, 24380.08, 16906.22, 20072.24, 19768.2, 20951.09, 19647.7, 
22407.11, 20438.47, 23875.99, 26235.04, 24900.22, 25619.64, 24765.16, 
26245.83, 24979.97, 26835.89, 26954.57, 25789.02, 28527.69, 28527.69, 
28241.12, 29540.17, 28435.56, 25358.33, 27225.73, 28163.47, 24868.81, 
27989.6, 27294.53, 25138.9, 27862.07, 27128.98, 27683.45, 26966.48, 
26585.32, 26671.72, 26258.16, 24734.54, 26353.19, 25547.16, 26122.19, 
25064.35)
weight.ts<-ts(weight,frequency=52)
fit.weight<-auto.arima(weight.ts,stepwise=FALSE,seasonal.test=c("ch"))

and the error i get is 

Error in solve.default(tmp, tol = 1e-25) : 
  system is computationally singular: reciprocal condition number = 8.10953e-31

Based on my research, this error message comes out if there is collinearity among the variables. But my input data is a single variable/vector.
If I use ocsb test, then it works fine.
Please help and let me know how I can fix this problem.
Thank you very much for your help.

**Comment by robjhyndman** [comment]
This is due to the series being too short given the frequency of 52. I have now prevented the error occurring with https://github.com/robjhyndman/forecast/commit/286b6e4aeb2dd93b5da0227fc209cc89242be8a0
