### ISSUE TITLE
Seasonal coefficients in ETS

### ISSUE THREAD

**Issue by config-i1** [robjhyndman/forecast#104]
"coefficients" function in R returns one less seasonal coefficient than it should. For example, it will return s0 to s10 for monthly data instead of s0 to s11.
An example:
> coefficients(ets(M3$N2568$x))

The output:

>        alpha         beta        gamma            l            b           s0           s1           s2           s3           s4           s5           s6           s7           s8           s9          s10 
>        2.165810e-02 2.138159e-02 1.261955e-03 4.812537e+03 8.213480e+01 1.115512e+00 8.264085e-01 8.510733e-01 1.207049e+00 8.723206e-01 8.681461e-01 1.233918e+00 7.137628e-01 1.578858e+00 7.979522e-01 7.886988e-01

**Comment by robjhyndman** [comment]
The final seasonal component is redundant as they have to sum to 1 for additive models, and to m for multiplicative models.
