### ISSUE TITLE
dm.test adjusts small variances without warning

### ISSUE THREAD

**Issue by mdbauer** [robjhyndman/forecast#106]
The following line in `dm.test` is problematic
```
dv <- max(1e-08, d.var)
```
If the forecast error series `e1` and `e2` are small (e.g., with scale smaller than 1e-4), then this leads to a wrong result, because `d.var`, the long-run variance of the loss differential `e1^2-e2^2` (with squared error loss) is below 1e-8.  (This issue will of course occur less frequently with absolute error loss.) 

Presumably, this line is to prevent numerical issue, and may be useful. But adjusting the variance, which is central to the test result, *without a warning* is very dangerous and this behavior should be classified as a bug.

**Comment by robjhyndman** [comment]
Removed in https://github.com/robjhyndman/forecast/commit/7e17cca9bb08528aec3c99c66bfd1f77ac7b9be9
