### ISSUE TITLE
splinef fitted values same as inputs

### ISSUE THREAD

**Issue by rulero** [robjhyndman/forecast#107]
When extracting the fitted values from an splinef object the result is (pretty much) the inputs
Although not exactly the same, differences are in the order of E-08, and don't match the residuals which make more sense given any inputs I've tried

**Comment by robjhyndman** [comment]
Nonsense. 
```
> fit <- splinef(airmiles)
> lines(fitted(fit),col='red')
> sum((fitted(fit)-airmiles)^2)
[1] 3768316
```

**Comment by rulero** [comment]
Sorry, I should have provided detailed information from the beginning, my fault

```
> mydata <- c(3837.44, 5586.70, 13933.03, 8499.41, 12835.37, 22489.08, 12047.35, 19202.50, 27373.44, 13590.00, 10875.97, 8404.63, 2771.99, 5955.58, 8975.03, 8029.35, 12624.02, 23080.86, 17587.07, 24256.37, 23094.68, 13663.68, 7217.00, 3891.89)
> myts <- ts(mydata)
> myfit <- splinef(myts)
> sum((fitted(myfit) - mydata)^2)
[1] 1.840817e-16
> plot(mydata)
> lines(fitted(myfit),col='red')
> accuracy(myfit)
                    ME     RMSE      MAE       MPE     MAPE    MASE       ACF1
Training set -291.1955 11723.15 9502.599 -5.633784 79.51911 1.62358 -0.5762938
> version
               _                           
platform       i386-w64-mingw32            
arch           i386                        
os             mingw32                     
system         i386, mingw32               
status                                     
major          3                           
minor          1.2                         
year           2014                        
month          10                          
day            31                          
svn rev        66913                       
language       R                           
version.string R version 3.1.2 (2014-10-31)
nickname       Pumpkin Helmet              
```

packages.update() already executed, I'm running it right now in my x86 laptop but it was first spotted in a x64 system also with Windows OS

**Comment by robjhyndman** [comment]
The issue with this example is that the smoothing parameter is estimated to be close to zero as can be seen using
```
myfit$model
```
Compare the following two:
```
plot(myts, type='b')
lines(fitted(splinef(myts)),col='red')
lines(fitted(splinef(myts, method='mle')),col='green')
```
So this is not a bug, it is just a badly estimated parameter.

**Comment by rulero** [comment]
oh, I see

I have one last question, if may I...

Aren't all the accuracy measures too high for fitted values *that* close to the actual values?
The MAPE, for instance, I was expecting the same result from these two:

```
> mean(abs((myts - fitted(myfit))/myts)) * 100
[1] 1.814334e-11
> accuracy(myfit)[, 'MAPE']
[1] 79.51911
```
or am I missing something?

**Comment by robjhyndman** [comment]
The accuracy statistics are based on one-step forecasts. The fitted values from a spline fit are based on a smoothing spline using all observations. To see the one-step forecasts, use
```
lines(myfit$onestepf, col='green')
```

**Comment by robjhyndman** [comment]
It looks like the help file for `splinef` does not contain this information. I'll fix it in the next version.
