### ISSUE TITLE
Allow auto.arima to have include.mean=F argument

### ISSUE THREAD

**Issue by adunaic** [robjhyndman/forecast#108]
The auto.arima function has lots of functionality but does not have the same include.mean=F option that the Arima function has.  Please can this be included as i'm currently having to modify the function to auto fit without a mean (intercept) term.

**Comment by robjhyndman** [comment]
Added allowmean argument in https://github.com/robjhyndman/forecast/commit/daa3b45eceb7285448051ebab923c8f35c7e775d
