### ISSUE TITLE
TBATS error with timeseries of zeros

### ISSUE THREAD

**Issue by harmbuisman** [robjhyndman/forecast#109]
TBATS gives an error with the simple sequence of zeros.

Repro:
{library(forecast);tbats( rep(0,10) )}

Result:
Error in checkForRemoteErrors(val) : 
  3 nodes produced errors; first error: initial value in 'vmmin' is not finite

Version info:
This is forecast 5.9 
R version 3.1.3 (2015-03-09)

**Comment by tbats** [comment]
Having same issue. Any fixes? Or temporary solutions?

**Comment by robjhyndman** [comment]
Fixed in https://github.com/robjhyndman/forecast/commit/ada6da10bb993d78e6639fd63db92a8698c6f0c7
