### ISSUE TITLE
easily extracting the type of model fitted

### ISSUE THREAD

**Issue by spedygiorgio** [robjhyndman/forecast#110]
It would be nice to have a way to easily get the kind of stochastic process fitted. E.g. if we use auto.arima and we fit and ARIMA(2,1,1) with drift 0.6 it would be nice to have an easy way to get the expression of the model in character form (e.g. "ARIMA (2,1,1)...") without having to wrangle in the slots...

**Comment by robjhyndman** [comment]
forecast:::arima.string() exists, it is just not user-visible.

**Comment by spedygiorgio** [comment]
Thank Rob, is it possible to make it somewhat visible? Maybe a coerce to "character" method for forecast package's object could be a suggestion....

**Comment by robjhyndman** [comment]
Added as.character.Arima() in https://github.com/robjhyndman/forecast/commit/d106d6a79b4a4a8af49dea7f6ae2af1c83952a64
