### ISSUE TITLE
meanf : h parameter should not be equal to NULL

### ISSUE THREAD

**Issue by agstudy** [robjhyndman/forecast#117]
Trying to forecast this time series, I get this error : 

       library(forecast)
       object <- xts(2,as.POSIXct("2015-05-05"))
       Error in rep(meanx, h) : invalid 'times' argument

This also reproduce the same error : 

       forecast(object,NULL)

Looking in the code of `meanf`, it looks that is due to the fact that `rep` can't takes a NULL `times argument`

         f <- rep(meanx, h)

Either , one should assert that h is different of NULL or trying to optimizing it like you did for gamma. I can fork the code and submit a correction

**Comment by robjhyndman** [comment]
As explained in the help file, forecast requires a ts object or a numerical vector. If you try passing other classes of objects, do not expect it work.

**Comment by agstudy** [comment]
I passed an xts object ( ts ) , The error comes here from the h parameter.

**Comment by robjhyndman** [comment]
An xts object is NOT a ts object.

**Comment by agstudy** [comment]
Yes. It works fine if h is not null. Basically I get the error with `forecast` function that internally calls `meanf`. You can get the same error using a ts object : `meanf(Nile,NULL)`
