### ISSUE TITLE
Error on loading library

### ISSUE THREAD

**Issue by VanHumbeeckA** [robjhyndman/forecast#123]
I upgraded the package from 5.9 to 6.1 today.
Currently, i have R 3.2.0 installed.
Running on Windows 8.1 64bit
When loading the package with library(forecast), i get the following error:
```
> library(forecast)
Loading required package: zoo

Attaching package: ‘zoo’

The following object is masked _by_ ‘.GlobalEnv’:

    as.Date.numeric

The following objects are masked from ‘package:base’:

    as.Date, as.Date.numeric

Loading required package: timeDate
Error : .onAttach failed in attachNamespace() for 'forecast', details:
  call: fun(libname, pkgname)
  error: 4 arguments passed to .Internal(nchar) which requires 3
In addition: Warning message:
package ‘forecast’ was built under R version 3.2.1 
Error: package or namespace load failed for ‘forecast’
Called from: library(forecast)
Browse[1]> 
```

**Comment by robjhyndman** [comment]
Since you are the second person to report this, I will investigate it. Can you please send me the output from
```
sessionInfo()
```

**Comment by VanHumbeeckA** [comment]
Hi there, i recently discovered a solution, although i still don't really know what the original problem triggered. By upgrading from R 3.2.0 to R 3.2.1 this problem dissapeared. [This post](https://stackoverflow.com/questions/30955508/r-cannot-load-package-forecast-due-to-namespace-error/30956549#30956549) on stackoverflow explains it in more detail:

**Comment by bowen0701** [comment]
Hi Prof. Hyndman

My R version is 3.2.1, but I still cannot load forecast library; 
attached is the error message (PS. I used this useful library before).

Error : .onAttach failed in attachNamespace() for 'forecast', details:
  call: formatDL(nm, txt, indent = max(nchar(nm, "w")) + 3)
  error: incorrect values of 'indent' and 'width'

Thank you so much for your help!

Best wishes,
Bowen

**Comment by snanda73** [comment]
i have the same problem when trying top upload data and do ReadAffy
Error in formatDL(nm, txt, indent = max(nchar(nm, "w")) + 3) : 
  incorrect values of 'indent' and 'width'

what to do, i reinstalled R and Affy, still the same problem. Any suggestion is appreciated.
Need help for my homework. It worked when i gave space between the"=" sign suddenly, then when i  come back to work on the question, it gives the same error again.
Please help Thanks
