### ISSUE TITLE
forecast::tsclean() throws 'NA/Nan/Inf in foreign function call'

### ISSUE THREAD

**Issue by raleighlinda** [robjhyndman/forecast#128]
for time series containing  zeros tsclean()
sometimes throws an error from call to simpleLoess
examples:

> s <- c(0,0,0,0,0,0,0,0,0,0,0,0,2,0,0,0,0,0,0,0,0)
> tsclean(s)
Error in simpleLoess(y, x, w, span, degree, parametric, drop.square, normalize,  : 
  NA/NaN/Inf in foreign function call (arg 1)

at three nonzeros the function succeeded.
> s <- c(0,0,0,0,0,0,0,4,0,0,0,0,2,0,0,0,0,0,0,3,0)
> tsclean(s)
 [1] 0 0 0 0 0 0 0 4 0 0 0 0 2 0 0 0 0 0 0 3 0
> 

> s <- c(0,0,0,0,0,0,0,0,0,0,8,5,2,28,15)
> tsclean(s)
Error in simpleLoess(y, x, w, span, degree, parametric, drop.square, normalize,  : 
  NA/NaN/Inf in foreign function call (arg 1)

**Comment by robjhyndman** [comment]
Fixed in https://github.com/robjhyndman/forecast/commit/aa0232df3349fe881cdf222b69da6670e0f8318f
