### ISSUE TITLE
forecast:forecast() throws a quantile.default ... misssing values and NaN's not allowed if ..

### ISSUE THREAD

**Issue by raleighlinda** [robjhyndman/forecast#129]
This particular combination of 
input data
specifying model= "MMN"  in ets()
and setting h=18 in forecast()
caused the error ----

Error in quantile.default(newX[, i], ...) : 
  missing values and NaN's not allowed if 'na.rm' is FALSE

 > s <- ts(c(2090,2687,2874,2821,2661,2526,2283,2407,2858,2855,2759,2678,2283,2006,1420,1865,1726,1752,1656,1401,1465,1243,1019,775,653,360,349,352,337,253,210,152,178,113,114,86,107,89,60,41,82,118,71,77,67,57,52,58,60,49,14,0.1,0.1,0.1,0.1,0.1,0.1,0.1,2090,2687,2874,2821,2661,2526,2283,2407,2858,2855,2759,2678,2283,2006,1420,1865,1726,1752,1656,1401,1465,1243,1019,775,653,360))

> s.ets <- ets(s, model = "MMN")
> forecast(s.ets)
   Point Forecast Lo 80        Hi 80 Lo 95         Hi 95
85    198.4915107     0 5.851867e+05     0  9.209497e+05
86    109.4355512     0 4.989827e+11     0  2.883661e+12
87     60.3357787     0 1.259073e+19     0  6.889658e+21
88     33.2652977     0 1.544470e+18     0  4.541465e+33
89     18.3403621     0 7.518420e+20     0  6.680052e+45
90     10.1117052     0 8.646620e+25     0  1.617294e+53
91      5.5749489     0 1.505744e+28     0  2.024390e+64
92      3.0736710     0 4.370081e+34     0  4.456501e+74
93      1.6946260     0 1.280005e+43     0  1.509090e+86
94      0.9343086     0 1.191004e+51     0 2.386175e+100
> forecast(s.ets, h= 18)
Error in quantile.default(newX[, i], ...) : 
  missing values and NaN's not allowed if 'na.rm' is FALSE

**Comment by robjhyndman** [comment]
Fixed in https://github.com/robjhyndman/forecast/commit/8b67cf35aa702ebb41c558a4523b4b447fd0001a
