### ISSUE TITLE
auto.arima with trace=TRUE values

### ISSUE THREAD

**Issue by pfv07** [robjhyndman/forecast#135]
If the trace=TRUE, this print the model and a value, what is this value ?, because its diferent for the ic values in the best model selected. In the example the value for the best model is 924.795
and ics are: AIC=1029.69   AICc=1029.96   BIC=1037.26

ARIMA(2,1,2)(1,1,1)[12]                    : Inf
ARIMA(0,1,0)(0,1,0)[12]                    : 954.051
ARIMA(1,1,0)(1,1,0)[12]                    : 924.795
ARIMA(0,1,1)(0,1,1)[12]                    : Inf
ARIMA(1,1,0)(0,1,0)[12]                    : 946.442
ARIMA(1,1,0)(2,1,0)[12]                    : 929.0547
ARIMA(1,1,0)(1,1,1)[12]                    : Inf
ARIMA(1,1,0)(2,1,1)[12]                    : 929.8475
ARIMA(0,1,0)(1,1,0)[12]                    : 933.6663
ARIMA(2,1,0)(1,1,0)[12]                    : 927.8044
ARIMA(1,1,1)(1,1,0)[12]                    : 926.2389
ARIMA(2,1,1)(1,1,0)[12]                    : 929.594

 Best model: ARIMA(1,1,0)(1,1,0)[12]                    

Series: dat 
ARIMA(1,1,0)(1,1,0)[12]                    

Coefficients:
         ar1     sar1
      0.3392  -0.5716
s.e.  0.0976   0.0899

sigma^2 estimated as 3775:  log likelihood=-511.85
AIC=1029.69   AICc=1029.96   BIC=1037.26

**Comment by robjhyndman** [comment]
If approximation=TRUE, it is the approximated AICc value.
