### ISSUE TITLE
How to determine seasonality in auto.arima

### ISSUE THREAD

**Issue by zhuzelong** [robjhyndman/forecast#139]
Wish you would not mind me asking questions here. I am a bit confused of the `Arima()` and `auto.arima()`.

I have an irregular time series (unit is day) stored in a `zoo` object. It is irregular because no data on holidays and weekends. 

The function `as.ts()` converted the `zoo` into a regular ts with `NA` interpolated. But the resulting ts has a frequency 1. So `auto.arima()` seemed to exclude all seasonal terms even though I specified `D=1, max.D=30`.

If I converted the `zoo` explicitly by `ts(zoo, start=, frequency=340)` (340 is due to exclusion of holidays and weekends), then `auto.arima` would include seasonal terms.

The question is, the ts is irregular and conversion by `ts(..., freq=340)` led to wrong time series. Is there any approaches that `forecast` can deal with the issue?

**Comment by robjhyndman** [comment]
This is not a help site. It is intended for bug reports only. Please ask questions on crossvalidated.com
