### ISSUE TITLE
Larg and negative values in forecasting positive time series

### ISSUE THREAD

**Issue by lassaw** [robjhyndman/forecast#141]
Thank you for your reply. here is an example of the bug i get :

" I used to forecast daily positive time series using tbats. But in some cases i get négatives or very long values like 1.25868e+14 where my real values are between 0 and 50000. I tried to include lamda=0 in my models but it doesn't work any more. I would like to know if there is a solution to avoid that problems ?"

Exemple of table
![datas](https://cloud.githubusercontent.com/assets/13781192/9249967/c9ad82be-41c9-11e5-96c3-b790d448fd45.PNG)

Code used
![r_code](https://cloud.githubusercontent.com/assets/13781192/9250291/1d3b3564-41cc-11e5-9bf9-1cfafdfeb54e.PNG)

Calling town_fc("lille",10) or town_fc("bayonne",10)
These are 10 forecast values i get :
![forecast values](https://cloud.githubusercontent.com/assets/13781192/9250242/c9db85d6-41cb-11e5-99c2-f7ccdf9043c6.PNG)

Thank you in advance.

Alassane

**Comment by robjhyndman** [comment]
Please provide a reproducible example of the problem. Also make sure you are using the latest version of the package as a similar problem to this was resolved in recent updates.

**Comment by lassaw** [comment]
Thank you sir,
I dont't get bug reports but just incorrect values in the output table. I'm updating the forecast package, now i have the 6.1 version, is it the last version ? Also, i notice that, the execution of tbats command takes lot of time, is there a way to reduce it ?

Thank you for your help

**Comment by robjhyndman** [comment]
This is not a help site. It is for bug reports only. Unless you provide a reproducible example of any problem, I will close this issue.

**Comment by lassaw** [comment]
Well received, i will manage to provide a reproducible exemple of any bug reports.
