### ISSUE TITLE
Different results with different versions of R

### ISSUE THREAD

**Issue by vicmgg** [robjhyndman/forecast#145]
Hi, I have the R version 3.2.0 in one computer and the version 3.2.2 in another and the same version of the package "forecast" (6.1) in both of them. So, when I apply the auto.arima function with d=1 to the vector "fec1" (see below) in the computer with version 3.2.0 it gives me an ARIMA(1,1,1) while in the computer with version 3.2.2 it gives me an ARIMA(1,1,0) with drift. Why does such difference happens? When I skip the d=1, I get the same result in both computers. Thanks in advance.

fec1 <- c(9.53408021, 9.48993631, 9.44261613, 9.38585482, 9.31611858, 9.24743801, 9.19483663, 9.11690414, 9.05586032, 8.96781034, 8.85437896, 8.73956021, 8.62587246, 8.49758284, 8.41877774, 8.29737132, 8.02294327, 7.62604834, 7.32936532, 7.10006394, 6.87039464, 6.56332757, 6.27195705, 5.97089310, 5.69537808, 5.46074967, 5.19061116, 4.90749261, 4.61822473, 4.39635507, 3.96883450, 3.71230296, 3.43604354, 3.15150833, 2.82864081, 2.51857560, 2.27264470, 2.06785600, 1.86116599, 1.61452534, 1.41214847, 1.26673153, 1.15033592, 1.00646045, 0.83493055, 0.65399085, 0.47450499, 0.30408840, 0.18216540, 0.09006937, 0.00000000)

**Comment by robjhyndman** [comment]
As you are using the same version of the forecast package, it has nothing to do with the forecast package. Most likely it is due to improvements in the optimizer used by arima() from the stats package, or possibly changes in the initialization used by arima(). You would have to see what changes were made to arima() or optim() between versions of R.

**Comment by vicmgg** [comment]
Thanks Rob.

All the best,

Víctor

*Dr. Víctor Manuel García-Guerrero*
*Profesor-Investigador*

*Coordinador de la Maestría en Demografía*Centro de Estudios
Demográficos, Urbanos
y Ambientales
El Colegio de México A.C.
Tel. +52 55 5449 3032

2015-08-26 19:52 GMT-05:00 Rob J Hyndman <notifications@github.com>:
