### ISSUE TITLE
forecast::tsclean()  - unexpected results - tsclean changes points dramatically and unlike neighbors

### ISSUE THREAD

**Issue by raleighlinda** [robjhyndman/forecast#146]
tsclean - replacements made with values that are very different from neighbors creating odd spikes in the cleaned time series

raw <- c(4315,12178,2619,5826,2162,3196,2359,1443,2955,3613,1985,2084,2664,4294,
         7777,3173,2279,5645,1813,660,611,173,0,0,3,4,1,13,3,5,15,1,3,0,0,6,4,3,
         8,1,0,0,0,0,3,0,6,1,10,2,1,2,1,2,2,0,0,0,0,0)
raw.ts <- ts(raw,start=c(2011, 1), end=c(2015, 8),frequency=13)
plot(raw.ts,pch=20,main="Original Series")
points(raw.ts,pch=20)
![image](https://cloud.githubusercontent.com/assets/3473486/9764575/cf821000-56dd-11e5-91ca-c2b3e0681260.png)

clean.ts <- tsclean(raw.ts)
plot(clean.ts, col ="blue", main = "Tscleaned Series")
points(clean.ts, col ="blue",pch=20)

![image](https://cloud.githubusercontent.com/assets/3473486/9764585/de0850e4-56dd-11e5-8213-33c54654cb62.png)

**Comment by robjhyndman** [comment]
Thanks for the example. I'll see if I can modify tsclean to avoid this sort of thing.

**Comment by robjhyndman** [comment]
Fixed in https://github.com/robjhyndman/forecast/commit/02a3c84491435d89d28aee194fc643a8573bc8f0

**Comment by praveen24kumar** [comment]
On executing tsclean with ts data I'm getting following error:

Error in `^.default`(abs(x), lambda) : 
  non-numeric argument to binary operator

Please suggest.
