### ISSUE TITLE
fan argument for forecast.stlm()

### ISSUE THREAD

**Issue by dashaub** [robjhyndman/forecast#151]
The documentation states that the ```fan``` argument sets ```level``` to ```seq(50,99,by=1)```
However, this example below seems to indicate that it is in fact ```seq(from = 51, to = 99, by  = 3)```
```forecast(stlm(wineind), fan = TRUE)$level```

Many files (e.g. season.R, spline.R, arfirma.R, arima.R, and etsforecast.R) use the sequence starting at 51 and going by 3, so I'm guessing it is the documentation file forecast.stl.Rd that needs correction.

If this is the case, I have it fixed in the documentation of my fork of the repo and can put in a pull request.

**Comment by robjhyndman** [comment]
Thanks. Now fixed in https://github.com/robjhyndman/forecast/commit/095c8314796eb3d9959379c16ba059e81171746a
