### ISSUE TITLE
lambda in code for forecast.ar()

### ISSUE THREAD

**Issue by dashaub** [robjhyndman/forecast#153]
The following appears in the the code for ```forecast.ar()```:
```
    if (!is.null(lambda)) {
        pred$pred <- InvBoxCox(pred$pred, lambda)
        lower <- InvBoxCox(lower, lambda)
        upper <- InvBoxCox(upper, lambda)
        fits <- InvBoxCox(fits, lambda)
        x <- InvBoxCox(x, lambda)
    }
```
Why is the ```lambda``` argument allowed by ```forecast.ar()```? Aren't all ```ar``` objects generated by ```stats::ar()```?

It appears ```stats::ar()``` doesn't do anything when ```lambda``` is passed as an additional argument.
```
set.seed(55)
simseries <- arima.sim(model = list(ar = runif(4, min = -.2, max = .2)), n = 400)
forecast(ar(simseries, order.max = 5))$upper == forecast(ar(simseries, order.max = 5, lambda = .1))$upper 
# All true
```
Models fit by ```forecast::Arima()``` could have the Box-Cox transform, but they are not ```ar``` objects even if they have no other ma, etc components.
```
arimafit <- Arima(simseries, order = c(4, 0, 0), lambda = .1)
class(arimafit)
# ARIMA Arima
```
Is ```lambda``` allowed as a future enhancement? To allow users to manually transform ```ar``` objects (since the ```ar``` models from stats won't carry the lambda properties)? Can some function from "forecast" produce an ```ar``` with the lambda property stored in the object (but users calling ```forecast.ar()``` would still have to manually specify lambda)? As an oversight?

**Comment by robjhyndman** [comment]
Consider the following example:

```
library(forecast)
fit <- ar(BoxCox(lynx,0.5))
fc <- forecast(fit, lambda=0.5)
plot(fc)
```
