### ISSUE TITLE
extract components of ets()

### ISSUE THREAD

**Issue by emriva** [robjhyndman/forecast#158]
Is it possible to have a function able to extract ets() components (level, slope, sesaonality) like tbats.components does with tbats() function?

**Comment by robjhyndman** [comment]
There's no need. They are returned as the states object. e.g.,
```
fit <- ets(WWWusage)
plot(fit$states)
```

**Comment by emriva** [comment]
Thanks Rob,

 

Could you add this info in ets() documentation, with the explanation of the meaning of columns (I understood that the first 3 columns are related to level, slope and seasonality but what about the others? ).

 

Thanks

RGDS

 

Enrico

 

 

Da: Rob J Hyndman [mailto:notifications@github.com] 
Inviato: giovedì 24 settembre 2015 23:41
A: robjhyndman/forecast <forecast@noreply.github.com>
Cc: emriva <enrico@martico.it>
Oggetto: Re: [forecast] extract components of ets() (#158)

 

There's no need. They are returned as the states object. e.g.,

fit <- ets(WWWusage)
plot(fit$states)
