### ISSUE TITLE
seasonal and initial arguments in hw() and holt() 

### ISSUE THREAD

**Issue by dashaub** [robjhyndman/forecast#165]
I've found some strange code in the `holt()` and `hw()` functions that doesn't match the documentation.

First, this works fine (and `summary()` reports the method as multiplicative )
```
summary(hw(gas, seasonal = "fake value"))  # Forecast method: Holt-Winters' multiplicative method
```
This could be fixed by adding argument matching in the `hw()` function for `seasonal`. It seems that `"multiplicative"` should be an acceptable value of `seasonal` too, in which case the documentation and function header should show `seasonal = c("additive", "multiplicative")`,

Second, there is code in `holt()` that checks `if(initial == "heuristic")`. However, `heuristic` is not a possible value according to the function's documentation (or the function header, so this if statement could never be true). Is `heuristic` intended as an as-yet unimplmeented option?

**Comment by robjhyndman** [comment]
Thanks for spotting those.

1. Yes, anything other than "additive" is currently interpreted as "multiplicative". It would be better to use match.arg() to restrict the options.

2. That's an error. It should say `if(initial == "simple")`. 

Feel free to issue a pull request with fixes.
