### ISSUE TITLE
Pass Fitted ETS Models to etsmodel parameter on stlm.

### ISSUE THREAD

**Issue by harryrose** [robjhyndman/forecast#167]
It would be good to allow fitted ETS models to be passed into the `etsmodel` parameter of `stlm`.  Currently it seems only possible to pass a character string.

**Comment by robjhyndman** [comment]
You can do that via the modelfunction argument. Here is an example:

```
stlfit <- stl(USAccDeaths, s.window="periodic")
etsmod <- ets(seasadj(stlfit))
modfunc <- function(x,mod,...){return(ets(x,model=mod,...))}
tsmod <- stlm(USAccDeaths, modelfunction=modfunc, mod=etsmod)
plot(forecast(tsmod, h=36))
```

**Comment by harryrose** [comment]
Thanks for the fast reply.  I'll use the modelfunction argument.
