### ISSUE TITLE
Allow conditional mean forecasts when Box-Cox transformations are used.

### ISSUE THREAD

**Issue by robjhyndman** [robjhyndman/forecast#17]

**Comment by mitchelloharawild** [comment]
@robjhyndman 
Fixed in #208

**Comment by robjhyndman** [comment]
Still needed in nnetar()

**Comment by mitchelloharawild** [comment]
Which approach did you have in mind for adding biasadj to nnetar?
Since `nnet::predict.nnet()` doesn't provide intervals, nor does your avnnet directly provide residuals (the residuals are less of a concern, as they can be computed from fits).

**Comment by robjhyndman** [comment]
Oops. Sorry. I'd forgotten we had no variance or intervals for nnetar.
