### ISSUE TITLE
ci.type argument in tsdisplay()

### ISSUE THREAD

**Issue by dashaub** [robjhyndman/forecast#177]
The `tsdisplay()` function uses `"white"` as the default value of `ci.type` but also checks at one point if it is `"ma"`. The `tsdisplay` documentation states that acceptable values can be those for `acf` (and provides a link). However, I see that `ci.type` is being passed as an optional argument to `plot.acf`. The help file for `acf` therefore does not contain an explanation what acceptable values are, and only by visiting the documentaiton for `plot.acf` do we see the explanation for the white noise or MA process for generating the confidence intervals.
Furthermore, the argument matching and error handling occurs in the `acf` function. This doesn't throw an error until `plot.acf`
```
tsdisplay(oil, ci.type = "fake value")
```
This is a problem too because the graphing window will leave `par` stuck with the three plotting windows that `tsdiplay` creates instead of nicely cleaning up the environment to what the user had previously.

It would seem better for the user to make all of this more clear with the following:
1) Argument matching in `tsdisplay` for the `ci.type` function with `"white"` as default and `"ma"` as acceptable.
2) Updating the `tsdisplay` documentation to include an explanation taken from `plot.acf`, i.e. "should the confidence limits assume a white noise input or for lag k an MA(k-1) input?"

**Comment by robjhyndman** [comment]
Good idea
