### ISSUE TITLE
lag-1 values in Acf missing?

### ISSUE THREAD

**Issue by lotterdata** [robjhyndman/forecast#178]
I’m seeing some discrepant results compared to the act functions in the TSA and stats packages. If I’m looking at this right, it seems the lag-1 correlations are being dropped. Here’s a little function I wrote to make the comparison for an arbitrary time series.

```
library(forecast)
library(TSA)


compareACF <- function(time.series){
  temp <- NULL
  temp$forecast <- Acf(time.series)$acf[1:10]
  temp$TSA <- TSA::acf(time.series)$acf[1:10]
  temp$stats <- stats::acf(time.series)$acf[1:10]
  data.frame(temp)
}
```

I've tried a few cases, and each time the values following the expected 1.0 for 0-lag is the lag-2 correlation from the other packages' functions.

**Comment by lotterdata** [comment]
Upon further investigation, I've found this problem occurs only when TSA is loaded. Seems likely that this is due to the fact that act from the stats package is masked when TSA is loaded. This can probably be fixed by using "stats::act" when calling the act function.

**Comment by robjhyndman** [comment]
Thanks for spotting the problem. Now fixed
