### ISSUE TITLE
etsmodel Parameters out of range

### ISSUE THREAD

**Issue by VadimSokolov** [robjhyndman/forecast#179]
When I run ets function, for certain values of alpha and beta, I get the following error:
Error in etsmodel(y, errortype[i], trendtype[j], seasontype[k], damped[l],  : 
  Parameters out of range

**Comment by robjhyndman** [comment]
Please provide a minimal reproducible example.

**Comment by robjhyndman** [comment]
Please provide a minimal reproducible example.

**Comment by VadimSokolov** [comment]
Here it is:
temp = readRDS(gzcon(url('https://www.dropbox.com/s/cpq69wwlwgkbdwz/ets_fail_sample.rds?dl=1')))
temp.ets = ets(res, model = 'AAN',alpha=0.4, beta=0.5, damped=T)

**Comment by robjhyndman** [comment]
You are specifying parameters that are inadmissible. beta must be less than alpha. Do not specify the parameters and let ets() estimate them.
