### ISSUE TITLE
Data scale and/or sample size issue with auto.arima

### ISSUE THREAD

**Issue by CarryOn-DrG** [robjhyndman/forecast#181]
I tried running auto.arima on a ts object with 730 observations and received the following error:
Error in solve.default(res$hessian * n.used, A) : 
  system is computationally singular: reciprocal condition number = 1.65928e-16.

However, in a subsequent run using the same dataset, I scaled the observations by 1 million so that instead of a typical value being something like 56261248 it was now expressed as 56.261.  This time auto.arima worked just fine.  Are you aware of anyone else running into this circumstance in the past?  

Furthermore, I noticed that if I reduce my sample size to below 200 that auto.arima works just fine whether or not I scale the data.  I'm happy to provide sample data but wanted to first check if this type of issue is something you are already familiar with off-hand.

Thanks!

**Comment by robjhyndman** [comment]
Please provide a minimal reproducible example. The error is probably due to a rank deficient regressor matrix. It is likely that the smaller sample size removes the collinearity, and the scaling is masking the problem.
