### ISSUE TITLE
ets doc does not match code

### ISSUE THREAD

**Issue by davidthaler** [robjhyndman/forecast#183]
In the ets() function, the code says that the default value for allow.multiplicative.trend is FALSE, but the doc says that the default is TRUE.

code: https://github.com/robjhyndman/forecast/blob/master/R/ets.R#L5
doc: https://github.com/robjhyndman/forecast/blob/master/man/ets.Rd#L46

**Comment by robjhyndman** [comment]
Thanks. Now fixed at https://github.com/robjhyndman/forecast/commit/779b5a9b6432b8eeef236c61ae5e81472771937b
