### ISSUE TITLE
Robustness and correctness of subset.ts()

### ISSUE THREAD

**Issue by dashaub** [robjhyndman/forecast#186]
I'm looking through subset.R and its accompanying .Rd, and a few things have me puzzled.

First, it appears the `quarter` argument does not work properly with monthly data:
```
frequency(wineind) # 12
subset.ts(wineind, quarter = 5) # no error, shouldn't this be limited to 4?
```
It appears `quarter` is being used synonymously with month when the ts frequency is 12:
```
all(subset(wineind, quarter = 1) == subset(wineind, month = "January")) # TRUE
all(subset(wineind, quarter = 9) == subset(wineind, month = "September")) # TRUE
```
Now if this is quarterly data, the function behaves as I would expect:

```
frequency(cafe) # 4
subset(cafe, quarter = 5) # error
# First observation is in Q2
all(subset(cafe, subset = c(FALSE, FALSE, FALSE, TRUE)) == subset(cafe, quarter = 1)) # TRUE
all(subset(cafe, subset = c(TRUE, FALSE, FALSE, FALSE)) == subset(cafe, quarter = 2)) # TRUE
```
It looks like there should be a robustness check of the ts frequency that is passed in (this would be a good idea anyway to make sure the ts has frequency 4 or 12). Furthermore, either the `quarter` argument should be ignored with a monthly series (and a warning thrown) or the subset behavior should be fixed to grab the appropriate months. To further illustrate the problem, note the behavior here
```
frequency(taylor) # 336
all(subset(taylor, month = "January") == subset(taylor, quarter = 1)) # TRUE
# Should we throw an error when subsetting using month/quarter on series with a frequency not 4 or 12?
```

Second, the documentation describes the `month`, `quarter`, and `season` arguments as accepting character lists (for `month`) and numeric lists for `quarter` and `season`. They also accept character vectors (for `month`) and numeric vectors for the other arguments. Vectors seem to be the more likely way it would be used (and even the examples from the .Rd do not use lists), so the documentation should be updated to include vectors as being acceptable.
```
all(subset(wineind, month = list("June", "October")) == subset(wineind, month = c("June", "October"))) # TRUE
all(subset(wineind, month = list("April")) == subset(wineind, month = "April")) # TRUE
```

Finally, the `month` argument sometimes produces a warning when longer lists/vectors are used and does not work when noncontiguous months are used.
```
subset(a10, month = "January") # ok
subset(a10, month = c("January", "July")) # Same results as subset(a10, month = "January")
subset(a10, month = c("July", "January")) # Same results as subset(a10, month = "July")
subset(a10, month = c("July", "August")) # ok
subset(a10, month = c("July", "September")) # Same results as subset(a10, month = "July")
subset(a10, month = c("July", "August", "September")) # ok
subset(wineind, month = c("July", "August", "September")) # ok, but a warning (the warning isn't produced in subst.ts(), however)
```
A similar phenomenon can be observed with the `quarters` argument.
The code in subset.R that is responsible for these results appears to be
```
x.time <- subset(time(x),cycle(x)==season)
```
Are these desired behaviors? Should multiple months and non-contiguous months/quarters be allowed?

**Comment by robjhyndman** [comment]
I've now rewritten `subset.ts` to fix these problems and to add some additional functionality. See https://github.com/robjhyndman/forecast/commit/b8c4edda5d4d924b6d00dd4e93b758eddc67affb
