### ISSUE TITLE
Parameter "centre" doesn't do what it should in ma function

### ISSUE THREAD

**Issue by config-i1** [robjhyndman/forecast#191]
Hi Rob,
It looks like parameter "centre" in "ma" function behaves strangely: when you set it to FALSE, it still produces centred moving average in the output. At least it seems that there's no difference in the output with or without "centre=FALSE".
An example:

ma(c(1:7),order=3,centre=TRUE)
[1] NA  2  3  4  5  6 NA

ma(c(1:7),order=3,centre=FALSE)
[1] NA  2  3  4  5  6 NA

We checked it in different versions of forecast (5.2, 5.9, 6.1, 6.2).

**Comment by robjhyndman** [comment]
The centre argument only matters when order is even. I'll update the docs to give more information.

**Comment by config-i1** [comment]
Okay. Thanks for the clarification.
