### ISSUE TITLE
Allow "refit" for bats and tbast objects

### ISSUE THREAD

**Issue by spedygiorgio** [robjhyndman/forecast#192]
When a bats or tbats object, It would be nice to use the coefficient structure of these models unchanged in order to apply to a new series, maybe to compare actual outcome and prediction. In other words, it is possible to apply the procedure shown http://stats.stackexchange.com/questions/55937/how-to-use-a-fitted-model-parameters-for-forecasting-other-time-series to bats and tbats?

**Comment by Yongyiw** [comment]
Check this https://github.com/robjhyndman/forecast/issues/15

I believe both `bats()` and `tbats` are able to refit previous models.
