### ISSUE TITLE
package

### ISSUE THREAD

**Issue by rehmanasif** [robjhyndman/forecast#197]
how to create the package of forecast into another package with different name

**Comment by robjhyndman** [comment]
I don't know what this means, but it doesn't sound like an issue for the forecast package. Please direct general questions to stackoverflow.com.

**Comment by rehmanasif** [comment]
I have created a sample package.In that we should add forecast package?

**Comment by znmeb** [comment]
@rehmanasif I'd recommend Hadley Wickham's book R Packages. You can read it online at http://r-pkgs.had.co.nz/ - Table of Contents is at upper left.

**Comment by rehmanasif** [comment]
The above link is helpful for me,but I want to built one sample package name some- x .in that x package i want the some default packages of r like ts,fpp etc into x.when i run the x package it should work

**Comment by mitchelloharawild** [comment]
You can include fpp as a dependency to your package, and then it will be loaded when you run library(x).
http://r-pkgs.had.co.nz/description.html#dependencies

**Comment by rehmanasif** [comment]
when i am building the package i got this kind of error how to rectify please help on this



Error in library.dynam(lib, package, package.lib) : 
  DLL 'TTR' not found: maybe not installed for this architecture?
Error: loading failed
Execution halted
ERROR: loading failed
* removing 'C:/Users/user/Documents/R/win-library/3.2/Accuracy'
* restoring previous 'C:/Users/user/Documents/R/win-library/3.2/Accuracy'

Exited with status 1.
