### ISSUE TITLE
[Bug+fix] seasonplot can fail to produce correct left labels due to rounding error

### ISSUE THREAD

**Issue by justa9** [robjhyndman/forecast#199]
It seems that `seasonplot` can fail to produce correct left labels in the case where the machine representation of the numeric value that `year` holds differs enough that the truncation fails to produce the desired output.

The culprit lies in this segment near the end of the `seasonplot` function definition:
```
if (year.labels.left) {
        idx <- which(Season[!is.na(xnew)] == 1)
        year <- time(tsx)[idx]
        if (min(idx) > 1)
            col <- col[-1]
        text(x = rep(1 - labelgap, length(year)), y = tsx[idx],
            labels = paste(c(trunc(year))), adj = 1, ..., col = col[1:length(idx)])
    }
```

After running `seasonplot` line-by-line in such a corner case:

```
> year
[1] 2014 2015
> trunc(year)
[1] 2014 2014
```

The reason should be clear if we try to print more decimal places:

```
> sprintf("%.15f", year)
[1] "2014.000000000000000" "2014.999999999999773"
```

However, note that: 
```
> as.character(year)
[1] "2014" "2015"
```

which means that if we substitute: `labels = paste(c(trunc(year)))` with `labels = as.character(year)`, we get the expected output.

**Comment by mitchelloharawild** [comment]
As far as I am aware, this is intended behaviour.
Could you produce a minimally reproducible example for where these labels are incorrect?

Although the year "2014.999999999999773" is very close to 2015, it is still the year 2014.
Converting this decimal to a date time gives "2014-12-31 23:59:59 GMT", which is the last second of 2014.

**Comment by justa9** [comment]
@mitchelloharawild  Apologies for the delay.

I do not think that this is a "last second" type of expected behavior, since we have just monthly values.

Providing a *reproducible* example is not something that I can do, due to the fact of the issue (i.e. representation of the numbers in the machine level is not a deterministic process on the level of the actual numbers: we have no way of knowing whether 2015 will be represented as 2015.0000000 or as 2014.999999, or as 2015.000000000001; number of zeros is arbitrary), which means that it doesn't happen all the time. It is a corner case. However, here is a snippet that *may* produce the problem.

```
ts1 <- structure(c(16120, 12688, 7918, 7668, 6308, 5772, 5900, 6045,
7542, 5282, 5110, 4908, 5068, 4772, 4140, 4435, 3938, 3932, 4726,
5478, 4535, 4188, 4278, 4708, 4676, 4205, 4640, 4078, 3585, 3880,
3795, 3628, 3316, 3310, 3250, 3748, 3092, 2930, 2772, 3048, 3108,
2356, 2002, 1602, 1300, 1165, 1145), .Tsp = c(2012.16666666667,
2016, 12), class = "ts")

ts2 <- structure(c(16120, 12688, 7918, 7668, 6308, 5772, 5900, 6045,
7542, 5282, 5110, 4908, 5068, 4772, 4140, 4435, 3938, 3932, 4726,
5478, 4535, 4188, 4278, 4708, 4676, 4205, 4640, 4078, 3585, 3880,
3795, 3628, 3316, 3310, 3250, 3748, 3092, 2930, 2772, 3048, 3108,
2356, 2002, 1602, 1300, 1165, 1145), .Tsp = c(2012.16666666667,
2016, 12), class = "ts")

all.equal(ts1, ts2) #TRUE
identical(ts1, ts2) #FALSE


par(mfrow=c(1,2))
seasonplot(ts1, year.labels=T, year.labels.left=T)
seasonplot(ts2, year.labels=T, year.labels.left=T)
```

![seasonplot](https://cloud.githubusercontent.com/assets/3420355/12371128/9d41ebb0-bc31-11e5-9fc2-820e5f3b0789.png)


You can see that the second seasonplot exhibits the problem, while the first one does not.
I understand that perhaps there might be no way to reproduce this example (other than the word of me, or of some fellow user who might encounter it in the future), however I would like to suggest that you consider implementing a solution (if you agree). Right now, I'm using a seasonplot function identical to the one in the package, except from the fix I proposed, and have not encountered any side effects.

**Comment by mitchelloharawild** [comment]
Ah, so there is a mismatch in how newlines for seasonplots are created and how they are named.
I agree that there is an issue here with what is displayed, and will look into it tomorrow.

all.equal() uses some approximation in it, which is why it is true as 2014.999999 "equals" 2015.000000000001. However for the plot, if 2014.999999 is in the data, then it should be on the line for 2015, not creating a newline labelled 2015.

Thanks for finding this issue.

**Comment by mitchelloharawild** [comment]
Which version of R are you running?

I've ran this code for several million loops (on R 3.2.2 Fire Safety) and have never encountered identical(ts1, ts2) = FALSE. How frequently does this occur for you?

At this stage, I'm apprehensive about simply replacing trunc() with as.character() as it is more likely that someone has data in the last second of the year, than this machine level number representation issue occurring. We could select labels using different methods depending on the data's frequency, to set some sort of sensitivity to these machine level inaccuracies... but for a plotting function that seems over the top.

**Comment by justa9** [comment]
Running  "R version 3.2.3 (2015-12-10)". 

Sorry for misleading: one of the timeseries (ts2) was created by being assigned the value of a list element (list contains similar timeseries). Afterwards, `dput` was used to produce the readable code ("structure(c..") in order to paste it here. Running the code exactly as I posted does not produce the bug as I implied. Again, apologies for misleading.

However, the bug is stil produced when using the package function on (some elements of) the list. I can understand your apprehension, though I am not fully sure it applies to the particular matter (as I think that the values inside that particular point in `seasonplot` correspond to start and end of one particular year, thus the __left__ seasonplot label corresponds to the start of the year which the line describes), however I will respect your decision. 

Perhaps, there can be a parameter option which allows the user to choose the function (with a default of "trunc").

**Comment by mitchelloharawild** [comment]
Changing
```R
year <- time(tsx)[idx]
```
to
```R
year <- round(time(tsx)[idx], nchar(s))
```
Should resolve any issues resulting from machine level representation of the data, whilst allowing frequencies of seconds to be plotted correctly. Let me know if this suits your use case.

**Comment by justa9** [comment]
@mitchelloharawild Yes, this seems to fix the issue.

Thank you very much for your patience and dilligence.
