### ISSUE TITLE
Avoid unnecessary warning in plot.forecast

### ISSUE THREAD

**Issue by RubenCrevits** [robjhyndman/forecast#200]
An unnescessary warning pops in the following case:
"fit = ets(USAccDeaths)
f = forecast(fit,PI=FALSE)
plot(f)
Warning message:
In max(x$upper) : no non-missing arguments to max; returning -Inf"

This is because x$upper is NULL. Therefore I suggest to check is.finite(max(x$upper)) only when it is not NULL in plot.forecast.

I suggest to adapt a few lines of plot.forecast:
" if(is.null(x$lower) | is.null(x$upper) | is.null(x$level) ){
     plot.conf=FALSE
   }else if(!is.finite(max(x$upper))){
      plot.conf=FALSE
    }
"

instead of 

" if(is.null(x$lower) | is.null(x$upper) | is.null(x$level) |(!is.finite(max(x$upper))) ){
     plot.conf=FALSE
   }
"

**Comment by mitchelloharawild** [comment]
Pull request #201 
Unusual that R doesn't escape the or condition as soon as true occurs (left to right).

**Comment by robjhyndman** [comment]
Fixed in https://github.com/robjhyndman/forecast/commit/2268471cce5da6c16fce8e1b7faaada7a0aed3e3
