### ISSUE TITLE
ets() initstate seasonal indices, changes while model calculation

### ISSUE THREAD

**Issue by pavolloffay** [robjhyndman/forecast#240]
Hello,

in the etsmodel() function initial seasonal indices are calculated in initstate() function https://github.com/robjhyndman/forecast/blob/master/R/ets.R#L333 but different values are returned after finishing est() function.

**Comment by robjhyndman** [comment]
Yes, what's your point?

**Comment by pavolloffay** [comment]
I though they won't change during calculation (etscalc).

Could you please explain me little bit how seasonal indices are calculated (or changed) in etscalc function? And also how to calculate the first seasonal index since here https://github.com/robjhyndman/forecast/blob/master/R/ets.R#L708 first is omitted.

Thanks,
Pavol

**Comment by robjhyndman** [comment]
They are estimated by maximum likelihood along with the smoothing parameters. The *initial* values are computed using initstate(). These are then refined in the optimization routine. All explained in the book: https://www.otexts.org/fpp/7/7
