### ISSUE TITLE
Messy output of auto.arima when parallel = TRUE

### ISSUE THREAD

**Issue by ludovictheate** [robjhyndman/forecast#261]
The output of auto.arima changes drastically when the option parallel is set to TRUE. This is an issue as the whole time-series is printed which makes the output difficult to read.

Example:

> auto.arima(data,d=0,D=1,xreg=1:119,seasonal=TRUE,allowdrift=TRUE,stepwise=FALSE,approximation=FALSE,ic=("aic"),parallel=FALSE)

Series: data 
ARIMA(3,0,0)(0,1,1)[12]                    

Coefficients:
         ar1     ar2     ar3     sma1   1:119
      0.0453  0.1548  0.2341  -0.7624  0.0019
s.e.  0.0935  0.0932  0.0938   0.1245  0.0003

sigma^2 estimated as 0.001983:  log likelihood=175.81
AIC=-339.61   AICc=-338.77   BIC=-323.58
> 
> auto.arima(data,d=0,D=1,xreg=1:119,seasonal=TRUE,allowdrift=TRUE,stepwise=FALSE,approximation=FALSE,ic=("aic"),parallel=TRUE)

Call:
auto.arima(x = structure(list(x = structure(c(4.95544127661749, 4.80333360039729, 
4.90123143366908, 4.72550824846432, 4.82682043851698, 4.8081150741008, 4.71593597743032, 
4.65168869569841, 4.72508290547833, 4.89757682795692, 4.85865376394986, 4.70139744951747, 
4.91643875282444, 4.77014899788405, 4.91123684491345, 4.80760276903324, 4.88772468137775, 
4.88500695175344, 4.84505242312625, 4.66752361395451, 4.77588267260681, 4.89764952902214, 
4.85027372020489, 4.70300253891795, 4.99837111130447, 4.85259394141247, 4.82728492825307, 
4.9672661514606, 4.89746645720249, 4.92002278392945, 4.88324379802441, 4.7340531047945, 
4.8493313616548, 4.97105175850955, 4.82692602761926, 4.74979566398128, 4.96955936666879, 
4.86154158003748, 4.96134578163827, 4.87419541545993, 4.85215748776421, 4.94005214333675, 
4.89425313141333, 4.84288488599398, 4.87912254898279, 5.0212393165514, 4.94666434649201, 
4.82862374963218, 4.99672941742763, 4.91631100831186, 5.06169030129395, 4.94444805229148, 
4.89002203289493, 4.90756203857889, 4.86887160621469, 4.74685935988966, 4.89086022479577, 
4.99798320415069, 4.95158899508649, 4.85967606739949, 5.04467197290689, 4.91931899257927, 
5.02122280373389, 4.93642346064497, 5.02859606632886, 4.89215186951552, 4.96034290845743, 
4.83530276640052, 4.95162128478437, 4.95637483516925, 4.99806244519172, 4.83296722196922, 
5.04717098547732, 4.93697582089791, 4.9643889705375, 4.95263854083563, 4.96083649446902, 
4.93340616291754, 4.98347644503747, 4.80738339411009, 4.89733246279153, 4.99429414474492, 
4.93211062567597, 4.81161349292948, 5.11181926924982, 4.91542267360367, 4.9230208117168, 
5.02143124424229, 4.94329929595529, 4.92331973395196, 5.04725909613123, 4.85478768823501, 
4.93125452048532, 5.04020950682286, 4.96461599301945, 4.88388107007345, 5.14842397757094, 
4.96175459384309, 4.99821358182042, 5.01782070971797, 4.98779916202219, 4.97024244477254, 
4.98601669707782, 4.77625134719598, 4.97230287275131, 4.99575826330943, 4.9574942225036, 
4.92306710764089, 5.17227220878438, 5.00986699819149, 5.12384194017821, 5.08164575517817, 
5.03196826308231, 5.08619355030336, 5.03662427686059, 4.92165258154249, 5.01338301249596, 
5.07365612375457, 5.03648069237), .Tsp = c(2006, 2015.83333333333, 12), class = "ts")), .Names = "x", row.names = c(NA, 
-119L), class = "data.frame"), d = 0, D = 1, seasonal = TRUE, ic = ("aic"), 
    stepwise = FALSE, approximation = FALSE, xreg = 1:119, allowdrift = TRUE, 
    parallel = TRUE)

Coefficients:
         ar1     ar2     ar3     sma1   1:119
      0.0453  0.1548  0.2341  -0.7624  0.0019
s.e.  0.0935  0.0932  0.0938   0.1245  0.0003

sigma^2 estimated as 0.001983:  log likelihood = 175.81,  aic = -339.61
>

**Comment by robjhyndman** [comment]
Now fixed in https://github.com/robjhyndman/forecast/commit/c7a79020390f39ccfd4f8a8e38486bee255efcf3
