### ISSUE TITLE
Cross-validation for nnetar

### ISSUE THREAD

**Issue by gabrielcaceres** [robjhyndman/forecast#262]
Reading your [working paper on CV](http://robjhyndman.com/working-papers/cv-time-series/) made me think about whether we should have a cross-validation function for `nnetar`. It might be useful since there are a number of parameters that need to be set which probably will vary depending on the specific dataset (particularly `size` and `decay` come to mind, but also possibly  `maxit`; I imagine not `p` and `P` since the embedded time series would change). 

This could also be useful for #241, in that if multiple models were already fit for parameter selection, we can use those to create future sample paths. Of course, if no CV was done before hand, new models may still have to be re-fitted anyway. 
But even so, I wonder if doing "proper" CV might give a better handle on model uncertainty than refitting a sample path created by a previous NN model. 

Thoughts?

**Comment by robjhyndman** [comment]
Yes, proper CV would be useful for nnetar, and also for ar models. There is an existing CV() function that works with lm class objects which does LOOCV for regression models. So CVar() might be a useful addition which would do CV (LOO and k-fold) for ar and nnetar models. Then a CVts() function could do time-series cross-validation based on a rolling origin approach.

**Comment by gabrielcaceres** [comment]
Hhmm it might actually be tricky to write an independent, generic function to do CV since one needs to create the design matrix with the embedded time series prior to fitting. We would need to be able to pass the information about which elements to include. The internals of  `nnetar` can be modified in a straightforward manner to account for this, but not so for `ar`. 

We could provide our own AR function and modify it accordingly. One really easy way would be using `nnetar` and the arguments `skip=TRUE` and `size=0` (i.e. no hidden layer and inputs are directly connected to the outputs), which would fit a linear model through OLS (as a motivating example, something like this is essentially how `nnet::multinom` does multinomial logistic regression). On the plus side this would automatically bring some additional functionality with the `model` and `xreg` arguments. On the downside, it'd lack some of the more formal machinery used in the base `ar` implementation, and could be more confusing to add another equivalent function into the mix...

**Comment by robjhyndman** [comment]
Good point. Let's leave ar for now.

**Comment by gabrielcaceres** [comment]
How about something like this as a first-draft for regular CV. It depends on #280 since it uses the `subset` argument. 

It needs to be cleaned up a bit of course, but it's functional (note that I'm not particularly attached to any variable names).

I noticed that when using `do.call` the fitted model for each fold is not printed correctly (prints lots of extra output). I commented those lines out and for now just called the function directly. I'll look into what that's about.

Give it a whirl and see what you think.

```
## Note arguments to pass must be named
CVar <- function(x, k=10, FUN="nnetar", cvtrace=FALSE, ...){
  nx <- length(x)
  ## n-folds at most equal number of points
  k <- min(k, nx)
  ## capture arguments to pass to FUN
  funargs <- list(...)
  funargs$x <- x
  ind <- 1:nx
  xshuff <- sample(nx)
  ## create folds
  fold <- suppressWarnings(split(xshuff, 1:k))
  ## xfit <- x  # out-of-sample for full series?
  cvacc <- matrix(NA_real_, nrow=k, ncol=7)
  out <- list()
  for (i in 1:k){
    out[[paste0("fold", i)]] <- list()
    testset <- fold[[i]]
    trainset <- ind[-testset]
    funargs$subset <- trainset
    ## trainmodel <- do.call(FUN, funargs)
    ## testmodel <- do.call(FUN, list(x=x, model=trainmodel, xreg=trainmodel$xreg))
    trainmodel <- nnetar(x, subset=trainset, ...)
    testmodel <- nnetar(x, model=trainmodel, xreg=trainmodel$xreg)
    testfit <- fitted(testmodel)
    acc<- accuracy(x, testfit, test=testset)
    cvacc[i, ] <- acc
    ##
    out[[paste0("fold", i)]]$model <- trainmodel
    out[[paste0("fold", i)]]$accuracy <- acc
    ## include full series?
    ## xfit[testset] <- testfit[testset]
    if (isTRUE(cvtrace)){
      cat("Fold", i, "\n")
      print(acc)
      cat("\n")
    }
  }
  out$k <- k
  out$fun <- FUN
  ## calculate mean acuracy accross all folds
  out$CVmean <- matrix(apply(cvacc, 2, FUN=mean, na.rm=TRUE), dimnames=list(colnames(acc), "Mean"))
  ## calculate accuracy sd accross all folds --- include?
  out$CVsd <- matrix(apply(cvacc, 2, FUN=sd, na.rm=TRUE), dimnames=list(colnames(acc), "SD"))
  ## what class to set? e.g.
  return(structure(out, class=c("CVar", FUN)))
}
print.CVar <- function(x, ...){
  ## Add info about series, function, and parameters
  ## Add note about any NA/NaN in folds?
  ##
  ## Print number of folds
  cat(x$k, "-fold cross-validation\n", sep="")
  ## Print mean & sd accuracy() results
  print(x$CVmean)
  print(x$CVsd)
  invisible(x)
}
```

Some examples:

```

modelcv <- CVar(oil)
print(modelcv)
print(modelcv$fold1)
print(modelcv$fold10)
print(modelcv$fold11) #Should be NULL

modelcv <- CVar(usconsumption[, 1], k=5, p=3, xreg=usconsumption[, 2])
print(modelcv)
print(modelcv$fold1)

modelcv <- CVar(lynx, k=5, lambda=0.15)
print(modelcv)
print(modelcv$fold1)

modelcv <- CVar(oil, k=length(oil))
print(modelcv)

modelcv <- CVar(oil, k=100)  #caps out at LOO
print(modelcv)
```

**Comment by robjhyndman** [comment]
Added this function in https://github.com/robjhyndman/forecast/commit/5e5651c7c5bf012481a2a105ca39e417376e1ce6
