### ISSUE TITLE
seasonalaxis() doesn't behave with frequency < 1

### ISSUE THREAD

**Issue by mitchelloharawild** [robjhyndman/forecast#264]
```R
Acf(uspop)
```
Will give far too many axis ticks. A possible solution is to change the frequency==1 section to be frequency<=1, what do you think?

(And as in not behaving, I don't think the extra tick-marks are worthwhile.)

**Comment by robjhyndman** [comment]
Fixed in https://github.com/robjhyndman/forecast/commit/8334ad0e358595fcab8bee04aa8f6897d967d55d
