### ISSUE TITLE
Improved method for selecting seasonal differencing

### ISSUE THREAD

**Issue by robjhyndman** [robjhyndman/forecast#272]
nsdiffs often chooses D=0 when a visual inspection suggests D=1. I think this is due to the null hypothesis used in the OCSB test. Is there a better way?

**Comment by robjhyndman** [comment]
Add HEGY test to nsdiffs using uroot::hegy.test

**Comment by mitchelloharawild** [comment]
Support for hegy.test is provided in 7a9de0ed08d005e5098781734b59515bd0d8a867
