### ISSUE TITLE
Add gglagplot

### ISSUE THREAD

**Issue by robjhyndman** [robjhyndman/forecast#286]
ggplot2 version of lag.plot.

**Comment by mitchelloharawild** [comment]
For this to function, we should first add support for: autoplot.ts(x, y).

Text size scaling to smaller view windows, and ending the lines early (plot type "b") are difficult to implement in ggplot2... may take some time to implement this functionality.

Example:
```R
plot(mdeaths, fdeaths)
```

**Comment by mitchelloharawild** [comment]
Currently it looks like this:
```R
gglagplot(mdeaths)
```
![lagplot1](https://cloud.githubusercontent.com/assets/16127127/14735629/688e031a-08b5-11e6-9db5-a0e3f7cb7f58.png)

```R
gglagplot(lungDeaths, lags=2)
```
![lagplot2](https://cloud.githubusercontent.com/assets/16127127/14735648/9850f5d0-08b5-11e6-84e7-ee38a6cd93c0.png)

The aspect ratio (coord_fixed) breaks when introducing free axis facets

**Comment by mitchelloharawild** [comment]
Here's a quick progress update on this function, just a few more tweaks for parity with lag.plot()
Key differences are, colour has been added (removing text labels as the default option), and the layout has been made consistent with lag.plot()

Using colour, I have added options to highlight seasonal lag movements within the year, and movements across all observations.

![rplot13](https://cloud.githubusercontent.com/assets/16127127/15136851/8a85a24a-16c8-11e6-9259-a8e3811dee95.png)
![rplot14](https://cloud.githubusercontent.com/assets/16127127/15136854/90dfb928-16c8-11e6-8ab6-714e3d32e527.png)
![rplot15](https://cloud.githubusercontent.com/assets/16127127/15136859/930e4aca-16c8-11e6-92dd-d7b4f9ee3215.png)

**Comment by mitchelloharawild** [comment]
Added in #309
