### ISSUE TITLE
Rd for auto.arima

### ISSUE THREAD

**Issue by dashaub** [robjhyndman/forecast#290]
Small item that isn't worth a pull request, so I opened this issue instead: the Rd file for `auto.arima` links to the `arima` function in the details/value sections. It would perhaps be better to link to `Arima` here since the object returned from `auto.arima` is an `Arima` object that has list items such as `bic`, `aicc`, drift, etc that aren't in objects returned from `stats::arima`. The "See Also" section might also benefit from a link to `Arima`.

**Comment by robjhyndman** [comment]
Thanks. Now fixed.
