### ISSUE TITLE
More reliable results from auto.arima for short series

### ISSUE THREAD

**Issue by robjhyndman** [robjhyndman/forecast#291]
Example:

```
orig <- ts(c(-0.001730532,-0.035105068,-0.094437577,-0.149320148,-0.146847960,-0.129048208))
auto.arima(orig)
```

Need to restrict size of model considered so that number of parameters is much less than number of observations.

**Comment by harmbuisman** [comment]
Hi Rob,

The following also produces unexpected flat 0 forecast for auto.arima

library(forecast) #This is forecast 7.1 
forecast(auto.arima(c(134019,139712,222190,213367)))

**Comment by robjhyndman** [comment]
First issue fixed in https://github.com/robjhyndman/forecast/commit/73ffc9a38362936fca02a6a884087cddcd1434a8

Second issue is not that bad given size of prediction intervals. In any case, it is hard to see how to find a general solution for such edge cases. Add 200 to all values and a different model is selected.
