### ISSUE TITLE
ggtsdisplay ignores themes

### ISSUE THREAD

**Issue by robjhyndman** [robjhyndman/forecast#297]

**Comment by mitchelloharawild** [comment]
This is because of how the grid panels are arranged. I don't think this is
possible without significant ggplot tweaks.

**Comment by mitchelloharawild** [comment]
One way that I can think of implementing this is having a theme argument.

Essentially the output for these multi-panel objects are fixed as printed objects, some can (and should) be converted to facets, like autoplot.mforecast(), although multi-panel objects of different sizes cannot be faceted in a way that creates the same layout.

Example usage would be:
ggtsdisplay(WWWusage, theme=theme_bw())

**Comment by robjhyndman** [comment]
Adding a theme argument is ok I think.

**Comment by mitchelloharawild** [comment]
Added in #299
