### ISSUE TITLE
Croston method issues with Forecast 7.1 version

### ISSUE THREAD

**Issue by thotaanil** [robjhyndman/forecast#300]
Hi,

We used to run croston method forecast with older versions of Forecast packages until 6.2. Recently, I have updated my forecast package with 7.1 version, then the problem started for croston method.

I am getting the below error. Please check once.
 
**Function Model_output: Error in ts(object$upper[1:h, ], start = tspf[1], frequency = tspf[3]): 'ts' object must have one or more observations**

**Comment by robjhyndman** [comment]
Please provide a reproducible example of the error.

**Comment by thotaanil** [comment]
library(forecast)

vol_data <-read.csv("D:\\My Stuff\\R Code for Machine Learning-RAJU\\Inter Ikea\\Input Files\\Process2 Data.csv")

per_te_Data=10
te_n<-round(nrow(vol_data)*(per_te_Data/100))
f_Period=10
vol_data$Date=as.Date(paste(vol_data$Date), format ="%m/%d/%Y")

## Splitting the data into train and test for evaluating best model
tr_vol_data = vol_data[1:(nrow(vol_data)-(te_n+f_Period)),] 
te_vol_data = vol_data[(nrow(vol_data)-(te_n-1+f_Period)):(nrow(vol_data)-f_Period),] 

tr_Wkdays_ts = ts(tr_vol_data[,2],frequency=7)  #input ts for model using trianing data

Z=as.numeric(nrow(tr_vol_data))
tr_pred_data_wk=vol_data[(Z+1):nrow(vol_data),]

      fit = suppressWarnings(croston(tr_Wkdays_ts,h=nrow(tr_pred_data_wk)))
      Forecast_output=forecast(fit,h=nrow(tr_pred_data_wk))
      
This is the code, where I am getting an Error with latest version of forecast package

**Comment by robjhyndman** [comment]
This is not reproducible because you haven't provided the data. Please provide a reproducible example.

**Comment by alahoty** [comment]
Hi thotaanil, 
I am not an expert, I think I got you query (if it is still open), with due respect to **robjhyndman** , I would like to answer this query
So, the problem you are facing is due to up-gradation of package "forecast"
Earlier, the croston model works like:
fit <- croston(x, h = horizon) and to get the forecast plot
forecast_croston <- forecast(fit, h = horizon)
plot(forecast_croston)
After up-gradation,
fit <- croston(x, h = horizon)
plot(fit)
There is no need for the additional step now ( Thanks to **robjhyndman** here)
This worked for me as I am also facing the same error.
This is purely based on my experience, I hope I am clear.

**Comment by robjhyndman** [comment]
As far as I can recall, croston() has not changed in several years.

**Comment by alahoty** [comment]
Oh!
But, I faced the similar error when I was playing around with croston() ( only after up-gradation of the package, earlier it was working fine)
It worked for me that way, so I thought to help (if that resolves the issue)

Attaching a reproducible example below:
####### Example #########
require(forecast)
require(Mcomp)
M3[[2000]]
# Croston Model
croston.model <- croston(M3[[2000]]$x,h = 18)
croston.forecast <- forecast(croston.model, h = 18)
plot(croston.model)

#ets Model
ets.model <- ets(M3[[2000]]$x)
ets.forecast <- forecast(ets.model, h = 18)
plot(ets.model)
plot(ets.forecast)

**Comment by robjhyndman** [comment]
croston() returns a forecast object, not a model. ets() returns a model. To get the forecasts from an ets object, you need to use forecast(). 

The error was introduced due to a change in the forecast.forecast() function, not the croston() function. I'll fix it in a future version.
