### ISSUE TITLE
AIC calculations off when using lamda = 0 for ets, auto.arima functions

### ISSUE THREAD

**Issue by SinghB** [robjhyndman/forecast#301]
Taking 'gas' dataset as an example, I was trying out a log transformation by using lamda = 0
I was trying to do comparison for various error measures and information criterion and noticed that the ic values are all way lower when using lambda.
Note that I've made a call to forecast(ets(gas, lambda=0), lambda = 0)
Have to use it twice to allow forecast function to back transform.
While the comparison in terms of fitted and forecast values for the above call against forecast(ets(gas)) is similar, the ic values are very different.
My guess is the ic values are preserved from the time series was transformed to build the model.
However, I was expecting forecast function to back transform things, including the residuals and the calculation based on residuals like ic. But that didn't happen.
If I'm missing some basic concepts, please feel free to close the issue.

**Comment by dashaub** [comment]
`forecast` does backtransform `lambda` values automatically:
```
e <- ets(gas, lambda = 0.5)
# View the lambda
e$lambda # 0.5
# Are the point forecasts the same?
forecast(e)$mean == forecast(e, lambda = 0.5)$mean # All TRUE
# Are the residuals the same?
residuals(forecast(e)) == residuals(forecast(e, lambda = 0.5)) # All TRUE
```

Information criteria can't usefully be compared between models with a transformed series (Think about why you can't compare the IC from an ARIMA and an ARMA model).
