### ISSUE TITLE
Add geom_ts

### ISSUE THREAD

**Issue by robjhyndman** [robjhyndman/forecast#305]
Equivalent to geom_line(aes(x=time(y), y=y), ...)

**Comment by mitchelloharawild** [comment]
I'm not convinced that this is the way to implement this, in terms of how
the grammar is structured.
I think this type of functionality is most appropriate as a autoplot, as in
autoplot.ts()?

I think what you're thinking of is a fortify method for time series
objects, so you can do:
ggplot(aes(x=time, y=[seriesname]), data=mytsobject) + geom_line()

What use-case do you envision?

**Comment by robjhyndman** [comment]
I was thinking of something like this:
```
autoplot.ts(y) + geom_ts(x)
```
as a quick way of adding a new time series to an existing plot without actually constructing the multiple time series object. I realise that it is possible to do it like this:
```
tmp <- cbind(y,x)
autoplot(tmp)
```
but that seems more awkward. But I'm happy to leave it if you don't like it.

**Comment by mitchelloharawild** [comment]
I think the approach that is consistent with the grammar would be to
maintain use of geom_line(), but define methods for ts objects.
Not sure if possible, but I think it would be better to do:

autoplot.ts(y) + geom_line(data=x)

Of course geom_line() is just one example, and it would work with any
geom that requires x (time) and y (observations). Such as
geom_point().

**Comment by robjhyndman** [comment]
Yes, that makes sense. But how to convince geom_line (or any other geom) to handle ts objects seamlessly?

**Comment by mitchelloharawild** [comment]
So how I'm thinking of achieving this is using the fortify.ts() method to
change the aesthetic mappings to provide defaults (x=time, y=observations).

Fortify methods are called on all data objects provided to ggplot, so when
it is given a ts object, it looks to fortify.ts() to convert it into a
data.frame (all ggplot data is stored as a data.frame).
Ideally, there is support for fortify methods to provide default
aesthetics, but I have a suspicion that this is not the case. So to
implement this, the mapping variable in the parent function will need to be
changed.
