### ISSUE TITLE
auto.arima()

### ISSUE THREAD

**Issue by lbertolotti** [robjhyndman/forecast#330]
I think the auto.arima function is bugged, the D parameter doesn't change the result:

```
library(forecast)
auto.arima(WWWusage, D=0)
auto.arima(WWWusage, D=1)
auto.arima(WWWusage, D=2)

```

All give the same ar and ma coefficients.

**Comment by gabrielcaceres** [comment]
Capital D is for seasonal differencing, but there's nothing to difference if the series is non-seasonal. Try it with lower case d, or by giving the data a seasonal period first.

**Comment by lbertolotti** [comment]
```
library(forecast)
t=1:length(WWWusage)
auto.arima(WWWusage*sin(5*t), D=0)
auto.arima(WWWusage*sin(5*t), D=1)
auto.arima(WWWusage*sin(5*t), D=2)

```
What about this?

**Comment by robjhyndman** [comment]
As you've already been told, D is for seasonal differencing. WWWusage is not seasonal.

**Comment by lbertolotti** [comment]
So you are saying sin(5*t) is not a seasonal component?

**Comment by gabrielcaceres** [comment]
It doesn't matter if the data display periodicity; if the time series doesn't have an explicitly defined seasonal period the functions won't add a seasonal component.

Try this (with an arbitrarily picked frequency):

```
x <- ts(WWWusage, frequency = 7)
auto.arima(x, D=0)
auto.arima(x, D=1)
auto.arima(x, D=2)
```

**Comment by lbertolotti** [comment]
Ok, thanks. But please add this as a note on the description for auto.arima(). I thought this was done automatically too.
