### ISSUE TITLE
geom_forecast() bug

### ISSUE THREAD

**Issue by robjhyndman** [robjhyndman/forecast#337]
Reported at https://stats.stackexchange.com/questions/217909/how-to-use-new-function-geom-forecast-in-forecast-v7

MRE:

```
library(forecast)
library(ggplot2)
fit.nnetar<-nnetar(mdeaths,size = 4)
fc.nnetar<-forecast(fit.nnetar,h=20)
autoplot(mdeaths)+geom_forecast(fc.nnetar) 
```

**Comment by mitchelloharawild** [comment]
I've identified a few problems with geom_forecast() and other methods when solving this one.

as.data.frame.forecast() treats forecasts without confidence intervals differently than forecasts with intervals. Not sure if this should be the case, I think it is done this way for display purposes, and not for data manipulation purposes. This is used by print.forecast() for example.

I've set fortify.forecast() to not use as.data.frame.forecast() whenever there are no confidence intervals, and it seems to work ok.

Also regarding the SO post, autoplot(fc.nnetar) would satisfy their use-case.
