### ISSUE TITLE
Different auto.ARIMA result when using package 7.1 instead of 5.9

### ISSUE THREAD

**Issue by kristkova** [robjhyndman/forecast#339]
Dear Rob,

I am using Package Forecast, function auto.arima with the following command:
ARIMA2_dummy <- auto.arima(tsProd2, xreg=Production2$Dummy11, approximation = FALSE)

My problem is that when I run this command on different R package releases, I get different ARIMA specifications (see below, here the seasonal lag is different).

Could you please explain why is this happening and which version would you recommend using? We are interested in forecasting the values and they differ quite a lot because of this.

Thank you in advance for your response.
Best regards,
Zuzana

################ARIMA with Dummy - Output version (Forescast 5.9)##################

#Series: tsProd2 
#ARIMA(5,0,2)(2,0,0)[36] with non-zero mean 

#Coefficients:
#  ar1     ar2    ar3     ar4    ar5    ma1    ma2   sar1   sar2  intercept  Production2$Dummy11
#0.249  -0.619  0.224  -0.024  0.263  0.294  0.585  0.282  0.395      0.862               -0.250
#s.e.  0.126   0.198  0.138   0.099  0.070  0.113  0.201  0.063  0.069      0.053                0.136

#sigma^2 estimated as 0.036:  log likelihood=61
#AIC=-98   AICc=-96.9   BIC=-53.68

###############ARIMA with Dummy - (Forecast 7.1)######################

#Series: tsProd2_Wil 
#ARIMA(5,0,2)(1,0,0)[36] with non-zero mean 

#Coefficients:
#  ar1     ar2    ar3    ar4    ar5    ma1    ma2   sar1  intercept  Production2_Wil$Dummy11
#0.369  -0.606  0.345  0.031  0.280  0.364  0.658  0.335      0.852                   -0.166
#s.e.  0.117   0.148  0.139  0.088  0.072  0.097  0.137  0.080      0.058                    0.081

#sigma^2 estimated as 0.0433:  log likelihood=46.87
#AIC=-71.73   AICc=-70.81   BIC=-31.1

**Comment by robjhyndman** [comment]
The algorithms have been improved over time. Always use the most recent version.
