### ISSUE TITLE
accept index positions for subset.ts

### ISSUE THREAD

**Issue by dashaub** [robjhyndman/forecast#343]
It would be nice if this would work:

```
subset.ts(AirPassengers, subset = 1:24)
```

The main use case I see for this is contiguous subsetting. This would increase consistence with base R subsetting.

Finally, I can understand why you are preventing vector recycling in this case to shield the user, but it is also inconsistent with how R allows vector recycling in subsetting operations.

```
subset.ts(AirPassengers, subset = TRUE)
subset.ts(AirPassengers, subset = c(TRUE, FALSE))
```

Thoughts on allowing at least index subsetting? The documentation could use some expansion with more details to make more clear the type of syntax allow and disallowed.

**Comment by dashaub** [comment]
Looking through the open PRs, I see this is very similar in intention to #312 and #283. Since preserving tsp only makes sense with contiguous slices (or monthly, quarterly, yearly slices that remove seasonality), really Gabriel and I are after the same thing here a subsetting function for contiguous slices that preserves tsp.

**Comment by robjhyndman** [comment]
Resolved in https://github.com/robjhyndman/forecast/commit/9302c5c71451cbce44c26bc2b1b6e8de0c262321
