### ISSUE TITLE
ETS(A, Ad, N) states do not match additive damped trend equations in https://www.otexts.org/fpp/7/4

### ISSUE THREAD

**Issue by josepm** [robjhyndman/forecast#344]
Using the aust time series:
z = ets(y = aust[1:length(aust)], model = "AAN", damped = TRUE, alpha = 0.8,  beta = 0.2, phi = 0.8) 
z$states:
                  l                      b
 0 42.45355    -4.77767830
 1 41.10825    -3.20293187
 2 26.94266    -5.46315584
 3 30.37691    -2.41933121
 4 35.55126    -0.15801228

but if I implement the recursion in https://www.otexts.org/fpp/7/4, I get

	           y	       level	       trend
0		          42.4536	   -4.7777
1	41.72746	  41.1082	   -3.3268
2	24.04185	  26.9228	   -4.9662
3	32.32810	  30.4525	   -2.4725
4	37.32871	  35.5579	   -0.5613

**Comment by robjhyndman** [comment]
Please provide a minimal reproducible example. `aust` is not provided here and is not defined in the page you link to.

**Comment by josepm** [comment]
Sorry about that. 
The aust series comes with the forecast package. Here are its values:
y = [41.72746, 24.04185, 32.32810, 37.32871, 46.21315, 29.34633, 36.48291, 42.97772, 48.90152, 31.18022, 37.71788, 40.42021, 51.20686, 31.88723, 40.97826, 43.77249, 55.55857, 33.85092, 42.07638, 45.64229, 59.76678, 35.19188, 44.31974, 47.91374]

**Comment by robjhyndman** [comment]
No, it is not from the forecast package. It is a subset of the `austourists` data from the fpp package. The following code reproduces the first few states:

```
library(fpp)
aust <- window(austourists, start=2005)

alpha <- 0.8
beta <- 0.2
phi <- 0.8

l <- b <- numeric(6)
l[1] <- z$states[1,1]
b[1] <- z$states[1,2]
for(i in 2:6)
{
  l[i] <- alpha * aust[i-1] + (1-alpha)*(l[i-1]+phi*b[i-1])
  b[i] <- beta/alpha*(l[i]-l[i-1]) + (1-beta/alpha)*phi*b[i-1]
}

cbind(l,b)

z <- ets(aust, model = "AAN", damped = TRUE, 
         alpha = alpha, beta = beta, phi = phi) 
z$states[1:6,]
```

The two match exactly, as you would expect.
