### ISSUE TITLE
Slight mistake in "plot.forecast" documentation

### ISSUE THREAD

**Issue by pascaloettli** [robjhyndman/forecast#345]
Hello,

In the documentation of the `plot.forecast` function (v.7.1 and v.7.2) , we find:

    pi.col	If shade=FALSE and plot.conf=TRUE, the prediction intervals are plotted in this colour.
    pi.lty	If shade=FALSE and plot.conf=TRUE, the prediction intervals are plotted using this line type.

However, if we try:

    wine.fit <- hw(wineind,h=48)
    plot(wine.fit, shade=FALSE, plot.conf=TRUE)

We get this error:

    Error in plot.forecast(wine.fit, shade = FALSE, plot.conf = TRUE) : 
      argument 2 matches multiple formal arguments

Because the correct argument is `shaded`, not `shade`:

    shaded	Logical flag indicating whether prediction intervals should be shaded (TRUE) or lines (FALSE)

Regards

**Comment by robjhyndman** [comment]
Thanks. Fixed in https://github.com/robjhyndman/forecast/commit/453ef88916dd47b3b7d6fbb42e4d5f181026f4cd
