### ISSUE TITLE
fourier K error in forecast 7.1 with daily data

### ISSUE THREAD

**Issue by tcheng2014** [robjhyndman/forecast#350]
In forecast 7.1, when working with msts  and fourier functions on daily data (ts.frequency=7) and set seasonal period to be yearly (seasonal.periods=c(365.25)), an error is given when set K=c(4) saying 'K must be not be greater than period/2'.  Since the period is 365.25, K=4 is much smaller than 365.25/2. I believe this is a bug since no error was reported until forecast 7.0.

require(forecast);require(lubridate);

Mini<-data.frame(Date=as.Date('2016-01-01')+days(0:99),Number=runif(100, 1, 1000))

y1 <- msts(Mini$Number,seasonal.periods=c(365.25),ts.frequency=7,start=c(2016,1,1))
z1<- fourier(y1, K=c(4))

**Comment by mitchelloharawild** [comment]
Hi, please provide a minimal reproducible example.

**Comment by tcheng2014** [comment]
A minimum reproducible  example:

require(forecast);require(lubridate);

Mini<-data.frame(Date=as.Date('2016-01-01')+days(0:99),Number=runif(100, 1, 1000))

y1 <- msts(Mini$Number,seasonal.periods=c(365.25),ts.frequency=7,start=c(2016,1,1))
z1<- fourier(y1, K=c(4))

Run the above code and I get

Error in ...fourier(x, K, 1:length(x)) : 
  K must be not be greater than period/2

**Comment by robjhyndman** [comment]
You have two periods, 7 and 365.25. If you only pass one value of `K`, it applies to both, and `K=4` is too large for period 7. In addition, you set `ts.frequency` to 7 which is not one of the `seasonal.periods`.

You need to pass two values of K and use two seasonal periods:

```
y1 <- msts(Mini$Number,seasonal.periods=c(365.25, 7),ts.frequency=7,start=c(2016,1,1))
z1<- fourier(y1, K=c(4,1))

```
