### ISSUE TITLE
auto.arima speed up

### ISSUE THREAD

**Issue by robjhyndman** [robjhyndman/forecast#353]
With long series having period greater than 10, consider using only last 6 years (or so) of data  when selecting orders

**Comment by dashaub** [comment]
Would this be enabled by default, set with an additional argument (e.g. `truncate= TRUE`), or be impossible to opt out? For what it's worth,  high-frequency (not `ts` frequency) daily/hourly/minute data seem most likely to generate these long series, so `ts` frequency seems unrelated to series length.

**Comment by robjhyndman** [comment]
No, it would not be enabled by default, at least until it is very thoroughly tested. So it would be an opt-in if you want to try it. The slow cases seem to be long time series AND high seasonal period time series. The combination is deadly. I thought I'd start experimenting with what effect truncation has on order selection and speed. If it looks like a useful strategy, I'll add an option to allow it in auto.arima().

**Comment by robjhyndman** [comment]
Resolved for now by adding optional truncate argument to auto.arima().
