### ISSUE TITLE
issue in tslm() after last package update

### ISSUE THREAD

**Issue by andreaspapayiannis** [robjhyndman/forecast#354]
I believe there is a small bug in tslm() after the last update of the forecast package. The problem arises once using the '.' shortcut symbol when referring to the entire data frame. Please have a look at the following examples. 

mydf <- data.frame( y=ts( rnorm(14) ,freq=7),  x=1:14,  z=factor(rep(1:7,2)))

lm(y ~ . , data=mydf) # works fine

tslm(y ~ . , data=mydf) # does not work
tslm(y ~ . - trend - season, data=mydf) # does not work
Both report  " Error in terms.formula(formula) : '.' in formula and no 'data' argument "

Thank you

**Comment by mitchelloharawild** [comment]
Fixed in #355.
By default, trend and season are not included, but can be added like so:
```R
tslm(y ~ . + trend + season, data=mydf)
```

**Comment by andreaspapayiannis** [comment]
Great thanks. Does one normally wait for a new package release in order to obtain the edited code - or is there a simpler way to do this? thanks

**Comment by mitchelloharawild** [comment]
To install the latest version from github, you can use the install_github() function from the devtools package.
```R
install.packages("devtools")
devtools::install_github("robjhyndman/forecast")
```

However Rob needs to accept the PR before it becomes available on this repo, so if you want to experiment with it now, you can install from my fork: (however the wait shouldn't be long)
```R
devtools::install_github("mitchelloharawild/forecast")
```

**Comment by andreaspapayiannis** [comment]
Great thanks.
