### ISSUE TITLE
 Warning at forecast.Arima !!!!

### ISSUE THREAD

**Issue by spoulopo** [robjhyndman/forecast#356]
Hi Rob,
I was using arima to fit a regression model with arima errors by using as xreg a train dataset and forecast to predict a new time series data by using for xregnew a test dataset. Here is the code I am using:
[test_data.xlsx](https://github.com/robjhyndman/forecast/files/449284/test_data.xlsx)
[train_data.xlsx](https://github.com/robjhyndman/forecast/files/449285/train_data.xlsx)
```
library(xlsx)
library(forecast)

train_data<-read.xlsx("train_data.xlsx",sheetName = "train_data")
test_data<-read.xlsx("test_data.xlsx",sheetName = "test_data")
xVars<-setdiff(names(train_data),"y")
trainARIMA<-arima(x = train_data[,"y"],xreg=train_data[,xVars],
                  order =c(2,0,2), include.mean = TRUE)
forecastValues <- forecast.Arima( trainARIMA,xreg=test_data[,xVars])$mean
```
And I am getting this warning message:

_**Warning message:
In cbind(intercept = rep(1, n), xreg) :
  number of rows of result is not a multiple of vector length (arg 2)**_

The two datasets (train_data and test_data) have the same number of columns. 
Have you any explanation about this?

**Comment by robjhyndman** [comment]
Use `Arima()`, not `arima()`, to do the model estimation.

**Comment by spoulopo** [comment]
Thank you for your help..
