### ISSUE TITLE
forecast.bats error @ row 80

### ISSUE THREAD

**Issue by FransAndersen** [robjhyndman/forecast#358]
After updating to the latest version of the forecasting package on github (due to anouther bug) i get the following error at row 80 at forecast.bats:

y <- ts(c(object$y, 0), start = start.time, frequency = ts.frequency)
Error in try.xts(0) : 
  Error in as.xts.double(x, ..., .RECLASS = TRUE) :   order.by must be either 'names()' or otherwise specified

The error is more precise comming from c(object$y, 0)

--------------------------------------------------------------------------------
SAMPLE CODE
--------------------------------------------------------------------------------
variableValues <- c(33736.25,33712.5,38087.75,34594.75,30841.25,36909.75,37604,35536,37919.25,38211,39905.75,38832.75,36678.75,37647.75,41619.5,39772,34867.25,38081.75,37346.5,41084,40469,40494.25,45103.5,44942.25,49926.5,49098.25,55861.75,49798.5,60079.5,54494.25,52755.5,54108.5,51919.5,58384,59443.75,53449.75,61783.5,56632.25,60741.25,53469.25,58679.25,56215.5,60113.75,55327.25,47813.5,56163.75,55138.25,42860.5,53791.75,58305.75,57092.25,65094,58048.5,62106.75,70625.75,58003.75,57788.25,48779,37041.5,31290.5,29668.5,26596.25,29381,28410,27741.25,34613.25,38353.25,38667.75,40339.25,41320,40927.75,45773.5,44696.75,40971.5,50719.75,46328,38762.75,42482.5,43731.25,44469.75,47563.5,49267.5,51317.5,49352,48782.5,50155,58700.25,47921.25,51833.5,56210.75,52743.5,52627.5,50518.75,45608.75,45609.25,40429.5,45020.25,46274.5,48017,38877.5,44003.75,35805.5,41224.25,40429.75,41069.75,45422,42740.25,39639.75,44829.5,41062.75,38255.5,38981,38435.5,36320,40649.25,38103.5,36962,41676,36727.25,12062.25)
dates <- c("2003-12-28","2004-02-01","2004-02-29","2004-03-28","2004-04-25","2004-05-30","2004-06-27","2004-08-01","2004-08-29","2004-09-26","2004-10-31","2004-11-28","2004-12-26","2005-01-30","2005-02-27","2005-03-27","2005-05-01","2005-05-29","2005-06-26","2005-07-31","2005-08-28","2005-09-25","2005-10-30","2005-11-27","2006-01-01","2006-01-29","2006-02-26","2006-03-26","2006-04-30","2006-05-28","2006-06-25","2006-07-30","2006-08-27","2006-10-01","2006-10-29","2006-11-26","2006-12-31","2007-01-28","2007-02-25","2007-04-01","2007-04-29","2007-05-27","2007-07-01","2007-07-29","2007-08-26","2007-09-30","2007-10-28","2007-11-25","2007-12-30","2008-01-27","2008-02-24","2008-03-30","2008-04-27","2008-06-01","2008-06-29","2008-07-27","2008-08-31","2008-09-28","2008-10-26","2008-11-30","2008-12-28","2009-02-01","2009-03-01","2009-03-29","2009-04-26","2009-05-31","2009-06-28","2009-07-26","2009-08-30","2009-09-27","2009-11-01","2009-11-29","2009-12-27","2010-01-31","2010-02-28","2010-03-28","2010-04-25","2010-05-30","2010-06-27","2010-08-01","2010-08-29","2010-09-26","2010-10-31","2010-11-28","2010-12-26","2011-01-30","2011-02-27","2011-03-27","2011-05-01","2011-05-29","2011-06-26","2011-07-31","2011-08-28","2011-09-25","2011-10-30","2011-11-27","2012-01-01","2012-01-29","2012-02-26","2012-04-01","2012-04-29","2012-05-27","2012-07-01","2012-07-29","2012-08-26","2012-09-30","2012-10-28","2012-11-25","2012-12-30","2013-01-27","2013-02-24","2013-03-31","2013-04-28","2013-05-26","2013-06-30","2013-07-28","2013-09-01","2013-09-29","2013-10-27","2013-12-01")
rdates <- as.Date(dates)
number_of_forecasts <- 10
confidence_interval <- c(50,75,95);
TBATSseries<-xts(variableValues, rdates)
tbatsfit<-tbats(TBATSseries, use.box.cox = NULL, use.trend = NULL, use.damped.trend = NULL, seasonal.periods = NULL, use.parallel = TRUE)
TBATSforecast<-forecast(tbatsfit, h=number_of_forecasts, level=confidence_interval)

**Comment by dashaub** [comment]
`tbats()`--and the functions in the "forecast" package in general--expects the input timeseries to be `ts`, `mtsts`, or `numeric`.

**Comment by robjhyndman** [comment]
Just use 
```
TBATSseries <- as.ts(xts(variableValues, rdates))
```
and it should work ok. (Use the latest version on github as there was a problem with tbats handling ts objects having frequency less than 1.)
