### ISSUE TITLE
myarima.sim: innovatinos & BoxCox 

### ISSUE THREAD

**Issue by gabrielcaceres** [robjhyndman/forecast#363]
Quick question regarding the innovations for simulations when the data was fitted after a Box-Cox transform.  

In `myarima.sim`, there is an argument `x` to have the simulation be conditional on those values, and an argument `e` for the innovations. The `simulate` methods that call `myarima.sim` transform the data if a Box-Cox transform was used in the original fit, but the innovations used remain in the same scale as the untransformed data. Should the innovations be transformed in the same way as the data prior to using them?

**Comment by robjhyndman** [comment]
Innovations stay on transformed scale

**Comment by gabrielcaceres** [comment]
Ah, I see what you mean and noticed where my confusion stemmed from after reading through the `Arima` code. When a transformation is requested, the code does:

`data` &rarr; `BoxCox(data)` &rarr; `fit model` &rarr; `get model fitted values & residuals` &rarr; `invBoxCox(fitted values)`

So when a Box-Cox transform is used the residuals remain in the transformed scale and `data - (new) fitted values` &ne; `residuals(model)`, correct? 

This then raises a question regarding what `nnetar` is doing (and for context, my confusion arose while tweaking code for #308 ). 

In `nnetar` we are doing:

`data` &rarr; `BoxCox(data)` &rarr; `fit model` &rarr; `get fitted values` &rarr; `invBoxCox(fitted values)` &rarr; `residuals = data - (new) fitted values`

So: 
- Which residuals would be most appropriate to give as part of the model output?

- If the residuals we are currently using are fine, then in that case they _should_ be transformed first to be in the correct scale to be used as innovations, right?

**Comment by robjhyndman** [comment]
There are two different kinds of errors here. The residuals should be on the transformed scale, as in Arima(). But sometimes it is useful to compute errors on the same scale as the data, as is done in nnetar. For simulation purposes, you need the residuals on the transformed scale. For forecast accuracy purposes, you need the errors calculated as the difference between data and fitted values. 

It is probably better to be consistent with Arima() and store residuals on the transformed scale. But then we will need to check if this change will cause problems elsewhere. Note that you can't transform the residuals themselves.

**Comment by gabrielcaceres** [comment]
OK, thanks for the clarification! I made the change on #308 to get the correct residuals for simulations, but haven't changed the stored `nnetar` residuals in case it could cause issues.
