### ISSUE TITLE
Issue with installation 

### ISSUE THREAD

**Issue by dbalanzategui** [robjhyndman/forecast#365]
I am trying to install forecast but I am not having much success. The following is the report I am facing. What do you suggest?
Software: RStudio Version 0.99.903

First attempt:
> install.packages("forecast")

  There is a binary version available but the source version is later:
         binary source needs_compilation
forecast    7.1    7.2              TRUE

Do you want to install from sources the package which needs compilation?
y/n: n
trying URL 'http://cran.cnr.berkeley.edu/bin/macosx/mavericks/contrib/3.3/forecast_7.1.tgz'
Warning in install.packages :
  cannot open URL 'http://cran.cnr.berkeley.edu/bin/macosx/mavericks/contrib/3.3/forecast_7.1.tgz': HTTP status was '404 Not Found'
Error in download.file(url, destfile, method, mode = "wb", ...) : 
  cannot open URL 'http://cran.cnr.berkeley.edu/bin/macosx/mavericks/contrib/3.3/forecast_7.1.tgz'
Warning in install.packages :
  download of package ‘forecast’ failed

Second attempt:
> install.packages("forecast")

  There is a binary version available but the source version is later:
         binary source needs_compilation
forecast    7.1    7.2              TRUE

Do you want to install from sources the package which needs compilation?
y/n: y
installing the source package ‘forecast’

trying URL 'http://cran.cnr.berkeley.edu/src/contrib/forecast_7.2.tar.gz'
Content type 'application/x-gzip' length 201592 bytes (196 KB)
==================================================
downloaded 196 KB

* installing *source* package ‘forecast’ ...
** package ‘forecast’ successfully unpacked and MD5 sums checked
** libs
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
ERROR: compilation failed for package ‘forecast’
* removing ‘/Library/Frameworks/R.framework/Versions/3.3/Resources/library/forecast’
Warning in install.packages :
  installation of package ‘forecast’ had non-zero exit status

The downloaded source packages are in
	‘/private/var/folders/v_/m8jldl7x29d_kv1l7mm1vdyr0000gn/T/RtmpieR2MJ/downloaded_packages’
> require(forecast)
Loading required package: forecast
Warning message:
In library(package, lib.loc = lib.loc, character.only = TRUE, logical.return = TRUE,  :
  there is no package called ‘forecast’

**Comment by robjhyndman** [comment]
Wait until the new 7.2 binary is available and then you won't have to compile it yourself.

**Comment by dbalanzategui** [comment]
Thanks for the speedy reply. I got it working by compiling in R. R studio was able to find the packages needed to run dendrometeR, job done!
