### ISSUE TITLE
model residuals

### ISSUE THREAD

**Issue by gabrielcaceres** [robjhyndman/forecast#368]
Thinking about the discussion from #363, I was wondering if it might be useful to implement a `residuals.XXX` method, with a `type` argument like is done for [`residuals.glm`](https://stat.ethz.ch/R-manual/R-devel/library/stats/html/glm.summaries.html).

That could make it clearer what residuals are being used and also make them easier to access.

**Comment by robjhyndman** [comment]
That should be useful. I imagine there would be two types: innovation residuals and fitted residuals. Not sure if they are the best names though.

**Comment by gabrielcaceres** [comment]
What about something like "innovation" and "response"? The latter would be consistent with the usage in the `glm` documentation.

I could also see a "working" option (again similarly to `glm`) for at least `nnetar` since it scales the data during fitting.

The functionality of `arima.errors` could also be included for ARIMA models, unless you feel it might add confusion (not necessarily replace the original function, but be able to call it from a centralized place).

**Comment by robjhyndman** [comment]
"innovation" and "response" sound ok to me.
I'm not so sure we want "working" as well. Let's leave that out for now.
My attempt to distinguish "errors" from "residuals" in Reg-ARIMA models has not really taken hold, and is probably confusing anyway. So adding these into "residuals" might be sensible, perhaps calling them "regression" residuals.

**Comment by robjhyndman** [comment]
Done in https://github.com/robjhyndman/forecast/commit/cf6b5e38df9d31f8683550a2c5c07b543552323c
