### ISSUE TITLE
Simulate.nnetar innovations 

### ISSUE THREAD

**Issue by gabrielcaceres** [robjhyndman/forecast#369]
I realized one possible point of confusion regarding the `innov` argument of `simulate.nnetar`.

The code internally standardizes the data, so the added innovations should be in the corresponding scale. Currently the innovations given through the `innov` argument are added as-is, meaning that the user should provide them in the appropriate scale (which can be done using the value in the `$scalex$scale' slot of the fitted model).

If it's more intuitive, we can change it to be done automatically inside the function. Alternatively, we can also add something like `scale.innov` as an additional logical argument.

Note that here I'm talking about just scaling by a constant multiplicative factor. Also, this only affects the `innov` argument since the other options already use the "working" residuals from the model.

**Comment by robjhyndman** [comment]
I think the following should work:
```
library(forecast)
fit <- nnetar(lynx)
res <- na.omit(residuals(fit))
plot(lynx, xlim=c(1820,1990))
lines(simulate(fit, nsim=length(res), innov=res), col='red')
```
I guess that means doing the scaling internally so the innov argument can be provided on the same scale as the residuals.

**Comment by robjhyndman** [comment]
Fixed in https://github.com/robjhyndman/forecast/commit/660f1512e13e117c581716d470b448af17bdfe43
