### ISSUE TITLE
bootstrap issue on forecast.Arima when no seasonal difference is present

### ISSUE THREAD

**Issue by mcruas** [robjhyndman/forecast#370]
Hi Rob, 

First of all, I would like to say that this package is awesome and thank you for all your contributions to the statistical community.

I am forecasting a time series, but my main interest are the different paths that the variable may have in the future. So I started looking at the bootstrap option on the `forecast.Arima function`. 

I am sending you below a code example that shows an issue while using the bootstrap=TRUE option when no seasonal difference is present. In the first model, while using `seasonal = list(order = c(1,1,1), period = 12)`, the *bootstrap* and *no bootstrap* versions are pretty similar.
But on the second model, when I was using `seasonal = list(order = c(1,0,1), period = 12)`, the *bootstrap* version gave me strange results.

```
require(forecast)
x <- ts(c(8.216, 12.116, 11.424, 11.708, 14.784, 13.94, 14.936, 14.588, 18.284, 14.768, 12.376, 
  8.608, 5.524, 11.084, 13.192, 16.332, 18.108, 15.42, 15.016, 17.98, 17.872, 18.888,
  18.724, 16.076, 21.372, 8.696, 16.928, 16.324, 19.076, 19.568, 19.948, 19.208, 19.88, 
  21.776, 17.2, 13.236, 15.212, 8.696, 11.244, 13.02, 19.372, 20.664, 21.764, 22.436, 
  22.2, 19.86, 17.132, 17.604, 11.544, 15.564, 20.912, 18.724, 21.6, 22.312, 22.12, 
  21.748, 26.85032, 22.12, 16.404, 19.476, 15.712, 22.744, 19.156, 14.296, 17.18, 24.508,
  22.236, 21.944, 23.484, 24.156, 19.452, 9.8, 15.652, 19.192, 17.74, 19.356, 22.844,
  27.736, 25.54, 24.508, 30.412, 30.248, 29.096, 19.012, 19.48, 17.896, 20.8, 21.936, 
  26.388, 30.17438, 30.79872, 27.2, 29.44574, 27.80563, 25.81288, 24.14855, 23.30059,
  26.35356, 26.59614, 26.7192, 31.68113, 28.91458, 31.68992, 30.26471, 29.80859, 30.1192, 
  25.33685, 25.88034, 33.6875, 29.06899, 28.09302, 29.62753, 31.06004, 34.11647, 32.51327,
  31.65078, 31.061, 31.22317, 30.52924, 26.90097, 25.31424, 28.1483, 29.46322, 30.00615,
  32.52554) , start = 2006, frequency = 12)

model1 = Arima(x, order = c(1,1,1), seasonal = list(order = c(1,1,1), period = 12))
plot(forecast(model1, bootstrap = FALSE, h = 55))
plot(forecast(model1, npaths = 2000, bootstrap = TRUE, h = 55))

model2 = Arima(x, order = c(1,1,1), seasonal = list(order = c(1,0,1), period = 12) )
plot(forecast(model2, h=55, npaths = 100, bootstrap = FALSE))
plot(forecast(model2, h=55, npaths = 2000, bootstrap = TRUE))
```

It looks like `simulate.Arima()` is not returning coherent values.

Best regards

**Comment by robjhyndman** [comment]
The seasonal AR parameter in model 2 is very close to 1 making the model unstable. That might be causing a problem.

**Comment by mcruas** [comment]
You are right! That may be the issue... I will use only model 1.

Thanks a lot for your answer!

**Comment by robjhyndman** [comment]
Actually, I am going to keep this open because I think there is a problem. The following example involves a stable model, but still gives bad results:
```
fit <- Arima(x, order=c(1,1,1), seasonal=c(0,0,1))
plot(forecast(fit, bootstrap=TRUE, npaths=500,h=100))
```

**Comment by robjhyndman** [comment]
This problem is being caused by the residuals have a mean of 0.6, which induces a drift in the bootstrap simulations. So not a problem with the code, just a bad model which shows up when bootstrapped.
