### ISSUE TITLE
Not available under R 3.3.1 version

### ISSUE THREAD

**Issue by xiaowangmath** [robjhyndman/forecast#371]

**Comment by robjhyndman** [comment]
You will need to provide more information than that. I am using the package with R 3.3.1 so it is available.

**Comment by xiaowangmath** [comment]
sorry, false alarm. I was using company computer and there are some issue regarding remote disk.


Thank you for your reply.


Sincerely,

Xiao WANG
Phone: (+1) 682-558-1630
Email: wxxw1982@hotmail.com<mailto:wxxw1982@hotmail.com>









________________________________
