### ISSUE TITLE
Add all autoplot functions to exports so they can be used by other packages

### ISSUE THREAD

**Issue by robjhyndman** [robjhyndman/forecast#375]
To use `autoplot.ts` you currently have to load the forecast package rather than use forecast::autoplot.ts.

**Comment by mitchelloharawild** [comment]
The current exports match ggfortify, not sure if it's appropriate to export S3 methods using export(). Regardless, working on it.

Also, while looking at the namespace, I found a few weird things:
```R
> devtools::missing_s3("github/forecast/")
Loading forecast
This is forecast 7.4 

[1] "getResponse.bats"       "getResponse.tbats"      "plot.armaroots"         "plot.mpacf"             "scale.ts"              
[6] "seasonal.decomposed.ts" "seasonal.stl"           "seasonal.tbats"         "subset.forecast"     
```
The last 4 are some of my WIP S3 methods, but the first 5 should be exported, right?

Also, on the same note, many other S3 methods aren't exported, such as:
```R
S3method(fitted,ets)
S3method(fitted,tbats)
S3method(fitted,bats)
S3method(fitted,nnetar)
S3method(fitted,fracdiff)
S3method(fitted,ar)
```

**Comment by robjhyndman** [comment]
They should only be exported if it makes sense for a user to call them directly, or if it makes sense for another package to call them. I want to call the autoplot.ts function from another package, and I can foresee reasons why other autoplot functions might be called. I'm not so sure that getResponse methods need to be exported, or plot.mpacf, or plot.armaroots. But scale.ts, and seasonal.stl and seasonal.decomposed.ts should be exported. As tbats is part of forecast package, there isn't a strong argument for exporting seasonal.tbats. Similarly for subset.forecast.
