### ISSUE TITLE
gglagplot colours

### ISSUE THREAD

**Issue by robjhyndman** [robjhyndman/forecast#377]
I think the colours should show the season of the observation on the vertical axis. 

Example:

```
beer2 <- window(ausbeer, start=1992)
gglagplot(beer2, lags=9, do.lines=FALSE, continuous=FALSE)
```

It currently seems to show the quarter on the horizontal axis which I think is less interpretable.

**Comment by mitchelloharawild** [comment]
I'm not sure if I understand the issue, are you referring to the facet layout, or the individual plots?

The facet layout of `gglagplot` is consistent with `lag.plot`.

**Comment by robjhyndman** [comment]
The layout is fine. But the colours indicating the season within the individual plots is confusing. I think the colour should indicate the season of the vertical axis, not the horizontal axis.
![beerlagplot-1](https://cloud.githubusercontent.com/assets/127518/20782381/771b6d08-b7df-11e6-922e-5bff4a44f161.png)

In this plot, the colours are mapped to the quarter of the series on the horizontal axes. Note that purple is always used for the right hand cloud of points, but the colours of the top most cloud of points varies. If colour was mapped to the quarter of the series on the vertical axis, it would be the other way around. I think it is easier to explain that way.

**Comment by mitchelloharawild** [comment]
Resolved in #402

```R
beer2 <- window(ausbeer, start=1992)
gglagplot(beer2, lags=9, do.lines=FALSE, continuous=FALSE)
```
![rplot03](https://cloud.githubusercontent.com/assets/16127127/20782585/37329fe8-b7e1-11e6-9e62-8b64540665cd.png)

**Comment by robjhyndman** [comment]
There appear to be some anomalies here. See the stray red dot in the lag 3 panel -- it should be purple.

**Comment by mitchelloharawild** [comment]
Off-by-one. #404

Weird, ifelse() doesn't give warnings for mismatched lengths.
```R
ifelse(rep(TRUE,4), 1:2, 1:4)
[1] 1 2 1 2
```

![rplot04](https://cloud.githubusercontent.com/assets/16127127/20783096/a1b41442-b7e5-11e6-8875-8aec18e9c4a9.png)
