### ISSUE TITLE
Pacf element series does not contain name

### ISSUE THREAD

**Issue by skloibhofer** [robjhyndman/forecast#379]
The minimal example below shows a different behavior of Pacf in comparison to Acf. It does not take the name of the x argument as series element, but always takes the value "x".  This leads to an error message when using autoplot afterwards:
Error in eval(expr, envir, enclos) : object 'x' not found

```{r}
library(forecast)
library(ggplot2)

Acf(wineind)$series
# With Pacf series entry always is "x"
Pacf(wineind)$series

# Problems occur when using the Pacf with autoplot
autoplot(Pacf(wineind))
```

I hope that really is the little error I believe it is.

**Comment by robjhyndman** [comment]
`autoplot` does not have a method for objects created from `Pacf`. Use `ggPacf` instead.

I'll fix the series name issue.

**Comment by skloibhofer** [comment]
Thank you.

`autoplot` for `Pacf` works analogous to `ggPacf` if the name is reset manually, I think because the class is `acf`.

Another little documentation issue I just saw, is the value of `autoplot, ggAcf,` ... In my opinion it returns a `ggplot` object, at least it is possible to modify it in `ggplot` style.

**Comment by mitchelloharawild** [comment]
Hi,

You're correct that autoplot for Pacf uses autoplot.acf because of its class. As Rob mentioned, the series name issue being fixed should make autoplot.acf work for your function `autoplot(Pacf(wineind))` above.

As for the documentation, you are also correct that it returns a ggplot object. I'll clarify that when I have the chance.

**Comment by robjhyndman** [comment]
Fixed in https://github.com/robjhyndman/forecast/commit/d560135bc0ef9af09f6451ce75a3bd07e36352df
