### ISSUE TITLE
Multiple seasonality with ARIMA models

### ISSUE THREAD

**Issue by robjhyndman** [robjhyndman/forecast#38]
Update fourier and fourierf to handle msts objects.

Update Arima and auto.arima to handle msts objects using the ts.frequency attribute.

Update msts so ts.frequency is not over-ridden by the existing frequency when argument is a ts object.

**Comment by robjhyndman** [comment]
The way to handle this is it to use fourier terms in Arima and auto.arima. fourier() now handles multiple seasonal time series.

**Comment by denadai2** [comment]
thanks

2016-03-13 9:39 GMT+01:00 Rob J Hyndman <notifications@github.com>:

> The way to handle this is it to use fourier terms in Arima and auto.arima.
> fourier() now handles multiple seasonal time series.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/robjhyndman/forecast/issues/38#issuecomment-195914656>
> .
>



-- 
*Marco De Nadai*
*me@marcodena.it <me@marcodena.it>*
http://www.marcodena.it/
<http://www.marcodena.it/?utm_source=email&utm_medium=email&utm_campaign=Email%2Bpersonali>
