### ISSUE TITLE
Request for level argument for Croston

### ISSUE THREAD

**Issue by harmbuisman** [robjhyndman/forecast#380]
A forecast with Croston now provides an interface to get the confidence bounds via fc$model$demand, but this is always a default confidence range [80,95]. I would like to request the argument in croston( .., level = [80,95] ) where I can specify my own bounds which is available for most of the other forecast models. Thanks

**Comment by robjhyndman** [comment]
Those PIs are not valid for this type of data. I will remove them rather
than provide more flexible user access

-------------------------------------------------------------
Rob J Hyndman
Professor of Statistics, Monash University
www.robjhyndman.com
