### ISSUE TITLE
Question: what is the base of "level" input in the forecast() function?

### ISSUE THREAD

**Issue by nkever** [robjhyndman/forecast#382]
This is a question rather than an issue. When I use the forecast() function to get prediction intervals, if I want a 90% confidence interval, should I put "level" as 0.9 or 90?

From the latest doc, it seems that 90 is the right one to use? If so, I wonder whether this was a recent change since previously we have been using 0.9 which seemed to give the right results?

Thanks!

**Comment by robjhyndman** [comment]
Either will work. If the number is less than 1, it is interpreted as a proportion. If the number is greater than 1, it is interpreted as a percentage.

**Comment by nkever** [comment]
Thanks, Professor Hyndman. The version I used recently has been unstable. I tried forecast(m, h, level = c(0.9, 0.76)) and forecast(m, h, level = 100 * c(0.9, 0.76)) repeatedly, and the results of both can be either a very narrow range around the mean which is like 0.9% level, or a wide range which looks more like the real 90% confidence level.

More specifically, the pattern seems to be like:
level = c(0.9, 0.76): narrow range
level = 100 * c(0.9, 0.76): narrow range
level = c(0.9, 0.76): wide range
level = c(0.9, 0.76): narrow range
level = c(0.9, 0.76): narrow range
level = c(0.9, 0.76): narrow range
...

And 
level = 100 * c(0.9, 0.76): narrow range
level = c(0.9, 0.76): narrow range
level = 100 * c(0.9, 0.76): wide range
level = 100 * c(0.9, 0.76): wide range
level = 100 * c(0.9, 0.76): wide range

Not sure if I need to update my package or if the internal version of my company is not stable. I will check.

Thanks again.

**Comment by robjhyndman** [comment]
That's not good. What is m here? A time series or a model?

**Comment by nkever** [comment]
m is the result of the following, where model.params=list(ets=list(model="ANN", alpha=NULL))

m <- ets(qf.hist$value, model=model.params$ets$model,
         alpha=model.params$ets$alpha, beta=model.params$ets$beta,
         gamma=model.params$ets$gamma)

qf.hist$hist is a time series with 1397 data points/days (not very predictable, fluctuates a lot). And I am trying to get a range forecast for 180 days.

Does "ANN" or "ZZZ" make a difference?

We recently had an internal update of the package. Someone was wondering if this could be due to a version clash, but not sure how or why it be occuring.

**Comment by nkever** [comment]
Update: I found that level = 0.9 gives the wrong range (very narrow, almost the same as mean) on the first run, while level = 90 gives the right range on the first run. Still not sure why it seems to remember the previous results when I alternated between 0.9 and 90, but at least now I know that it's better to make sure I use level = 90 in my code.

**Comment by robjhyndman** [comment]
I can't replicate this problem. Please provide a reproducible example.

**Comment by nkever** [comment]
m is the result of the following, where
model.params=list(ets=list(model="ANN", alpha=NULL))

m <- ets(qf.hist$value, model=model.params$ets$model,
         alpha=model.params$ets$alpha, beta=model.params$ets$beta,
         gamma=model.params$ets$gamma)

qf.hist$hist is a time series with 1397 data points/days (not very
predictable, fluctuates a lot). And I am trying to get a range forecast for
180 days.

Does "ANN" or "ZZZ" make a difference?

We recently had an internal update of the package. Someone was wondering if
this could be due to a version clash, but not sure how or why it be
occuring.

**Comment by robjhyndman** [comment]
Just repeating the same information does not help. I need a reproducible example. I don't have qf.hist, so I can't reproduce using this code.
