### ISSUE TITLE
Choose best ARMA model

### ISSUE THREAD

**Issue by salauer** [robjhyndman/forecast#384]
Hello Rob,

I want to compare a GARCH model with an ARMA model and was hoping to use auto.arima() to choose the best ARMA model. However, I still get non-zero d and D terms after specifying otherwise.

```
fit <- auto.arima(WWWusage, d=0, D=0, seasonal = FALSE)
fit$arma
[1] 2 2 0 0 1 0 0
```

That output means that the d=2 and D=1, right? If you could clear this up for me, I'd much appreciate it.

Thanks,
Steve

**Comment by robjhyndman** [comment]
```
> arimaorder(fit)
[1] 2 0 2
```

Please read the help file more carefully.

**Comment by salauer** [comment]
Thanks!
