### ISSUE TITLE
issue with duplicated rownames in high frequency ts

### ISSUE THREAD

**Issue by VincentGuyader** [robjhyndman/forecast#385]
Hi, 

If I use half hourly data such as this one:

`big <- ts(rnorm(65710),start=c(2013,1),frequency=17532)`

i cant use some of forecasting tool, for example :

`forecast::rwf(big)`

> Error in (function (..., row.names = NULL, check.rows = FALSE, check.names = TRUE,  : 
>   'row.names' dupliqués : 2016.748

I track the problem, and it's because of the rownames in `lower` and `upper` time series. the rownames created in the lagwalk function are : 2016.748 2016.748 2016.748 2016.748 2016.749 . there is not enough precision in the ts rownames. And the `as.data.frame` in `print.forecast`give an error.

`out <- forecast::rwf(big)
print(out)# error
class(out)<-"list"
print(out) #ok
`

It could be a goo idea to "make.unique" the rownames in any forecast objet.

Regards

**Comment by robjhyndman** [comment]
Fixed in https://github.com/robjhyndman/forecast/commit/e8c81983eafb6632a51689814c2207663e87dd8b
