### ISSUE TITLE
add smoother to ggtsdisplay upper graph?

### ISSUE THREAD

**Issue by Rmadillo** [robjhyndman/forecast#389]
I like having the `ggtsdisplay` function provide me with the major assumptions in one graph, so I add  
          
`tsplot <- tsplot + ggplot2::geom_point() **+ ggplot2::geom_smooth()**`

to line 20 of that function. 

It would be cool to have that as a T/F option!

**Comment by robjhyndman** [comment]
Done. https://github.com/robjhyndman/forecast/commit/01f427502cf2d0dcb85d67fa26f01abc106cb438

**Comment by Rmadillo** [comment]
That's great, thanks so much!!!
