### ISSUE TITLE
Allow re-use of a fitted model with new data from forecast function

### ISSUE THREAD

**Issue by khalida** [robjhyndman/forecast#393]
I think it would be useful if the `forecast()` function could handle the case where an already fitted function is provided as an input, along with some new data which is to be forecast forward using that existing model.

There are two feature requests currently open, which I believe are asking for this functionality for specific forecast model types [here](https://github.com/robjhyndman/forecast/issues/303) and [here](https://github.com/robjhyndman/forecast/issues/41). It would be even more convenient if the result from a call to `forecast()` could be directly re-used in another call to forecast. Something like:

`fc1 <- forecast(oneTimeSeries)`
`fc2 <- forecast(anotherTimeSeries, model=fc2$model)`

Where this would produce an automatic forecast and associated model based on `oneTimeSeries`, and then use the same model without refitting on `anotherTimeSeries`.

This would make little sense if the two time series are unrelated, but would be very useful for cases in which rolling forecasts need to be produced, and it is not feasible (e.g. due to time constraints) to re-fit the model repeatedly.

**Comment by robjhyndman** [comment]
Added in https://github.com/robjhyndman/forecast/commit/b6d3df5d238a9fafb7505a2ad13945a39c8b268a
