### ISSUE TITLE
Use of minimal samples in naive seasonal ARIMA model throws an error

### ISSUE THREAD

**Issue by mungojam** [robjhyndman/forecast#396]
To produce a simple seasonal naïve forecast, it should be possible to use an Arima model and provide the theoretical minimum number of samples, but this fails with an error during the model creation:
 
```
model <- Arima(
c(1, 2, 3, 4, 5, 6, 7),
order = c(0,0,0),
seasonal = list(period=7, order=c(0,1,0))
)
```
 
In forecast package v7.3 (and earlier), this gives the error:
 

> Error in stats::arima(x = x, order = order, seasonal = seasonal, include.mean = include.mean,  :
>   too few non-missing observations

 
If I add a dummy entry at the start of the series, then it is fine and the dummy entry goes unused. This is our current workaround.
 
```
model <- Arima(
c(5,1,2,3,4,5,6,7),
order = c(0,0,0),
seasonal = list(period=7, order=c(0,1,0))
)
```
 
Forecasting with this produces the expected result
 
`forecast(model, level=0, h = 7)$mean`

> Time Series:
> Start = 9 
> End = 15 
> Frequency = 1 
> [1] 1 2 3 4 5 6 7

 
It might seem like a rubbish forecast to produce, but it is our fall-back model during automated forecasting for occasions when only the bare minimum of historical data is available. We also include regressors in the real model but I thought it better to raise it for the minimal case.

**Comment by robjhyndman** [comment]
The problem is that with 7 observations after differencing at lag 7, there are no observations left. Adding one more observation means that you have one observation after differencing which is the minimum required to do something.

**Comment by mungojam** [comment]
The 8th value added isn't used in the example forecast I included (or when we add it for real in our forecast), so it is not required to produce a naive seasonal forecast when the model is a basic (0,0,0)(0,1,0) model or (0,0,0)(1,0,0).

**Comment by mungojam** [comment]
Some further proof that the extra value is not used in the forecast, just extending the number of output values. Perhaps it is used for some other properties of the model though

```
 model <- Arima(
                                   c(999999,1,2,3,4,5,6,7),
                                   order = c(0,0,0),
                                   seasonal = list(period=7, order=c(0,1,0))
                               )
                               
                               forecast(model, level=0, h = 21)$mean
```

> Time Series:
> Start = 9 
> End = 29 
> Frequency = 1 
>  [1] 1 2 3 4 5 6 7 1 2 3 4 5 6 7 1 2 3 4 5 6 7

**Comment by robjhyndman** [comment]
OK, but the error is not coming from the forecast package. The `arima` function from the stats package will not "fit" the model because it has no observations. You would have to convince the R core team to change that. I could catch the error in `Arima` before `arima` gets called, but it hardly seems worth the effort for the few occasions when people try to use an ARIMA model without any observations. If that's what you want to do, then catch the problem yourself before calling `Arima`.

**Comment by mungojam** [comment]
I take your point about zero observations. Here is an alternative, and more logical way that I tried to do naive seasonal using (0,0,0)(1,0,0) that fails instead in the forecast.Arima function:

```
model <- Arima(
c(5, 5, 5, 1,2,3,4,5,6,7),
order = c(0,0,0),
seasonal = list(period=7, order=c(1,0,0)),
include.constant=FALSE,
fixed=c(1)
)
```

`forecast.Arima(model, level = 0, h = 7)`

>    Point Forecast Lo 0 Hi 0
> 11            NaN  NaN  NaN
> 12            NaN  NaN  NaN
> 13            NaN  NaN  NaN
> 14            NaN  NaN  NaN
> 15            NaN  NaN  NaN
> 16            NaN  NaN  NaN
> 17            NaN  NaN  NaN
> Warning message:
> In forecast.Arima(model, level = 0, h = 7) :
>   Upper prediction intervals are not finite.

**Comment by robjhyndman** [comment]
A coefficient of 1 is inadmissible. Make the coefficient 0.9 and the forecast works as it should.

**Comment by mungojam** [comment]
Thanks, 0.999999999 works a treat. That's a nicer workaround than our current one of adding in dummy values as I can do it at the calibration rather than forecasting stage.
