### ISSUE TITLE
Make autoplot.decomposed.ts look like autoplot.stl

### ISSUE THREAD

**Issue by robjhyndman** [robjhyndman/forecast#397]
I've changed the ordering and labelling already. But it needs the remainder graph shown using geom_segment(lineend='butt').

**Comment by robjhyndman** [comment]
MRE:
```
library(fpp)
autoplot(stl(elecequip, s.window='periodic'))
autoplot(decompose(elecequip))
```

**Comment by mitchelloharawild** [comment]
When I wrote it, I aimed for consistency with plot()
Perhaps this should be an option?

**Comment by robjhyndman** [comment]
I know. But I'd rather consistency between seasonal decomposition methods rather than consistency between plot and autoplot. I don't control the plot.xxx functions, but we can at least make the autoplot.xxx functions consistent with each other. I can't think of a particular need for making plot.xx and autoplot.xx be consistent.

**Comment by mitchelloharawild** [comment]
```R
library(fpp)
autoplot(decompose(elecequip))
```
![rplot02](https://cloud.githubusercontent.com/assets/16127127/20782154/4049c808-b7dd-11e6-9da7-90409a7a6426.png)
