### ISSUE TITLE
autoplot.seas

### ISSUE THREAD

**Issue by robjhyndman** [robjhyndman/forecast#398]
I'm adding functions to allow X-13-ARIMA decomposition via the seasonal package. Can you please write an `autoplot.seas` function to mimic `autoplot.stl`.

**Comment by mitchelloharawild** [comment]
Added in #399
```R
library(seasonal)
m <- seas(AirPassengers)
autoplot(m)
```
![rplot01](https://cloud.githubusercontent.com/assets/16127127/20781863/b4e89638-b7da-11e6-9873-e6d2383f617e.png)
