### ISSUE TITLE
ggplot function enhancements

### ISSUE THREAD

**Issue by mitchelloharawild** [robjhyndman/forecast#429]
- [x] Convert grid aligned plots to facetted plots
- [x] Remove warning when using geom_forecast() with confidence intervals
- [x] Add mforecast support to geom_forecast()
- [x] Improve ggts() consistency with ggplot (?)
- [x] Add more convenience functions to reduce code re-use
- [x] Add `level` legend for geom_forecast()
- [x] Add custom legend icon for forecasts
- [x] Fix geom_forecast(h=1)
- [x] Test full functionality of new scale, perhaps generalise as scale_discrete_grayscale

**Comment by robjhyndman** [comment]
The new x-axis scale needs work:

```R
library(fpp)
autoplot(dj)
```

**Comment by mitchelloharawild** [comment]
It was mainly a demonstration/test of the breaks=function(x).
Hence item number one, is dedicated to improving it. :smile:

I plan to incorporate seasonality on this function also.
