### ISSUE TITLE
Forecast Horizons for meanf, croston, naive, splinef > 10

### ISSUE THREAD

**Issue by AnscombesGimlet** [robjhyndman/forecast#449]
All 4 of these methods produce an error when h > 10:

forecast(meanf(AirPassengers), h=12)

Error in forecast.forecast(meanf(AirPassengers), h = 12) : 
  Please select a longer horizon when the forecasts are first computed

**Comment by AnscombesGimlet** [comment]
User error.

**Comment by gkourogiorgas** [comment]
@AnscombesGimlet can you explain a bit more what you mean? I get the same error

**Comment by AnscombesGimlet** [comment]
@gkourogiorgas Sure, you just need to set the forecast horizon in the model building function. I.e. meanf(x, h=horizon) rather than in the forecast function.

**Comment by mitchelloharawild** [comment]
`meanf` is a function which produces forecasts, a list of functions which produce forecasts can be found here: https://otexts.org/fpp2/the-forecast-package-in-r.html

The `h` argument sets the forecast horizon, and so when you write `forecast(meanf(AirPassengers), h=12)`, the `forecast` function is redundant.

The correct way to write the code above is `meanf(AirPassengers, h=12)`.
