### ISSUE TITLE
hi i bumped on some errors when trying install.packages forecast_7.3. from offline source

### ISSUE THREAD

**Issue by savvaskef** [robjhyndman/forecast#461]
I tried installations with RStudio from an offline source i found both by download.pac.kage and from the temp binaries that are stored when you install from online install.packages. forecast wont co-operate.The error that appears is : Installing package into ‘C:/Users/savvas/Documents/R/win-library/3.3’
(as ‘lib’ is unspecified)
Warning in install.packages :
package ‘C:/Users/savvas/Documents/Visual Studio 2010/Projects/SchedFlows V6Projects/r packages/forecast_7.3.zip’ is not available (for R version 3.3.0)
(the problem appears only at zoo and forecast packages)
(when i try the same via r.net i get an even more compex error 127.)
Any ideas on how to circumvent this problem?

**Comment by robjhyndman** [comment]
Never seen that before. Install via CRAN or github.

**Comment by savvaskef** [comment]
the problem lies with r version. it must be set to R-3.3.2 . when r-3.3.3 is used zoo,forecast and possibly other packages remain stubbornly uninstallable from an off-line source

**Comment by robjhyndman** [comment]
Maybe one of the zoo dependencies requires R>=3.3.2

**Comment by savvaskef** [comment]
correction ... my old installation was R-3.3.0... it is the one where the error is raised. with R.3.3.2 that i installed later there is no problem
