### ISSUE TITLE
From forecast to 1-based array and back

### ISSUE THREAD

**Issue by savvaskef** [robjhyndman/forecast#462]
hi i am using forecastHybrid the constituents of which are of class:forecast. I guessed this class comes from your binary.Do you know how can I turn a forecast variable to a 1-based two dimensinal table suitable for use in excel.range.value array?(I am using r.net and retrieve results using engine.GetSymbol("fcast"))

It's a bit out of the forecast scope but do you know the reverse allocation - turning a range into a dataset as if it was loaded with "c(1900,1200,,,,etc) or better as if you could allocate them to a timeseries variable?
You don't have to know of r.net procedures but you will possibly do know of variable manipulation in R as much as anyone can...

If you don't know of it but you do know of a couple of links, that would do too, after all you are the forecast master

**Comment by robjhyndman** [comment]
Ask on stackoverflow.com.
