### ISSUE TITLE
phase problems

### ISSUE THREAD

**Issue by savvaskef** [robjhyndman/forecast#481]
Hi, I tried to use forecast in a dataset that is used in a tutorial.so the data have an autoregression at phases 2,3,4,6,12. There is just a small variation so as to avoid problems in confidence intervals.The result is quite intriguing. The fit function produces good results with a phase of 1 and thus seasonality dampened to a line. Its’s such an easy problem that it can pass under the radar I guess.See what you can tell me about it: I enlist the r commands just below.
 
 
datset_freq2<-c(3030,1830,3030,1830,3030,1830,3030,1830,3030,1830,3030,1830,3060,1830,3030,1830,3030,1830,3030,1830,3030,1830,3030,1830,3030,1830,3030,1830,3030,1830,3030,1830,3030,1830,3030,1830)
timeseriesdataset2 <-ts(datset_freq2,frequency=12)
fit<-auto.arima(y=timeseriesdataset2)
fcast <- forecast(fit,h=12,level=c(99,95))
 
#plot(fcast)
 
# you can observe the behavior I describe by commparing
fcast$fitted
with
timeseriesdataset2
thnx for your time
Hi, I tried to use forecast in a dataset that is used in a tutorial.so the data have an autoregression at phases 2,3,4,6,12. There is just a small variation so as to avoid problems in confidence intervals.The result is quite intriguing. The fit function produces good results with a phase of 1 and thus forecast is dampened to a line. Its’s such an easy problem that it can pass under the radar I guess.See what you can tell me about it: I enlist the r commands just below.
 
 
datset_freq2<-c(3030,1830,3030,1830,3030,1830,3030,1830,3030,1830,3030,1830,3060,1830,3030,1830,3030,1830,3030,1830,3030,1830,3030,1830,3030,1830,3030,1830,3030,1830,3030,1830,3030,1830,3030,1830)
timeseriesdataset2 <-ts(datset_freq2,frequency=12)
fit<-auto.arima(y=timeseriesdataset2)
fcast <- forecast(fit,h=12,level=c(99,95))
 
#plot(fcast)
 
# you can observe the behavior I describe by commparing
fcast$fitted
with
timeseriesdataset2

thnx for your time

**Comment by robjhyndman** [comment]
The problem is that auto.arima is not picking up the seasonality, and is fitting an ARIMA(0,1,0) model.
