### ISSUE TITLE
Add pso as an optimization option in ets

### ISSUE THREAD

**Issue by robjhyndman** [robjhyndman/forecast#483]
I'm interested to see how much difference it makes to forecast accuracy if we use something more reliable in the presence of local minima.

**Comment by AnscombesGimlet** [comment]
I believe the 'pso' R package has a plug and play replacement for the optim function. See pso::psoptim. See page 6: https://cran.r-project.org/web/packages/pso/pso.pdf

Hope this helps!

**Comment by cbergmeir** [comment]
I remember that 4 years ago I made experiments with a couple of solvers and the M3 data, but the results were not promising. I.e., same or worse accuracy and much increased runtime. The code for using Rmalschains is still in ets.R, but it is commented out. Also, pso wouldn't be my first choice, but I would try optimx, parma::cmaes, GenSA, RcppDE, and Rmalschains. All in all sounds like a good topic for a Masters thesis.

**Comment by robjhyndman** [comment]
Yes, I recall. I don't think it is likely to give much better results, and it would obviously take a long running time. The idea was to include an option to get the global optimum with high probability if people want it, but I'm not sold on pso. The existing optimizer often finds a local optimum, but that seems to work ok for forecasting purposes.

**Comment by AnscombesGimlet** [comment]
Perhaps allow for user-defined optimization algos? Or is there too much variability in the functions output/format that cbergmeir mentions?

**Comment by robjhyndman** [comment]
The output varies enormously. optimix might be a way around it as it tries to standardize the format from various algorithms.
