### ISSUE TITLE
Naive forecasts break when horizon is 1

### ISSUE THREAD

**Issue by ganesh-krishnan** [robjhyndman/forecast#484]
`> forecast(naive(AirPassengers), h = 1)`
`Error in .cbind.ts(list(...), .makeNamesTs(...), dframe = FALSE, union = TRUE) : 
  non-time series not of the correct length`

Seems like a problem with the tsp attributes. I'm using forecast v7.3 on R 3.2.4

**Comment by robjhyndman** [comment]
Now fixed in https://github.com/robjhyndman/forecast/commit/553a151f970ce523aff07b0e024ed2ffa5e65bb9
Note that you can just use `naive(AirPassengers,h=1)` as `naive()` produces a forecast object.
