### ISSUE TITLE
release 7.4 and ARM hardware

### ISSUE THREAD

**Issue by dashaub** [robjhyndman/forecast#485]
The next release--and the current Github version--are not automatically installable on ARM hardware--or more broadly any x86_64 or x86_32 CPU. ARM CPUs are very popular for mobile computing and system on a chip boards running Linux such as the Raspberry Pi and many Chromebooks. This is because you're importing the "seasonal" package which has a unusual "wrapper" package "x13binary" that installs the compiled executable US Census program for supported platforms and architectures in the "x13prebuilt" package. Right now a user needs to follow [these](https://github.com/christophsax/seasonal/wiki/Compiling-X-13ARIMA-SEATS-from-Source-for-Ubuntu) instructions to compile manually which aren't too bad but mean automatic `install.packages()` installation will be broken for lots of users. I'm investigating getting ARM binaries added over [here](https://github.com/christophsax/seasonal/issues/195).

**Comment by robjhyndman** [comment]
Thanks for letting me know. We reference seasonal functions in `trendcycle`, `remainder` and `seasadj.seas`. I'll see if I can avoid it while still supporting seasonal adjustment of `seas` objects.

**Comment by robjhyndman** [comment]
Fixed in https://github.com/robjhyndman/forecast/commit/eea2a885ffa9a397586a9fef4acffee898c5b892

**Comment by dashaub** [comment]
@robjhyndman FYI The latest release of "x13binary" fixes this, so the "seasonal" package can now be installed as usual.
