### ISSUE TITLE
Theta accuracy ACF1 disappeared @ version 7.2

### ISSUE THREAD

**Issue by FransAndersen** [robjhyndman/forecast#486]
The accuracy measure ACF1 is missing when using the theta model in the forecasting package version 7.2 and onward. Is it a bug or a conscious choice?

Example script:
variableValues <- c(33736.25,33712.5,38087.75,34594.75,30841.25,36909.75,37604,35536,37919.25,38211,39905.75,38832.75,36678.75,37647.75,41619.5,39772,34867.25,38081.75,37346.5,41084,40469,40494.25,45103.5,44942.25,49926.5,49098.25,55861.75,49798.5,60079.5,54494.25,52755.5,54108.5,51919.5,58384,59443.75,53449.75,61783.5,56632.25,60741.25,53469.25,58679.25,56215.5,60113.75,55327.25,47813.5,56163.75,55138.25,42860.5,53791.75,58305.75,57092.25,65094,58048.5,62106.75,70625.75,58003.75,57788.25,48779,37041.5,31290.5,29668.5,26596.25,29381,28410,27741.25,34613.25,38353.25,38667.75,40339.25,41320,40927.75,45773.5,44696.75,40971.5,50719.75,46328,38762.75,42482.5,43731.25,44469.75,47563.5,49267.5,51317.5,49352,48782.5,50155,58700.25,47921.25,51833.5,56210.75,52743.5,52627.5,50518.75,45608.75,45609.25,40429.5,45020.25,46274.5,48017,38877.5,44003.75,35805.5,41224.25,40429.75,41069.75,45422,42740.25,39639.75,44829.5,41062.75,38255.5,38981,38435.5,36320,40649.25,38103.5,36962,41676,36727.25,12062.25)
Thetaforecast <- thetaf(variableValues)
accuracy <- accuracy(Thetaforecast)
accuracy[,'ACF1']

**Comment by robjhyndman** [comment]
Fixed in https://github.com/robjhyndman/forecast/commit/7b97d5f032eab9cf750c2f88e94d749be688f41b
