### ISSUE TITLE
auto.arima prints newline when "No suitable ARIMA model found"

### ISSUE THREAD

**Issue by basjacobs93** [robjhyndman/forecast#489]
In the following snippet, an unwanted newline is printed by auto.arima

```
library(forecast)
train <- ts(1:120, frequency = 52)
train_ext <- ts(rep(0, 120), frequency = 52)
try(stlm(train, lambda=0, method="arima", xreg = train_ext), silent = TRUE)
```

It is caused by `cat("\n")` in line 463 `newarima2.R`, right before `stop("No suitable ARIMA model found")`. Removing that line fixes the issue, but I am not sure if it is needed for anything else.

**Comment by robjhyndman** [comment]
Thanks. Fixed in https://github.com/robjhyndman/forecast/commit/29db025df47f6b2866343bcfe52fdcd082408c54
