### ISSUE TITLE
auto.arima returning intercept with allow.mean=F

### ISSUE THREAD

**Issue by JordanCuevas** [robjhyndman/forecast#494]
See example below, run on R 3.3.1 with forecast 7.3. This scenario should return either 0 or an error.
> library(forecast)
> auto.arima(c(0.5), stationary=T, seasonal=F, allowdrift=F, allowmean=F)
Series: c(0.5) 
ARIMA(0,0,0) with non-zero mean 
Coefficients:
intercept  
      0.5  
sigma^2 estimated as NaN:  log likelihood=Inf
AIC=-Inf   AICc=-Inf   BIC=-Inf

**Comment by robjhyndman** [comment]
Fixed in https://github.com/robjhyndman/forecast/commit/61fcdd6866954bdd16314f28e0dff84ab01e6eb0
