### ISSUE TITLE
OCSBtest under auto arima

### ISSUE THREAD

**Issue by pranavbahl2308** [robjhyndman/forecast#495]
I think there is a typo in a line of auto arima file (/R/ewarima2.R) where the grep command seems to find if coefficient for 'y.two' exists but in actual the code is search for variable 't.two'. Following is the line of code (line# 779)

t.two.pos <- grep("t.two", rownames(reg.coefs), fixed = TRUE)

Please correct me if I am wrong

**Comment by robjhyndman** [comment]
Thanks. Fixed in https://github.com/robjhyndman/forecast/commit/8e85b5905e4227de8b2a8e430513904dae50af05
