### ISSUE TITLE
Error in forecast.lm after updating

### ISSUE THREAD

**Issue by tomhen1** [robjhyndman/forecast#497]
When I previously run the code below, it worked fine. But after the new R update I got the error message:

Error in eval(expr, envir, enclos) : object 'solvedFN___1' not found

The code I run is:

library(quantmod)
library(zoo)
library(forecast)
getSymbols("GDPC1",src="FRED")
GDPC1 <- na.locf(GDPC1)[endpoints(na.locf(GDPC1))]
GDPC1<-zooreg(GDPC1[,1],start=c(1947,1),frequency = 4)
GDP<- window(GDPC1,start=c(1950,1),end=c(2015,4))
d_gdp<-diff(log(GDP))
n<-length(d_gdp)
actual <-NULL
predicted0 <- NULL
START <- 40
for(t in START:n){
  g <- d_gdp[1:(t-1)]
  lg <- l_gdp[1:(t-1)]
  pred0 <- lm( g ~ lg ) 
  nd0 <- data.frame(lg <- l_gdp[t])
  fc0 <- forecast.lm(pred0, nd0 ,h=1,ts=T)  
  predicted0 <- c(predicted0, fc0$mean)   
  actual <- c(actual,d_gdp[t])
}

**Comment by mitchelloharawild** [comment]
Hi there,

I don't have `l_gdp` so I cannot reproduce this error. Is it just the log of d_gdp?

**Comment by mitchelloharawild** [comment]
Other than that, your data.frame should be named, so instead of 
```R
nd0 <- data.frame(lg <- l_gdp[t])
```

It should be 
```R
nd0 <- data.frame(lg = l_gdp[t])
```

**Comment by tomhen1** [comment]
Thanks a lot. It now runs perfectly when changing "<-" to "=".
