### ISSUE TITLE
Named Confidence Intervals in forecast.ets, forecast.bats, forecast.tbats objects

### ISSUE THREAD

**Issue by arodionoff** [robjhyndman/forecast#500]
Could you create Named Confidence Intervals in forecast.ets, forecast.bats, forecast.tbats objects just as they are in other forecasts (stl, arima). It turns out the lack of uniformity creates certain problems for writing functions to ggplot. 

For example, in package 7.3 forecast.ets$lower and forecast.ets$lower have Named Confidence Intervals  as 'Series 1' and 'Series 2'. Unfortunately forecast.bats$upper, forecast.bats$lower, forecast.tbats$upper,  and forecast.tbats$lower do not have any Named columns at all.

**Comment by mitchelloharawild** [comment]
I cannot reproduce the confidence interval name issues you're having for ETS, could you provide a MRE?
```R
colnames(forecast(ets(USAccDeaths))$lower)
[1] "80%" "95%"
```

I'll look into BATS and TBATS

**Comment by arodionoff** [comment]
Unfortunately, I can not boast of such a listing

> colnames(forecast(ets(USAccDeaths))$lower)
[1] "Series 1" "Series 2"

2017-02-21 13:53 GMT+06:00 mitchelloharawild <notifications@github.com>:

**Comment by mitchelloharawild** [comment]
Have you installed the latest version from github?

```R
# install.packages("devtools")
devtools::install_github("robjhyndman/forecast")
```

**Comment by mitchelloharawild** [comment]
I've fixed this issue for BATS and TBATS in #501.

**Comment by arodionoff** [comment]
I can not use version from "github", only CRAN ver .7.3.

> devtools::install_github("robjhyndman/forecast")
Error in curl::curl_fetch_disk(url, x$path, handle = handle) :
  Couldn't connect to server

2017-02-21 13:59 GMT+06:00 mitchelloharawild <notifications@github.com>:

**Comment by mitchelloharawild** [comment]
This is an unrelated issue, consider hadley/devtools#877

**Comment by arodionoff** [comment]
Thanks your command,

When I can download last version of "forecast" without this error from CRAN
repository?

2017-02-21 16:26 GMT+06:00 Rob J Hyndman <notifications@github.com>:

**Comment by mitchelloharawild** [comment]
You can wait until version 8.0 is released on CRAN, or download it from GitHub using 
```R
# install.packages("devtools")
devtools::install_github("robjhyndman/forecast")
```

**Comment by arodionoff** [comment]
When will unify objects of different forecast classes. For example, lower,
upper in forecasts of stl, ets have time-series class, but 'tbats',
'bats' deprived
pleasure to join this family, leaving only the data-frame objects.

It would also be very nice to be able to call for models 'tbats',
'bats' function 'autoplot'.

2017-02-21 16:37 GMT+06:00 mitchelloharawild <notifications@github.com>:

**Comment by robjhyndman** [comment]
1. forecast.tbats does return ts objects named lower and upper. What is the problem?
2. I have added the lack of autoplot.bats/autoplot.tbats as a new issue.
