### ISSUE TITLE
autoplot.mforecast  error

### ISSUE THREAD

**Issue by robjhyndman** [robjhyndman/forecast#502]
MRE:
```r
carPower <- as.matrix(mtcars[,c("qsec","hp")])
carmpg <- mtcars[,"mpg"]
fit <- lm(carPower ~ carmpg)
fcast <- forecast(fit, newdata=data.frame(carmpg=30))
plot(fcast, xlab="Year")
autoplot(fcast, xlab=rep("Year",2))
```

**Comment by robjhyndman** [comment]
Any chance of getting this done tonight? I was hoping to submit to CRAN and spotted this on my last check through the examples output.

**Comment by mitchelloharawild** [comment]
Where'd the code come from? The error is from the transition from grid
aligned ggplot to facets. I'll look at it now.

**Comment by robjhyndman** [comment]
Code from `help(plot.mforecast)`
