### ISSUE TITLE
checkresiduals throws error when series contains missing values

### ISSUE THREAD

**Issue by mungojam** [robjhyndman/forecast#506]
When a series contains missing values, the checkresiduals function throws an error:

c(1, 5, 3, NA, 2, 5) %>% 
Arima(order=c(1,0,0)) %>% 
checkresiduals()

throws:
Error in na.omit.ts(x) : time series contains internal NAs

Other functions like residuals and (.$residuals %>% Acf) work fine which are two of the plots in checkresiduals

**Comment by robjhyndman** [comment]
Thanks. Fixed in https://github.com/robjhyndman/forecast/commit/0bf87dbb16c1ab6e3495135a11c8fb5296451017
