### ISSUE TITLE
Error using snaive with zoo objects

### ISSUE THREAD

**Issue by JocelynBarker** [robjhyndman/forecast#508]
I have discovered that I can no longer use the `snaive()` function with `zooreg` objects from the `zoo` package as I could in earlier version of the `forecast` package.  The package version I am using is 8.0, but I ran into the same problem with 7.3.  The error can be reproduced with the following code

`forecast::snaive(zoo::zooreg(1:50, frequency = 4))`

> Error in .cbind.ts(list(e1, e2), c(deparse(substitute(e1))[1L], deparse(substitute(e2))[1L]),  : 
>  not all series have the same frequency

The other `forecast` functions I have tried (`stlm`/`stlf`, `auto.arima`, `ets`) do not have this same problem.

After some quick sleuthing, I think the problem is in the `lagwalk` function.  Near the beginning are the lines:

`if (!is.ts(y)) 
    y <- ts(y)`

Since `ts` defaults to a frequency of 1, the start time and frequency is lost at this line of code.  If it were changed to 

`if (!is.ts(y)) 
    y <- as.ts(y)`

It should keep that information for the `zoo` objects and still work if the series is a simple numeric vector.

Thank you!

**Comment by robjhyndman** [comment]
The forecast package is not designed to work with zoo objects. Some functions may do so without error, but that is not the way the package is intended to be used. It is designed to use `ts` objects.
