### ISSUE TITLE
Simulate of ARIMA(0,1,0) model with drift and regressor

### ISSUE THREAD

**Issue by ymzhang-neo** [robjhyndman/forecast#511]
The function `simulate` seems not work for ARIMA(0,1,0) with drift and regressor.  Here is an example:
```R
# R version: 3.3.1
# forecast package version: 8.0
library(forecast)
set.seed(1)
ts.length <- 200
ts.fit <- Arima(rnorm(ts.length), order=c(0,1,0), xreg=rnorm(ts.length), include.drift=TRUE)
simulate(ts.fit, xreg=ts.fit$xreg, future=FALSE, bootstrap=TRUE)
```
The error message is given:
```
Error in as.matrix(xreg) %*% object$coef : non-conformable arguments
```
It seems the intercept has been considered in `simulate` but not the drift.  

Could you please check it?  Thank you!

**Comment by robjhyndman** [comment]
Thanks. Fixed in https://github.com/robjhyndman/forecast/commit/f14e4dd920b467fc2cb1a62546bdb8a990534f7e

**Comment by ymzhang-neo** [comment]
Thank you Dr. Hyndman!
