### ISSUE TITLE
Confidence levels for nnetar

### ISSUE THREAD

**Issue by ashawky84** [robjhyndman/forecast#512]
Hi 

I was wondering if it is possible to add confidence levels to the nnetar forecast. I try to add "forecast.nnetar(fit, h=36, level=c(80, 95))" but it doesn't seem to work.

Kind regards,

Ahmed Shawky

**Comment by gabrielcaceres** [comment]
I assume you mean prediction intervals?

You need to set `PI = TRUE`.

**Comment by ashawky84** [comment]
Thank you that works 👍
