### ISSUE TITLE
ggseasonplot() NULL x-axis if weekly data presented

### ISSUE THREAD

**Issue by fahadshery** [robjhyndman/forecast#514]
Looked at the code. The issue could be resolved by adding:

`else {
            labs <- NULL
            xLab <- "Season"
        }`

**_to:_**
`labs <- 1:frequency(x)
            xlab <- "Season"`

**Comment by robjhyndman** [comment]
Fixed in https://github.com/robjhyndman/forecast/commit/0349697b1d147f2775277ea47647b0057ae32285

**Comment by fahadshery** [comment]
Thank you for a prompt response
