### ISSUE TITLE
Zoo object with (gg)tsdisplay gives incorrect x axis

### ISSUE THREAD

**Issue by MikeOM** [robjhyndman/forecast#515]
ggtsdisplay Gives x-axis as 1-102 instead of 1899-2000.
zoo object made with line 
`zoo(data$Value, order.by= data$Year)`

Can be fixed in the ggplot file by changing 
`ts(x)` to `as.ts(x)` I think.

**Comment by robjhyndman** [comment]
The forecast package is not designed to handle zoo objects. The documentation makes this clear.
