### ISSUE TITLE
autoplot.mts problem

### ISSUE THREAD

**Issue by robjhyndman** [robjhyndman/forecast#516]
MRE
```
library(fpp2)
autoplot(calls)
```

**Comment by mitchelloharawild** [comment]
Why is `calls` mts? It's only got 1 column?
```R
autoplot.ts(fpp2::calls)
```

Added an exception.

**Comment by robjhyndman** [comment]
It is not `mts`:
```r
class(calls)
[1] "msts" "ts"  
```

**Comment by mitchelloharawild** [comment]
Oh, misread it when I checked the class.
In that case, I should fix it via autoplot.msts and autolayer.msts, I'll make another pull.
