### ISSUE TITLE
Strip matrix information in stl forecast methods

### ISSUE THREAD

**Issue by mitchelloharawild** [robjhyndman/forecast#519]
When importing data using read_csv, and then using a column from the tibble as data for a timeseries, `is.matrix` returns TRUE, leading to:

```r
fcast<-stlf(y)
Error in stl(x, s.window = s.window, t.window = t.window, robust = robust) : 
  only univariate series are allowed
```

Even when
```r
class(y)
[1] "ts"
```

This is more of an issue with how `stl` checks for univariate ts, but we can at least control our calls to `stl`.

**Comment by mitchelloharawild** [comment]
MRE:
```r
tibble(USAccDeaths) %>% ts %>% stlf
```

**Comment by robjhyndman** [comment]
Fixed in https://github.com/robjhyndman/forecast/commit/5c67bd67ae5b8668429c34f5d7f7a78a7c447bc6
