### ISSUE TITLE
Error in calculating the AMSE

### ISSUE THREAD

**Issue by BindiCGN** [robjhyndman/forecast#522]
Hello,

I (hopefully) discovered a mistake in calculating the AMSE.

The MSE_1 is calculated correctly, but the MSE_2 (and upwards) is always too small. I was able to recreate the error and it seems like the denominator for calculating the mean of the squared errors is always +1 too high.

Example: Let's say we got 10 observations and I want to calculate the MSE_2, therefore I calculate the 2-step ahead forecast for period 2 to 10. In order to get the MSE_2, I sum up the squared errors and divide them by 9. Your software is currently dividing by 10.

Best regards

**Comment by robjhyndman** [comment]
Which function are you referring to?

**Comment by BindiCGN** [comment]
I'll just paste some code to clarify the issue:

y <- c(115,90,65,135,130,95,75,150,135,105,85,155,145,110,85,160)
y <- ts(y, frequency = 4)
fit <- ets(model="AAA", y, nmse=1)
fit$amse *(or fit$mse) is = 6.986899, which is correct*
fit <- ets(model="AAA", y, nmse=2)
fit$amse *is = 6.838385, which is supposedly incorrect*

The last row implicates that the MSE_2 must be = 6.69. But this is incorrect. According to my calculations, the sum of squared errors for the 2-step ahead forecast is = 107.03. If you divide that by the amount of observations for the 2-step ahead forecast (15), you get MSE_2 = 7.14 and consequently the AMSE = 7.06. However, if you falsely divide by 16 (the total amount of periods), you get MSE_2 = 6.69, the number mentioned earlier.

**Comment by robjhyndman** [comment]
Thanks. You're right. Fixed in https://github.com/robjhyndman/forecast/commit/237647bfcda99b9df5dedda917ba8cfc50f39cd5
