### ISSUE TITLE
hfitted error

### ISSUE THREAD

**Issue by robjhyndman** [robjhyndman/forecast#525]
```r
library(forecast)
y <- c(115,90,65,135,130,95,75,150,135,105,85,155,145,110,85,160)
y <- ts(y)
fit <- ets(y, model="ANN")
fit$state[,"l"]
fitted(fit, h=1)
fitted(fit, h=2)
```

**Comment by mitchelloharawild** [comment]
Is it unreasonable to set the use.initial.par option to TRUE when a refit
model is specified inside ets? If not, perhaps a warning / message if the
option is left as default?

**Comment by robjhyndman** [comment]
I've added a message.

**Comment by mitchelloharawild** [comment]
Message looks good.
I was more so thinking of also checking if missing(option) is true. That
way the message doesn't show if the user specifies option=FALSE

**Comment by robjhyndman** [comment]
Sure. Feel free to add that.

**Comment by mitchelloharawild** [comment]
The issue with the extra NA seems to be coming from how the initial values are used for the first fitted value... Which is kind of like fitting the model without any data (having seen/optimised over future data).

The hfitted function starts with 1 observation, however it should maybe start from 0 observations... However this would require all of the refit functions to allow for NULL data input, as ts(NULL) is not defined.

If I'm not mistaken, for the ETS above, the 2 step fitted value should be equivalent to the 1 step, even for the first fitted value?

**Comment by robjhyndman** [comment]
OK, that makes sense. I think it would be complicated to make all the refit functions have NULL data. So let's leave it.

**Comment by mitchelloharawild** [comment]
Is this issue resolved? Or should we try to extend refitting to allow for the first fit being the initial level?

**Comment by robjhyndman** [comment]
I think we should just leave it. I'll close the issue.
