### ISSUE TITLE
fortify produces duplicated x values

### ISSUE THREAD

**Issue by ggrothendieck** [robjhyndman/forecast#528]
This should have any duplicates:

```
library(forecast)

tt <- ts(c(123.22, 123.22, 123.22, 56.288), start = 2015, freq = 12)
ff <- forecast(tt)
anyDuplicated(fortify(ff)$x)
## [1] 25
```

**Comment by mitchelloharawild** [comment]
`fortify.forecast` is no longer an exported object as of forecast version 8.1.
I don't see what the issue is here.

Are you using the latest version?

**Comment by ggrothendieck** [comment]
Seems not. Sorry.
