### ISSUE TITLE
Forecasting in mlr

### ISSUE THREAD

**Issue by Stevo15025** [robjhyndman/forecast#530]
Hello! This is just a note so feel free to close at your leisure.

The purpose of my master's thesis is to take the tuning and training methodologies of the R package `mlr` and extent them to allow for forecasting models. Combining forecasting and machine learning methedologies allows for things like tuning the hyper-parameters of `forecast`'s `ets()` function using `mlrMBO` over growing or fixed windows.

It is quite a large project that is starting the final steps of integration into `mlr`

You can see the forecasting base functions PR for `mlr` [here](https://github.com/mlr-org/mlr/pull/1702)
- Base functions include an Arima learner, growing and fixed window resampling, a MASE measure, and a forecast regression task

An idea of the overall package extension PR can be found [here](https://github.com/mlr-org/mlr/pull/1318)
- This has quite a few forecasting models, the garch models from `rugarch`, multivariate forecasting, updating models with new data, and an experimental way to make arbitrary AR(p,d) machine learning models. Also at the top of this PR is a slightly outdated tutorial that can give you an idea of how the package works.

I know how incredibly busy you all are with your own work, but if you would have any time to investigate the forecasting base branch I could not thank you enough! The `mlr` team's background focuses on machine learning, so while a lot of concepts carry over I worry that something can slip through the gaps in our two fields.

Thank you for your time!

**Comment by robjhyndman** [comment]
Nice to see this happening, but I really can't give it any time myself. I'm already stretched way too far.
