### ISSUE TITLE
Add accuracy function for 'baggedETS' forecast objects

### ISSUE THREAD

**Issue by arodionoff** [robjhyndman/forecast#531]
Could you add to **accuracy** function the ability to work correctly with 'baggedETS' forecast objects. Now it runs 'Error in NextMethod(.Generic) : cannot assign 'tsp' to zero-length vector'.

**Comment by tiagomendesdantas** [comment]
Any news on this issue? Thanks!

**Comment by cbergmeir** [comment]
Sorry, must have overlooked this one...so no, no news at the moment, but I'll put it on my TODO list.
