### ISSUE TITLE
fitted values in ses output incorrect order

### ISSUE THREAD

**Issue by archapin** [robjhyndman/forecast#533]
I was using the following code  for the book "Forecasting: principles and practice", from section 7.1:

```
> fit1 = ses(oildata, alpha=0.2, initial="simple", h=3)
> data.frame(observed_values = fit1$x, fitted_values = fit1$fitted)

    observed_values fitted_values
1         446.6565      446.6565
2         454.4733      446.6565
3         455.6630      448.2199
4         423.6322      449.7085
5         456.2713      444.4932
6         440.5881      446.8489
7         425.3325      445.5967
8         485.1494      441.5439
9         506.0482      450.2650
10        526.7920      461.4216
11        514.2689      474.4957
12        494.2110      482.4503

```

The first two values in the fitted_values column are repeated, as if the initial state might have been used as part of the fitted output.  And comparing to the table 7.2 from the book, fitted values are lagged by one in position, so there is a missing fitted value.

Forecast values and accuray values seem to work fine comparing again with table 7.2.

```
> fit1$mean
Time Series:
Start = 2008 
End = 2010 
Frequency = 1 
[1] 484.8025 484.8025 484.8025
> accuracy(fit1)
                   ME    RMSE      MAE      MPE     MAPE     MASE      ACF1
Training set 15.89414 32.1348 24.66102 3.010684 5.067472 1.136664 0.5102479

> fit1$model$SSE
[1] 12391.75
```

**Comment by robjhyndman** [comment]
When `initial=simple` the value of $\ell_0$ is set to the first observation. Then $\ell_1$ is a linear combination of $\ell_0$ and the first observation which, of course, gives the first observation.
The fitted values are not lagged. Row 1 of your data frame is time 0.
