### ISSUE TITLE
Remove autolayer S3 generic

### ISSUE THREAD

**Issue by mitchelloharawild** [robjhyndman/forecast#542]
Looks like it has been released in ggplot2 2.2.1.9000.

https://github.com/tidyverse/ggplot2/blob/master/NEWS.md

Is this ready to remove now? @robjhyndman

**Comment by robjhyndman** [comment]
Yes. Just make sure you add the dependency version in the DESCRIPTION.

**Comment by robjhyndman** [comment]
I don't think it is on CRAN yet. So perhaps wait until it is.

**Comment by mitchelloharawild** [comment]
You're correct. Time to wait :+1:
