### ISSUE TITLE
Write package?forecast documentation

### ISSUE THREAD

**Issue by mitchelloharawild** [robjhyndman/forecast#543]
```r
package?forecast
Error in (function (e1, e2)  : 
  no documentation of type ‘package’ and topic ‘forecast’ (or error in processing help)
```

This should also document
```r
help(package="forecast")
```

**Comment by mitchelloharawild** [comment]
@robjhyndman, Is this documented in `forecast-package`?

Perhaps a link to FPP for getting started would be useful here.

![image](https://cloud.githubusercontent.com/assets/16127127/25836589/79705492-34cb-11e7-8bf5-761f5fb81e55.png)

**Comment by robjhyndman** [comment]
`package?forecast` works for me.

Yes, a link to `fpp` might be helpful.

**Comment by mitchelloharawild** [comment]
Hmm, so it does (at least on the built version).
I guess devtools::load_all doesn't set that up properly.
