### ISSUE TITLE
Argument is of length zero in ses

### ISSUE THREAD

**Issue by antaldaniel** [robjhyndman/forecast#550]
The following code:
```r
xts_df = xts (x = c("102175549024", "583748571792", "31889963227", "368884167541"), 
      order.by = as.POSIXct (c("2010-12-31", "2011-12-31", "2012-12-31", "2013-12-31"))
)
forecast::ses(xts_df,h = 1)
```
gives this error message:
>Error in if (is.na(lastseason)) lastseason <- ifelse(seasonal == "additive",  : 
 > argument is of length zero

Is this ifelse statement well-formatted?

**Comment by mitchelloharawild** [comment]
The ifelse statement is fine.
```r
is.na(lastseason))
	lastseason <- ifelse(seasonal=="additive",0,1)
```

xts objects are not supported, instead use ts objects.
