### ISSUE TITLE
could not find function "lpb" in taperedacf()

### ISSUE THREAD

**Issue by chcatano** [robjhyndman/forecast#552]
Hello, I am trying to get 95% CIs on estimates of autocorrelation at lag-1. I believe I can do this using the taperedacf() function, but when I run it on my time series I get the following error:

taperedacf(ts, lag.max = 1, plot = F, calc.ci = TRUE, level = 95, nsim = 1000)

Error in taperedacf(ts, lag.max = 1, plot = F, calc.ci = TRUE, level = 95,  : 
  could not find function "lpb"

I'm not familiar with this function, nor could find documentation for it. Any help would be appreciated.

Thanks,
Chris

**Comment by robjhyndman** [comment]
Apparently, you are trying to run the code without using the forecast package. The following works.
```r
library(forecast)
taperedacf(WWWusage)
help(taperedacf)
```
