### ISSUE TITLE
accuracy() does not validate length of the vectors and returns incorrect results 

### ISSUE THREAD

**Issue by twolodzko** [robjhyndman/forecast#561]
One could assume that true mean is a pretty good and consistent forecast for a large dataset

`accuracy(0.5, runif(1e6))`

However the function above returns very instable results. This is because `forecast:::testaccuracy` uses the following line of code

`error <- (xx - ff[1:n])[test]`

that returns NULL's for nonexistent datapoints, e.g.

```
> (0.5)[1:10]
 [1] 0.5  NA  NA  NA  NA  NA  NA  NA  NA  NA
```

Instead it should either

1. use `ff <- rep(f, length.out = n)`,
2. and/or check if `length(f) == length(x)` and otherwise throw error.

The above example is simplified, but one may imagine situation when by mistake the two vectors differ in length and nonetheless, `accuracy()` returns *some* result, that is wrong. On another case, comparing to single value "benchmark" forecast should be possible since this is consistent with many of other R's vectorized operations that "expand" shorter vectors (e.g. ` 0:1 * 1:10`).

**Comment by robjhyndman** [comment]
I've made it an error instead. I think that is safer. See https://github.com/robjhyndman/forecast/commit/4bc400b828d7d402c38e8f5d68c21f4966677404
