### ISSUE TITLE
Prediction intervals for nnetar model

### ISSUE THREAD

**Issue by FedericoBotta** [robjhyndman/forecast#563]
Hello,

I am running the code underneath to train a nnetar model with an external rergressor. When I try to get prediction intervals using the forecast function, the intervals do not contain the estimate.

Interestingly, if I simulate the prediction intervals myself using the simulate() function, I obtain perfectly fine intervals.

I'm putting here the most simple case in which I have observed this, but I have had this issue with a few time series of different lengths.

--------------
StartDate <- as.Date("2014-05-01","%Y-%m-%d")
EndDate <- as.Date("2017-04-01","%Y-%m-%d")
Data <- data.frame(Values=c(613354,501885,595019,686413,445973,473991,377363,367044,341653,380208,401531,421822,484772,388272,475441,444771,321903,375924,337615,338669,361563,287057,349639,305386,297165,604476,811162,704548,544742,691066,436004,455709,449905,506428,596594,673153))

Timeseries <- ts(Data,start=c(year(StartDate),month(StartDate)),end=c(year(EndDate),month(EndDate)),frequency=12)

ExternalData <- data.frame(Values=c(29,24,26,31,24,25,22,22,23,24,21,20,20,18,19,20,20,23,20,20,22,22,22,18,19,35,35,31,32,34,25,25,26,33,28,28))

Model <- nnetar(Timeseries, xreg = ExternalData, decay = 0.1)
fcst <- forecast(Model, xreg = 30, PI = T)

--------------

This gives a forecasted value of 578,495.5, and a 95% prediction interval [171,504.7; 354,993.7].

Many thanks!

**Comment by robjhyndman** [comment]
Fixed in https://github.com/robjhyndman/forecast/commit/b64f9d5df73cf906b144158c37f03aff298f7467
