### ISSUE TITLE
Getting Error installing forecast

### ISSUE THREAD

**Issue by garivaldo** [robjhyndman/forecast#564]
R version 3.4.0 (2017-04-21) -- "You Stupid Darkness"
Copyright (C) 2017 The R Foundation for Statistical Computing
Platform: x86_64-redhat-linux-gnu (64-bit)

---------------------------
install.packages("forecast")
Installing package into ‘/usr/lib64/R/library’
(as ‘lib’ is unspecified)
trying URL 'http://cran.rstudio.com/src/contrib/forecast_8.1.tar.gz'
Content type 'application/x-gzip' length 783567 bytes (765 KB)
==================================================
downloaded 765 KB

* installing *source* package ‘forecast’ ...
** package ‘forecast’ successfully unpacked and MD5 sums checked
** libs
g++ -m64  -I/usr/include/R -DNDEBUG  -I"/usr/lib64/R/library/Rcpp/include" -I"/usr/lib64/R/library/RcppArmadillo/include" -I/usr/local/include   -fpic  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches   -m64 -mtune=generic  -c calcBATS.cpp -o calcBATS.o
calcBATS.cpp: In function ‘SEXPREC* calcBATSFaster(SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP)’:
calcBATS.cpp:58:10: warning: ‘lengthSeasonal’ may be used uninitialized in this function [-Wmaybe-uninitialized]
  R_len_t lengthSeasonal;
          ^
calcBATS.cpp:57:53: warning: ‘sPeriods’ may be used uninitialized in this function [-Wmaybe-uninitialized]
  int adjBeta, previousS, lengthArma, *tau, *p, *q, *sPeriods;
                                                     ^
g++ -m64  -I/usr/include/R -DNDEBUG  -I"/usr/lib64/R/library/Rcpp/include" -I"/usr/lib64/R/library/RcppArmadillo/include" -I/usr/local/include   -fpic  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches   -m64 -mtune=generic  -c calcTBATS.cpp -o calcTBATS.o
g++ -m64  -I/usr/include/R -DNDEBUG  -I"/usr/lib64/R/library/Rcpp/include" -I"/usr/lib64/R/library/RcppArmadillo/include" -I/usr/local/include   -fpic  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches   -m64 -mtune=generic  -c etsTargetFunction.cpp -o etsTargetFunction.o
etsTargetFunction.cpp: In member function ‘void EtsTargetFunction::eval(const double*, int)’:
etsTargetFunction.cpp:87:36: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
  if(p_par_length != this->par.size()) {
                                    ^
etsTargetFunction.cpp:119:44: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
  for(int i=par.size()-nstate; i < par.size(); i++) {
                                            ^
etsTargetFunction.cpp:147:33: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   for(int i=start; i<state.size(); i++) {
                                 ^
etsTargetFunction.cpp:163:35: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
  for(int i=0; i <= p*this->y.size(); i++) state.push_back(0);
                                   ^
etsTargetFunction.cpp: In member function ‘bool EtsTargetFunction::admissible()’:
etsTargetFunction.cpp:302:28: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   for(int i=0;i<zeror.size();i++) {
                            ^
g++ -m64  -I/usr/include/R -DNDEBUG  -I"/usr/lib64/R/library/Rcpp/include" -I"/usr/lib64/R/library/RcppArmadillo/include" -I/usr/local/include   -fpic  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches   -m64 -mtune=generic  -c etsTargetFunctionWrapper.cpp -o etsTargetFunctionWrapper.o
gcc -m64 -std=gnu99 -I/usr/include/R -DNDEBUG  -I"/usr/lib64/R/library/Rcpp/include" -I"/usr/lib64/R/library/RcppArmadillo/include" -I/usr/local/include   -fpic  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches   -m64 -mtune=generic  -c etscalc.c -o etscalc.o
etscalc.c: In function ‘etssimulate’:
etscalc.c:119:15: warning: variable ‘nstates’ set but not used [-Wunused-but-set-variable]
     int i, j, nstates;
               ^
gcc -m64 -std=gnu99 -I/usr/include/R -DNDEBUG  -I"/usr/lib64/R/library/Rcpp/include" -I"/usr/lib64/R/library/RcppArmadillo/include" -I/usr/local/include   -fpic  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches   -m64 -mtune=generic  -c etspolyroot.c -o etspolyroot.o
g++ -m64  -I/usr/include/R -DNDEBUG  -I"/usr/lib64/R/library/Rcpp/include" -I"/usr/lib64/R/library/RcppArmadillo/include" -I/usr/local/include   -fpic  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches   -m64 -mtune=generic  -c makeBATSMatrices.cpp -o makeBATSMatrices.o
makeBATSMatrices.cpp: In function ‘SEXPREC* makeBATSWMatrix(SEXP, SEXP, SEXP, SEXP)’:
makeBATSMatrices.cpp:7:31: warning: ‘maCoefs’ may be used uninitialized in this function [-Wmaybe-uninitialized]
  double *smallPhi, *arCoefs, *maCoefs;
                               ^
makeBATSMatrices.cpp:7:21: warning: ‘arCoefs’ may be used uninitialized in this function [-Wmaybe-uninitialized]
  double *smallPhi, *arCoefs, *maCoefs;
                     ^
makeBATSMatrices.cpp:8:7: warning: ‘seasonalPeriods’ may be used uninitialized in this function [-Wmaybe-uninitialized]
  int *seasonalPeriods;
       ^
makeBATSMatrices.cpp:63:30: warning: ‘smallPhi’ may be used uninitialized in this function [-Wmaybe-uninitialized]
   wTranspose(0,1) = *smallPhi;
                              ^
makeBATSMatrices.cpp: In function ‘SEXPREC* makeBATSGMatrix(SEXP, SEXP, SEXP, SEXP, SEXP, SEXP)’:
makeBATSMatrices.cpp:146:44: warning: ‘seasonalPeriods’ may be used uninitialized in this function [-Wmaybe-uninitialized]
     position = position + seasonalPeriods[s];
                                            ^
makeBATSMatrices.cpp:147:48: warning: ‘gammaVector’ may be used uninitialized in this function [-Wmaybe-uninitialized]
     gTranspose(0, position) = gammaVector[(s+1)];
                                                ^
g++ -m64  -I/usr/include/R -DNDEBUG  -I"/usr/lib64/R/library/Rcpp/include" -I"/usr/lib64/R/library/RcppArmadillo/include" -I/usr/local/include   -fpic  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches   -m64 -mtune=generic  -c makeTBATSMatrices.cpp -o makeTBATSMatrices.o
makeTBATSMatrices.cpp: In function ‘SEXPREC* makeTBATSWMatrix(SEXP, SEXP, SEXP, SEXP, SEXP)’:
makeTBATSMatrices.cpp:7:31: warning: ‘maCoefs’ may be used uninitialized in this function [-Wmaybe-uninitialized]
  double *smallPhi, *arCoefs, *maCoefs;
                               ^
makeTBATSMatrices.cpp:7:21: warning: ‘arCoefs’ may be used uninitialized in this function [-Wmaybe-uninitialized]
  double *smallPhi, *arCoefs, *maCoefs;
                     ^
makeTBATSMatrices.cpp:64:28: warning: ‘tau’ may be used uninitialized in this function [-Wmaybe-uninitialized]
    wTranspose(0,(adjustPhi + *tau +i)) = arCoefs[(i-1)];
                            ^
makeTBATSMatrices.cpp:44:57: warning: ‘kVector’ may be used uninitialized in this function [-Wmaybe-uninitialized]
     for(int j = (position+1); j <= (position + kVector[s]); j++) {
                                                         ^
makeTBATSMatrices.cpp:58:30: warning: ‘smallPhi’ may be used uninitialized in this function [-Wmaybe-uninitialized]
   wTranspose(0,1) = *smallPhi;
                              ^
gcc -m64 -std=gnu99 -I/usr/include/R -DNDEBUG  -I"/usr/lib64/R/library/Rcpp/include" -I"/usr/lib64/R/library/RcppArmadillo/include" -I/usr/local/include   -fpic  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches   -m64 -mtune=generic  -c registerDynamicSymbol.c -o registerDynamicSymbol.o
g++ -m64  -I/usr/include/R -DNDEBUG  -I"/usr/lib64/R/library/Rcpp/include" -I"/usr/lib64/R/library/RcppArmadillo/include" -I/usr/local/include   -fpic  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches   -m64 -mtune=generic  -c updateMatrices.cpp -o updateMatrices.o
updateMatrices.cpp: In function ‘SEXPREC* updateFMatrix(SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP)’:
updateMatrices.cpp:81:72: warning: ‘beta’ may be used uninitialized in this function [-Wmaybe-uninitialized]
    F.submat(1,(betaAdjust+ *tau+p+1),1,(betaAdjust+ *tau+p+q)) = *beta * ma;
                                                                        ^
g++ -m64  -I/usr/include/R -DNDEBUG  -I"/usr/lib64/R/library/Rcpp/include" -I"/usr/lib64/R/library/RcppArmadillo/include" -I/usr/local/include   -fpic  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches   -m64 -mtune=generic  -c updateTBATSMatrices.cpp -o updateTBATSMatrices.o
updateTBATSMatrices.cpp: In function ‘SEXPREC* updateTBATSGMatrix(SEXP, SEXP, SEXP, SEXP)’:
updateTBATSMatrices.cpp:38:10: warning: unused variable ‘gammaVector’ [-Wunused-variable]
  double *gammaVector;
          ^
g++ -m64 -shared -L/usr/lib64/R/lib -Wl,-z,relro -o forecast.so calcBATS.o calcTBATS.o etsTargetFunction.o etsTargetFunctionWrapper.o etscalc.o etspolyroot.o makeBATSMatrices.o makeTBATSMatrices.o registerDynamicSymbol.o updateMatrices.o updateTBATSMatrices.o -L/usr/lib64/R/lib -lRlapack -L/usr/lib64/R/lib -lRblas -lgfortran -lm -lquadmath -L/usr/lib64/R/lib -lR
installing to /usr/lib64/R/library/forecast/libs
** R
** data
*** moving datasets to lazyload DB
** inst
** byte-compile and prepare package for lazy loading
Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  object 'vI' not found
ERROR: lazy loading failed for package ‘forecast’
* removing ‘/usr/lib64/R/library/forecast’
* restoring previous ‘/usr/lib64/R/library/forecast’
Warning in install.packages :
  installation of package ‘forecast’ had non-zero exit status

The downloaded source packages are in
	‘/tmp/RtmpwSd8mY/downloaded_packages’

**Comment by robjhyndman** [comment]
This is probably due to you not having the required dependencies, or using packages created under different versions of R. Please use Rstudio to install the package and make sure you "install dependencies" is checked.

**Comment by garivaldo** [comment]
Hi,

I am using Rstudio and I still ran into the problem with dependencies=TRUE flag. I also removed the previous forecast package (8.0) and I'm still getting the error. 

![image](https://user-images.githubusercontent.com/5017815/27434218-f913cc8e-5725-11e7-9e0d-4c33217af778.png)


> install.packages("forecast", dependencies = TRUE)
Installing package into ‘/usr/lib64/R/library’
(as ‘lib’ is unspecified)
also installing the dependency ‘expsmooth’

trying URL 'http://cran.rstudio.com/src/contrib/expsmooth_2.3.tar.gz'
Content type 'application/x-gzip' length 245921 bytes (240 KB)
==================================================
downloaded 240 KB

trying URL 'http://cran.rstudio.com/src/contrib/forecast_8.1.tar.gz'
Content type 'application/x-gzip' length 783567 bytes (765 KB)
==================================================
downloaded 765 KB

* installing *source* package ‘forecast’ ...
** package ‘forecast’ successfully unpacked and MD5 sums checked
** libs
g++ -m64  -I/usr/include/R -DNDEBUG  -I"/usr/lib64/R/library/Rcpp/include" -I"/usr/lib64/R/library/RcppArmadillo/include" -I/usr/local/include   -fpic  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches   -m64 -mtune=generic  -c calcBATS.cpp -o calcBATS.o
calcBATS.cpp: In function ‘SEXPREC* calcBATSFaster(SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP)’:
calcBATS.cpp:58:10: warning: ‘lengthSeasonal’ may be used uninitialized in this function [-Wmaybe-uninitialized]
  R_len_t lengthSeasonal;
          ^
calcBATS.cpp:57:53: warning: ‘sPeriods’ may be used uninitialized in this function [-Wmaybe-uninitialized]
  int adjBeta, previousS, lengthArma, *tau, *p, *q, *sPeriods;
                                                     ^
g++ -m64  -I/usr/include/R -DNDEBUG  -I"/usr/lib64/R/library/Rcpp/include" -I"/usr/lib64/R/library/RcppArmadillo/include" -I/usr/local/include   -fpic  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches   -m64 -mtune=generic  -c calcTBATS.cpp -o calcTBATS.o
g++ -m64  -I/usr/include/R -DNDEBUG  -I"/usr/lib64/R/library/Rcpp/include" -I"/usr/lib64/R/library/RcppArmadillo/include" -I/usr/local/include   -fpic  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches   -m64 -mtune=generic  -c etsTargetFunction.cpp -o etsTargetFunction.o
etsTargetFunction.cpp: In member function ‘void EtsTargetFunction::eval(const double*, int)’:
etsTargetFunction.cpp:87:36: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
  if(p_par_length != this->par.size()) {
                                    ^
etsTargetFunction.cpp:119:44: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
  for(int i=par.size()-nstate; i < par.size(); i++) {
                                            ^
etsTargetFunction.cpp:147:33: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   for(int i=start; i<state.size(); i++) {
                                 ^
etsTargetFunction.cpp:163:35: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
  for(int i=0; i <= p*this->y.size(); i++) state.push_back(0);
                                   ^
etsTargetFunction.cpp: In member function ‘bool EtsTargetFunction::admissible()’:
etsTargetFunction.cpp:302:28: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   for(int i=0;i<zeror.size();i++) {
                            ^
g++ -m64  -I/usr/include/R -DNDEBUG  -I"/usr/lib64/R/library/Rcpp/include" -I"/usr/lib64/R/library/RcppArmadillo/include" -I/usr/local/include   -fpic  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches   -m64 -mtune=generic  -c etsTargetFunctionWrapper.cpp -o etsTargetFunctionWrapper.o
gcc -m64 -std=gnu99 -I/usr/include/R -DNDEBUG  -I"/usr/lib64/R/library/Rcpp/include" -I"/usr/lib64/R/library/RcppArmadillo/include" -I/usr/local/include   -fpic  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches   -m64 -mtune=generic  -c etscalc.c -o etscalc.o
etscalc.c: In function ‘etssimulate’:
etscalc.c:119:15: warning: variable ‘nstates’ set but not used [-Wunused-but-set-variable]
     int i, j, nstates;
               ^
gcc -m64 -std=gnu99 -I/usr/include/R -DNDEBUG  -I"/usr/lib64/R/library/Rcpp/include" -I"/usr/lib64/R/library/RcppArmadillo/include" -I/usr/local/include   -fpic  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches   -m64 -mtune=generic  -c etspolyroot.c -o etspolyroot.o
g++ -m64  -I/usr/include/R -DNDEBUG  -I"/usr/lib64/R/library/Rcpp/include" -I"/usr/lib64/R/library/RcppArmadillo/include" -I/usr/local/include   -fpic  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches   -m64 -mtune=generic  -c makeBATSMatrices.cpp -o makeBATSMatrices.o
makeBATSMatrices.cpp: In function ‘SEXPREC* makeBATSWMatrix(SEXP, SEXP, SEXP, SEXP)’:
makeBATSMatrices.cpp:7:31: warning: ‘maCoefs’ may be used uninitialized in this function [-Wmaybe-uninitialized]
  double *smallPhi, *arCoefs, *maCoefs;
                               ^
makeBATSMatrices.cpp:7:21: warning: ‘arCoefs’ may be used uninitialized in this function [-Wmaybe-uninitialized]
  double *smallPhi, *arCoefs, *maCoefs;
                     ^
makeBATSMatrices.cpp:8:7: warning: ‘seasonalPeriods’ may be used uninitialized in this function [-Wmaybe-uninitialized]
  int *seasonalPeriods;
       ^
makeBATSMatrices.cpp:63:30: warning: ‘smallPhi’ may be used uninitialized in this function [-Wmaybe-uninitialized]
   wTranspose(0,1) = *smallPhi;
                              ^
makeBATSMatrices.cpp: In function ‘SEXPREC* makeBATSGMatrix(SEXP, SEXP, SEXP, SEXP, SEXP, SEXP)’:
makeBATSMatrices.cpp:146:44: warning: ‘seasonalPeriods’ may be used uninitialized in this function [-Wmaybe-uninitialized]
     position = position + seasonalPeriods[s];
                                            ^
makeBATSMatrices.cpp:147:48: warning: ‘gammaVector’ may be used uninitialized in this function [-Wmaybe-uninitialized]
     gTranspose(0, position) = gammaVector[(s+1)];
                                                ^
g++ -m64  -I/usr/include/R -DNDEBUG  -I"/usr/lib64/R/library/Rcpp/include" -I"/usr/lib64/R/library/RcppArmadillo/include" -I/usr/local/include   -fpic  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches   -m64 -mtune=generic  -c makeTBATSMatrices.cpp -o makeTBATSMatrices.o
makeTBATSMatrices.cpp: In function ‘SEXPREC* makeTBATSWMatrix(SEXP, SEXP, SEXP, SEXP, SEXP)’:
makeTBATSMatrices.cpp:7:31: warning: ‘maCoefs’ may be used uninitialized in this function [-Wmaybe-uninitialized]
  double *smallPhi, *arCoefs, *maCoefs;
                               ^
makeTBATSMatrices.cpp:7:21: warning: ‘arCoefs’ may be used uninitialized in this function [-Wmaybe-uninitialized]
  double *smallPhi, *arCoefs, *maCoefs;
                     ^
makeTBATSMatrices.cpp:64:28: warning: ‘tau’ may be used uninitialized in this function [-Wmaybe-uninitialized]
    wTranspose(0,(adjustPhi + *tau +i)) = arCoefs[(i-1)];
                            ^
makeTBATSMatrices.cpp:44:57: warning: ‘kVector’ may be used uninitialized in this function [-Wmaybe-uninitialized]
     for(int j = (position+1); j <= (position + kVector[s]); j++) {
                                                         ^
makeTBATSMatrices.cpp:58:30: warning: ‘smallPhi’ may be used uninitialized in this function [-Wmaybe-uninitialized]
   wTranspose(0,1) = *smallPhi;
                              ^
gcc -m64 -std=gnu99 -I/usr/include/R -DNDEBUG  -I"/usr/lib64/R/library/Rcpp/include" -I"/usr/lib64/R/library/RcppArmadillo/include" -I/usr/local/include   -fpic  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches   -m64 -mtune=generic  -c registerDynamicSymbol.c -o registerDynamicSymbol.o
g++ -m64  -I/usr/include/R -DNDEBUG  -I"/usr/lib64/R/library/Rcpp/include" -I"/usr/lib64/R/library/RcppArmadillo/include" -I/usr/local/include   -fpic  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches   -m64 -mtune=generic  -c updateMatrices.cpp -o updateMatrices.o
updateMatrices.cpp: In function ‘SEXPREC* updateFMatrix(SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP)’:
updateMatrices.cpp:81:72: warning: ‘beta’ may be used uninitialized in this function [-Wmaybe-uninitialized]
    F.submat(1,(betaAdjust+ *tau+p+1),1,(betaAdjust+ *tau+p+q)) = *beta * ma;
                                                                        ^
g++ -m64  -I/usr/include/R -DNDEBUG  -I"/usr/lib64/R/library/Rcpp/include" -I"/usr/lib64/R/library/RcppArmadillo/include" -I/usr/local/include   -fpic  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches   -m64 -mtune=generic  -c updateTBATSMatrices.cpp -o updateTBATSMatrices.o
updateTBATSMatrices.cpp: In function ‘SEXPREC* updateTBATSGMatrix(SEXP, SEXP, SEXP, SEXP)’:
updateTBATSMatrices.cpp:38:10: warning: unused variable ‘gammaVector’ [-Wunused-variable]
  double *gammaVector;
          ^
g++ -m64 -shared -L/usr/lib64/R/lib -Wl,-z,relro -o forecast.so calcBATS.o calcTBATS.o etsTargetFunction.o etsTargetFunctionWrapper.o etscalc.o etspolyroot.o makeBATSMatrices.o makeTBATSMatrices.o registerDynamicSymbol.o updateMatrices.o updateTBATSMatrices.o -L/usr/lib64/R/lib -lRlapack -L/usr/lib64/R/lib -lRblas -lgfortran -lm -lquadmath -L/usr/lib64/R/lib -lR
installing to /usr/lib64/R/library/forecast/libs
** R
** data
*** moving datasets to lazyload DB
** inst
** byte-compile and prepare package for lazy loading
Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  object 'vI' not found
ERROR: lazy loading failed for package ‘forecast’
* removing ‘/usr/lib64/R/library/forecast’
Warning in install.packages :
  installation of package ‘forecast’ had non-zero exit status
ERROR: dependency ‘forecast’ is not available for package ‘expsmooth’
* removing ‘/usr/lib64/R/library/expsmooth’
Warning in install.packages :
  installation of package ‘expsmooth’ had non-zero exit status

The downloaded source packages are in
	‘/tmp/RtmpTymXaI/downloaded_packages’
>

**Comment by garivaldo** [comment]
I had to update my Rjava package and then installing forecast worked.
