### ISSUE TITLE
error occurs while using "forecast.HoltWinters" 

### ISSUE THREAD

**Issue by JohnBuqing** [robjhyndman/forecast#566]
I installed forecast from CRAN. but when I use it in RStudio ,it goes like 
> library("forecast")
> souvenirtimeseriesforecasts2 <- forecast.HoltWinters(souvenirtimeseriesforecasts, h=48)
Error in forecast.HoltWinters(souvenirtimeseriesforecasts, h = 48) : 
  没有"forecast.HoltWinters"这个函数

last sentence(In Chinese) means  forecast.HoltWinters doesn't exist.

**Comment by robjhyndman** [comment]
Use forecast() not forecast.HoltWinters().
