### ISSUE TITLE
Question About OCSB Test

### ISSUE THREAD

**Issue by davidreilly007** [robjhyndman/forecast#569]
In the OCSB test, you first do some manual differencing, but then when you call the Arima function you leave the default include.mean = TRUE, resulting in 7 terms for the first model.

Should the include.mean = FALSE here?

I did test this by tweaking the OCSB test and rerunning M3. Out of 2184 Seasonal Data Sets, 39 changed D from 0 to 1, 55 changed D from 1 to 0, so empirically probably best to leave as is.

**Comment by olehjktu** [comment]
The Econometric Analysis of Seasonal Time Series Ghysels and  Osborn , p. 66, says:
An interpretation of the OCSB test, therefore, is that it
tests seasonal integration in a process that has been first differenced. 
Hence, it is very doubtful on the theoretic grounds to apply
this test to I(0) series. It looks like I(0) series should be cumulated
before inserting them into forecast::.OCSBtest
Oleh
jktu is oleg at cyrillic keyboard

**Comment by mitchelloharawild** [comment]
I've done a re-write of this test in 7a9de0ed08d005e5098781734b59515bd0d8a867 which should resolve this issue.

**Comment by olehjktu** [comment]
Dear "mitchelloharawild" ,

The script is fairly long, context search gave 37 occurenses
of "ocsb" so I can mistake
I have impression you committed just the opposite I proposed:
y <- diff(diff(x, period))
The null in OCSB test is y is I(1)
let
(1-L)P(L)y = Q(L)\vareps
then
exactly
diff(y)P(L)y = Q(L)\vareps
When y is I(0) diff(y) have no more
a nice representation: we have just introduced
a unit root in the MA part: 


Moreover, arima(y, p d q; P D Q)
is the same as arima(diff(y), p (d-1) q; P D Q)
The difference emerges only if we go forecasting:
we will forecast either y or diff(y)


We see that for I(1) differencing does not affect MA/SMA/SAR
polynomyals
This means y and diff(y) have the same seasonal properties
This means seasonal testing of y and diff(y) should output exactly the same
You can yourself write more efficient code but it should be
numerically equivalent to the following
if d=0 find cumulative sum of y and prepend zero: test cumulatives
if d=2 test diff(y) # it seems your current version is corrected for d=2
id d=3 test diff(diff(y))
Above y is input series
Oleh






















































22 лютого 2018, 14:41:12, від "mitchelloharawild" <notifications@github.com>:


I've done a re-write of this test in 7a9de0e which should resolve this issue.

**Comment by robjhyndman** [comment]
It's up to the user to make sure the data match the requirements of the ocsb test. The function implements the test under the stated OCSB null hypothesis.

**Comment by olehjktu** [comment]
It seems I have no chance to prove something
For I(0)
but (1-L)^-1P(L) where P(1) !=0 gives non-invertible
process and the distribution of the test statistics
can under H0 will be different
For I(2):
differences will be I(1) hence under H0
the distribution of thr test statistic will have
much more complicated functionla
of Wiener process, possibly involving
"Integral of integral"
Best,
Oleh 
 



23 лютого 2018, 00:58:52, від "Rob J Hyndman" <notifications@github.com>:


It's up to the user to make sure the data match the requirements of the ocsb test. The function implements the test under the stated OCSB null hypothesis.
