### ISSUE TITLE
R function auto.arima does not constrain parameters

### ISSUE THREAD

**Issue by crosschecker** [robjhyndman/forecast#570]
The R function auto.arima should allow a user to limit the number of parameters in several ways, namely (1) the max number of AR terms, (2) max number of MA terms, (3) max number of the sum of the AR and MA terms.  

I have observed that:

The constraints (1), (2), and (3) cannot be used at the same time.  You can have (1) and/or (2), but then not (3).  In other words, (3) will not work; the constraint specified may be violated (but will not necessarily be violated in every case).

**Comment by mitchelloharawild** [comment]
Could you provide a MRE?
