### ISSUE TITLE
Improve docs for tbats.components and plot.tbats

### ISSUE THREAD

**Issue by robjhyndman** [robjhyndman/forecast#571]
Need to explain that "observed values" are Box-Cox transformed. Also other components need describing.

**Comment by saurav2608** [comment]
Hi Rob,
I have been using your package for a while now. I can help update and improve this part of the document. If you are okay please assign this to me. 
S

**Comment by robjhyndman** [comment]
Sure. Thanks for the offer. Please fork the package, make the changes, and issue a pull request.

**Comment by saurav2608** [comment]
I have issues a PR. Please review and accept. 
Thanks - S

**Comment by saurav2608** [comment]
Let me know if I can contribute on this project in any way.

**Comment by robjhyndman** [comment]
Feel free to contribute in the same way. If you spot something you think can be improved, fix it and send in a PR.
