### ISSUE TITLE
ETS MMN :: No model able to be fitted

### ISSUE THREAD

**Issue by melwinjose1991** [robjhyndman/forecast#572]
I am trying to find the best value of alpha, beta and phi for the time-series using the following code : 

```
library(forecast)

data = c(40276L, 34094L, 34694L, 31840L, 33121L, 34431L, 31986L, 35253L, 
         34030L, 36552L, 33336L, 31367L, 34569L, 31460L, 40218L, 35031L, 
         38385L, 41342L, 36324L, 39890L, 39981L, 28232L, 27989L, 36193L, 
         36242L, 36932L, 33729L, 33201L, 31678L, 40539L, 38667L, 47671L, 
         35913L, 30501L, 21705L, 37101L, 20819L, 30007L, 32633L, 30209L, 
         32029L, 35518L, 32267L, 32033L, 35910L, 24330L, 31392L, 29628L
)
data_ts = ts(data, frequency=12)

h=3
alphas = seq(0.1, 0.9, length=10)
betas = seq(0.1, 0.9, length=10)
phis = seq(0.8, 0.98, length=10)
t_multiplicative = TRUE
configs = vector('character')
maes = vector('numeric')

for(phi in phis){
  for(beta in betas){
    for(alpha in alphas){
      
      print(paste0("alpha:",alpha," beta:",beta, " phi:",phi))
      if(beta>alpha)
        next
      
      window_ts = window(data_ts, end=4+((12-(h+1))/12))  
      fit = holt(window_ts, alpha=alpha, beta=beta, phi=phi, damped=TRUE,
                 h=h, exponential=t_multiplicative)
      # plot(fit)
      
      mae = mean(abs(tail(data,n=h)-fit$mean))
      print(mae)
      maes = c(maes, mae)
      
      configs = c(configs, paste0("alpha:",alpha," beta:",beta, " phi:",phi))
    }
  }
}

configs[which.min(maes)]
maes[which.min(maes)]

```

The above code gives following error 
> Error in ets(x, "MMN", alpha = alpha, beta = beta, phi = phi, damped = damped,  : 
  No model able to be fitted

I am new to the area of forecasting, my apologies if the above error is due to poor understanding of the concepts.

**Comment by robjhyndman** [comment]
holt will automatically select the best parameters for you. There are many inadmissible combinations in your code. For example, beta must be less than alpha.

**Comment by melwinjose1991** [comment]
I am trying to find the best parameters for out-of-sample prediction accuracy .

`data = c(40276L, 34094L, 34694L, 31840L, 33121L, 34431L, 31986L, 35253L, 
         34030L, 36552L, 33336L, 31367L, 34569L, 31460L, 40218L, 35031L, 
         38385L, 41342L, 36324L, 39890L, 39981L, 28232L, 27989L, 36193L, 
         36242L, 36932L, 33729L, 33201L, 31678L, 40539L, 38667L, 47671L, 
         35913L, 30501L, 21705L, 37101L, 20819L, 30007L, 32633L, 30209L, 
         32029L, 35518L, 32267L, 32033L, 35910L, 24330L, 31392L, 29628L
)
data_ts = ts(data, frequency=12)

h=3
t_multiplicative = FALSE

window_ts = window(data_ts, end=4+((12-(h+1))/12))  
fit = holt(window_ts, alpha=0.1, beta=0.1, phi=0.98, damped=TRUE, h=h, exponential=t_multiplicative)
plot(fit)

mae = mean(abs(tail(data,n=h)-fit$mean))
print(mae)`
