### ISSUE TITLE
Incompatibility between HoltWinters forecast and checkresiduals in forecast 8.1

### ISSUE THREAD

**Issue by jpclemens0** [robjhyndman/forecast#573]
checkresiduals worked with HoltWinters in version 8.0 in my experience.  Now due to lines 69 and 76 of checkresiduals.R the plot title gets set with a long string that obscures the plot.

**Comment by robjhyndman** [comment]
Thanks. Now fixed in https://github.com/robjhyndman/forecast/commit/5ec54d993831a627f7ecd9858bdd9ec7e9bb84e8
