### ISSUE TITLE
Forecast functions return errors

### ISSUE THREAD

**Issue by ramkumarkr** [robjhyndman/forecast#576]
I installed 8.1 and having issue in R 3.4 and 3.3.2

Error in forecast.Arima(births_arima2, h = 12) : 
  could not find function "forecast.Arima"

Error in forecast.HoltWinters(births_HW, h = 12) : 
  could not find function "forecast.HoltWinters"

**Comment by mitchelloharawild** [comment]
Use forecast() not forecast.HoltWinters(), or forecast.Arima()

#566
