### ISSUE TITLE
Is auto.arima not appropriate for tsCV?

### ISSUE THREAD

**Issue by cdeterman** [robjhyndman/forecast#577]
Perhaps I am overlooking something in the documentation but I thought I should be able to use `auto.arima` in the `tsCV` function.  The call will work but I only get `NA` values.

A minimal example

```r
library(forecast)
e <- tsCV(lynx, auto.arima, h = 1)
mean(e^2, na.rm = TRUE)
[1] NaN
```

**Comment by robjhyndman** [comment]
As explained in the documentation, the second argument must be a function that returns a forecast object. `auto.arima` returns a model. There is an example in the documentation about how to write a function that turns a model into a forecast object.
