### ISSUE TITLE
Calculation of trend component in ets()

### ISSUE THREAD

**Issue by mamut86** [robjhyndman/forecast#579]
I was recently wondering how the trend component is calculated and I am not sure if it is a bug or not. The model derived is an "AAN" with a smoothing parameter of 1 for the trend parameter.

When calculating the trend component b_t = b_{t-1} + 1* e_t for t = 2 we get 0:
hw.fit$states[1,2] + coef(hw.fit)[2]*resid(hw.fit)[1]

However, the function seems to return 0.095 instead:
hw.fit$states

[hw-fit.zip](https://github.com/robjhyndman/forecast/files/1187364/hw-fit.zip)

**Comment by robjhyndman** [comment]
You have tried to fit an AAA model which is inappropriate for this data set. Either let `ets` choose it's own model, or select an AAN model.
