### ISSUE TITLE
Error in etsmodel(y, errortype[i], trendtype[j], seasontype[k], damped[l],  :    Parameters out of range

### ISSUE THREAD

**Issue by nnsarath1991** [robjhyndman/forecast#580]
Hi Rob, 
Good day. I applied ETS function and it automatically choose parameters and corresponding models using minimum AIC value. When I read about it, I came to know this isn't optimal and my analysis confirmed the same. So, I'm trying to use ETS package with user-defined parameters, say(alpha =0.1 to 1 and picking optimal out of it, not using other parameters) and ended up with this error.  Could you please help me out why is it throwing out of range exception?

**Comment by robjhyndman** [comment]
This is not a help site. Ask R questions on stackoverflow.com and forecasting questions on crossvalidated.com.
