### ISSUE TITLE
BATS/TBATS one-step forecast attributes incosistency

### ISSUE THREAD

**Issue by alepmaros** [robjhyndman/forecast#581]
If I try to do a one-step forecast with BATS/TBATS I need to manually recreate the time series object so I can plot it accordingly.

```
star.tra <- window(star, end=c(590))
star.tes <- window(star, start=c(591))

fit1 <- tbats(star.tra)
forecast <- forecast(fit1, h=10)
fit2 <- tbats(star.tes, model=fit1)
one.step.forecast <- fitted(fit2)
```

one.step.forecast gives me this:

```
[1] 23.0412353  9.6037272  5.7801880  4.1347199  3.5141978  3.9116094  2.0071244  1.3125851  0.8593749  5.5703583
```

But normally (with Arima, ets, etc) it gives me this

```
Time Series:
Start = 591 
End = 600 
Frequency = 1 
 [1] 15.169821 12.390409  7.575436  5.678845  2.842747  1.891522  1.885663  2.825171  2.825171  6.594919
```
So to plot it or do whatever I need to manually create the ts object

```
plot(star.tes)
lines(ts(one.step.forecast, start=c(591)), col="red")
```

Is this the correct behaviour?

**Comment by robjhyndman** [comment]
Fixed in https://github.com/robjhyndman/forecast/commit/2af0252fe59a6c63d708805ed1783aabbbe38c2d
