### ISSUE TITLE
Extend tsCV to allow rolling window

### ISSUE THREAD

**Issue by robjhyndman** [robjhyndman/forecast#583]
Currently tsCV allows for rolling origin, but not rolling window evaluation. Add it as a non-default option with window length to be specified. Simplest UI would be to set window=Inf as default.

**Comment by mitchelloharawild** [comment]
At the start, should the window grow to the specified length or start at the specified length?

If it starts at the specified length, Inf doesn't make sense and NULL may be more appropriate.
Otherwise, infinite is consistent.

**Comment by robjhyndman** [comment]
Yes, you're right. I didn't think it through. So window.length=NULL and rolling.window=FALSE would be required.

**Comment by mitchelloharawild** [comment]
So to answer the question, the window should start at the specified length?

If so; we could have a UI as follows:
window = NULL (default, rolling window not used)
window = integer(1) (use a rolling window with length window)

**Comment by robjhyndman** [comment]
yes, ok.

**Comment by mitchelloharawild** [comment]
Resolved in #584

**Comment by panoptikum** [comment]
Nice. I hadn't seen this on time, so I've adjusted the tsCV for my needs.
