### ISSUE TITLE
Fortify a forecast object no longer possible

### ISSUE THREAD

**Issue by pascaloettli** [robjhyndman/forecast#585]
Using `forecast` version `8.1`, I now get an error while trying to `fortify` a `forecast` object.

    library(forecast)
    fit <- ets(window(WWWusage, end=60))
    fc <- forecast(WWWusage, model=fit)
    fortify(fc)
> Error in fortify(fc) : could not find function "fortify"

Another error occurs when combine with `ggplot2`, which I guess is somehow logical:

    library(ggplot2)
    fortify(fc)
> Error: ggplot2 doesn't know how to deal with data of class forecast

Checking `NEWS.md`, I don't see any mention of the withdrawal of `fortify`.

**Comment by mitchelloharawild** [comment]
Apologies, the fortify method was causing conflicts with ggfortify's fortify method, so it was made a hidden internal helper function (#480).

The old fortify method can be found with forecast:::forecast2plotdf

If you do need to convert a forecast object to a data.frame, I would recommend using the as.data.frame method for forecast objects.

I've added a note to the `NEWS.md` to reflect this change (ede689db1206544b4dce8e1d7f2603467cfbaace)

**Comment by pascaloettli** [comment]
Thank you. However, `as.data.frame(fc)` doesn't give the same output as `fortify(fc)`. I am using a workaround.

**Comment by mitchelloharawild** [comment]
If you require the output provided by the old fortify method, you can use forecast:::forecast2plotdf.
We can think about making the forecast:::forecast2plotdf function exported, or improving upon the fortify method and reintroducing it.
