### ISSUE TITLE
Erro function nnetar

### ISSUE THREAD

**Issue by hcamelo** [robjhyndman/forecast#587]
Hello Rob, I am returning the message about the error I commented on using the nnetar function. Here are the commands:

> camocim60mTraining <- read.table("camocim60m10minTraining.csv",header=T,sep=",",dec=",") #dados diurno 8736
> startDate = as.POSIXct("2004-09-01 0:00:00")
> endDate = as.POSIXct("2005-08-30 23:50:00")
> dateMin10min = seq(from=startDate, to=endDate, by="10 min")
> head(dateMin10min)
[1] "2004-09-01 00:00:00 ART" "2004-09-01 00:10:00 ART"
[3] "2004-09-01 00:20:00 ART" "2004-09-01 00:30:00 ART"
[5] "2004-09-01 00:40:00 ART" "2004-09-01 00:50:00 ART"
> length(dateMin10min)
[1] 52416
> length(camocim60mTraining$CamoVel60mTraining)
[1] 52416
> set.seed(1)
> camocim10dataTraining <- xts(camocim60mTraining$CamoVel60mTraining, order.by = dateMin10min)
> attr(camocim10dataTraining, 'frequency') <- 144  # set frequency attribute

fit5 <- nnetar(camocim10dataTraining) #Neural Network Time Series Forecasts
Error in nnet.default(x, y, linout = linout, trace = trace, ...) : 
  too many (1201) weights

**Comment by gabrielcaceres** [comment]
By default the underlying `nnet` function has a maximum of 1000 weights. Try changing the `MaxNWts` argument. The [`nnet` documentation](https://www.rdocumentation.org/packages/nnet/versions/7.3-0/topics/nnet) has more details.
