### ISSUE TITLE
Possible bug on assignment of max.p and max.q

### ISSUE THREAD

**Issue by davidreilly007** [robjhyndman/forecast#588]
In the autoarima code you have:

if(m > 1)
{
if(max.P > 0)
max.p <- min(max.p, m-1)
if(max.Q > 0)
max.q <- min(max.q, m-1)
}

Intuitively if the frequency was say 2, I could see restricting the seasonal max orders to 1 but to me doesn't make sense to restrict the non seasonal to 1.  Possible bug?

**Comment by robjhyndman** [comment]
This avoids confounding of nonseasonal terms with seasonal terms. A nonseasonal lag of m is confounded with a seasonal lag of 1.
