### ISSUE TITLE
Issue with annual data & baggedETS

### ISSUE THREAD

**Issue by AnscombesGimlet** [robjhyndman/forecast#590]
Consider:
```
data <- ts(c(80000, 73000, 74000, 76000), start=c(2013,1), f=1) # annual data
baggedETS(data)
```

Errors with: "Error in x[c:(c + window_size - 1)] : 
  only 0's may be mixed with negative subscripts"

I believe this is due to lack of data. It appears the minimum amount of data for baggedETS to run is 8. Would love it if it could handle any data size! Thanks!

**Comment by robjhyndman** [comment]
Fixed in https://github.com/robjhyndman/forecast/commit/471bae9671a2c9d0fd72cde1d5153db644eac6a1
