### ISSUE TITLE
accuracy measures with NAs in test data

### ISSUE THREAD

**Issue by AliHeggie** [robjhyndman/forecast#594]
I am using the accuracy function to evaluate MASE for test and train sets on a time series with many NA values.

For the test set the MASE always evaluates to NA.

At present line 84 of `errors.R` is `mase <- mean(abs(error/scale))`

Should it instead be `mase <- mean(abs(error/scale), na.rm=TRUE)`, the same as line 161?

**Comment by robjhyndman** [comment]
Thanks. Fixed in https://github.com/robjhyndman/forecast/commit/ce772a034e4b23eebffef47670a9391332c7c5c8
