### ISSUE TITLE
'Function cannot be evaluated at initial parameters' for baggedETS like #217 and #78

### ISSUE THREAD

**Issue by githubERIK** [robjhyndman/forecast#601]
Dear @robjhyndman,

I would be thankful if you could look into the following error.
> x <- stats::ts(c(7.5,7.4,0.0,4.6,5.0,10.0,4.3,7.5,10.0,3.0,4.3,8.3,2.8,10.0,8.4,5.0,4.8,4.1,6.8,5.8,7.3,3.8,0.0,5.3,3.3,2.1,5.3,6.1,5.6,5.8,4.7,6.1,5.6,6.5,4.2,4.4,6.7,6.5,5.3,5.2,5.7,4.5,6.6,4.7,5.6,4.2,6.5,7.4,8.1,8.8,5.0,6.7,0.0,5.6,6.0,9.0,7.1,8.4,6.6,9.4), start = c(2011,1), freq = 12)
> forecast::baggedETS(x)
Error in etsmodel(y, errortype[i], trendtype[j], seasontype[k], damped[l],  : 
  function cannot be evaluated at initial parameters

**Comment by robjhyndman** [comment]
Thanks for letting me know. Fixed in https://github.com/robjhyndman/forecast/commit/c87f33c95b017873eb747e7b16cf495d6b53a574
