### ISSUE TITLE
Comprehensive Documentation ?

### ISSUE THREAD

**Issue by Ic3fr0g** [robjhyndman/forecast#602]
Several sources are required to understand the workings of this package. Though `fpp` is a great starting point, it does not reflect the recent changes from `forecast8.x`. One has to look through  Hyndsight blog to find new features or worse, dig through all the code to find new developments. I want to create a PR for comprehensive documentation of the package, it should include - 
+ Recent changelog. Source: hyndsight blog
+ Models (tbats, nnetar, cronston). Source: all over the place, mainly, fpp book
+ Examples Usage in README.md and generic usage of the `forecast` function

**Comment by robjhyndman** [comment]
The 2nd edition of the fpp book is meant to be up-to-date, and is intended to cover all of this. See http://OTexts.org/fpp2. The book is not yet finished, but should be within the next 2-3 months.
