### ISSUE TITLE
ETS - Parameters out of range

### ISSUE THREAD

**Issue by jazzynorbi** [robjhyndman/forecast#603]
If you run
ets(ts(rnorm(100,0,1),frequency = 12), model = "AAA", beta = 0.1)
you get following error:
Error in etsmodel(y, errortype[i], trendtype[j], seasontype[k], damped[l],  : 
  Parameters out of range

I understand we have some restricted parameter ranges (0 < beta < alpha), but here alpha and gamma is free to be optimized in the range which satisfies criteria given beta is set to 0.1.

Using
ets(ts(rnorm(100,0,1),frequency = 12), model = "AAA", beta = 0.1, bounds = "admissible") 
works though.

**Comment by robjhyndman** [comment]
Now fixed in https://github.com/robjhyndman/forecast/commit/15652c620fb42ea7e5b43ea421bae6d5c5d66198 and https://github.com/robjhyndman/forecast/commit/a47d93a06a2617d5d5d4bdce536aefa800796c97
