### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by ristrettoanna** [robjhyndman/forecast#604]
I am trying to install development version of forecast package using:

devtools::install_github("robjhyndman/forecast")

I am encountering an error:

Downloading GitHub repo robjhyndman/forecast@master
from URL https://api.github.com/repos/robjhyndman/forecast/zipball/master
Error: running command '"C:/PROGRA~1/MIE74D~1/ROPEN~1/R-34~1.1/bin/x64/R" --no-site-file --no-environ --no-save --no-restore --quiet CMD config CC' had status 127

devtools is installed successfully, but I am afraid error is coming for forecast package. 

Any help here, please.

**Comment by robjhyndman** [comment]
Do you have Windows Rtools installed? https://cran.r-project.org/bin/windows/Rtools/

**Comment by ristrettoanna** [comment]
No, I am afraid, R tools is not installed. Which version should be suitable for win 64 bit? I will install and I will try reinstalling the package, forecast. Is there anything other than this, I need to do? 
Thank you for your response.

**Comment by ristrettoanna** [comment]
I have installed Rtools but I am not able to proceed further and still not able to install the package. May I get any help in here. 
Thanks.

**Comment by robjhyndman** [comment]
This is not a help site, but a place to submit bug reports or feature requests for the forecast package. I can't provide help for getting Rtools installed on your computer. Try reading https://github.com/stan-dev/rstan/wiki/Install-Rtools-for-Windows
