### ISSUE TITLE
g++ compiler warning :" WARNING: use of OpenMP disabled; this compiler doesn't support OpenMP 3.0+"

### ISSUE THREAD

**Issue by pgensler** [robjhyndman/forecast#607]
I am trying to install forecast in a docker container, and it appears that I get a bunch of warnings when trying to install with g++ compiler:

This warning is generated by: https://github.com/RcppCore/RcppArmadillo
```
In file included from /usr/local/lib/R/site-library/RcppArmadillo/include/armadillo:53:0,
                 from /usr/local/lib/R/site-library/RcppArmadillo/include/RcppArmadilloForward.h:46,
                 from /usr/local/lib/R/site-library/RcppArmadillo/include/RcppArmadillo.h:31,
                 from calcBATS.h:36,
                 from calcTBATS.cpp:1:
/usr/local/lib/R/site-library/RcppArmadillo/include/armadillo_bits/compiler_setup.hpp:474:96: note: #pragma message: WARNING: use of OpenMP disabled; this compiler doesn't support OpenMP 3.0+
   #pragma message ("WARNING: use of OpenMP disabled; this compiler doesn't support OpenMP 3.0+")
```

This isn't really a bug, but it would be nice to be able to compile the package without any warnings. Should I be using clang++ instead, or a different compiler? I can provide a dockerfile of the image I am trying to build if you are interested in more details.

[forecast_compile_warnings.txt](https://github.com/robjhyndman/forecast/files/1405540/forecast_compile_warnings.txt)

**Comment by robjhyndman** [comment]
The problems comes from RcppArmadillo, not forecast. Better ask the maintaners of that package.

**Comment by pgensler** [comment]
I see what happens now.......so because forecast has Linking to RccpArmadillo, I think the C calls basically generate a ton of these warnings (which I think you may need to enable, based on this discussion:

> It's complicated. "We" can only do what R let's us do. Because all compilations are via R CMD ..., ie R CMD compile ... (say, and behind the scenes) the R configuration matters.
> 
> Which is examined when RcppArmadillo is installed, and recorded. The test is essence studying whether R itself passes -fopenmp down or, and recording it. (With a special exception for macOS, but that is another drama in itself.)
> 
> So if R has seen OpenMP, we use it in RcppArmadillo. Now what is being talked about is that client packages of RcppArmadillo trigger the warning, and that is mostly ... because they do (not) yet add -fopenmp themselves to their builds. So (Rcpp)Armadillo can have OpenMP, expects it and does not see it. Hence the message.
> 
> Little we can do as we cannot / should not rewrite other people's src/Makevars. The warning is, actually, the Right Thing (TM).
> 
> We could add #define ARMA_DONT_PRINT_OPENMP_WARNING but I fear nobody will ever change their client packages... Dunno. Maybe we should instead of shouting at people. To be pondered some more.

**Comment by robjhyndman** [comment]
OK. First I knew about this. I'll ask Dirk what he suggests for the Makevars file.

**Comment by pgensler** [comment]
No worries, I completely understand. Let me know if you would like a copy of my container to reproduce all the warnings.

**Comment by robjhyndman** [comment]
Relevant discussion:
https://github.com/RcppCore/RcppArmadillo/issues/180
https://stackoverflow.com/questions/46723854/rcpparmadillo-using-autoconf-to-disable-openmp

**Comment by robjhyndman** [comment]
Something like this should fix the problem:
https://github.com/kogalur/randomForestSRC/tree/master/src/main/resources/cran/src

**Comment by mitchelloharawild** [comment]
Seems to have been resolved in the latest version of RcppArmadillo.
