### ISSUE TITLE
stlm forecast with newxreg

### ISSUE THREAD

**Issue by panoptikum** [robjhyndman/forecast#609]
Dear Forecasters,

I'm not sure whether this is a bug or I may misuse the stlm() and forecast.stlm() functions.

When I fit a model with stlm(x, xreg, ...) and then forecast this model with forecast.stlm(x, newxreg, h=12) I get very different results for my forecasts if I change one value of my twel newxreg. For example, if I forecast the one full year and I change the forecast for my external regressor from 2 to 5 all forecasts end up being on a higher level which seems quite odd to me.

For further clarification I'm happy to provide pictures and/or data.

**Comment by robjhyndman** [comment]
Why would you not expect them to change? If you change your regressors, the forecasts will change.

**Comment by panoptikum** [comment]
Yes, I expected that. But I changed only one value of 12 and the forecasts shift up on a whole new level.
