### ISSUE TITLE
Class of nnetar output is "nnetarmodels" but input checks for "nnetar"

### ISSUE THREAD

**Issue by MarkLondon** [robjhyndman/forecast#611]
I cannot train a model and resend it into a nnetar function, because my output class is different to my required input class:
    else if(inherits(model, "nnetar"))
      fit <- nnetar(object, model=model, ...)
    else
      stop("Unknown model class")
I get the error "Unknown model class" when passing a previous output back in as an input.

**Comment by robjhyndman** [comment]
Please provide a minimal reproducible example.
The following works:
```r
fit <- nnetar(window(lynx,end=1920))
fit2 <- nnetar(lynx, model=fit)
```

**Comment by MarkLondon** [comment]
Rob,


I was using the forecast package with abstraction, wrapping it in lists of models and functions that were created generically. I noticed that the class reported of the model output by the nnetar function is “nnetarmodels“. I now can send this model into the function, but

have changed my wrapper function, so the original ‘bug’ is unreproducible.

I followed your example, and interestingly, it is input data dependant. Works on lynx, not on AirPassengers. Hope this helps,

Thanks,
Mark London


# debug:
library(forecast)
# Fit on subset
fit <- tbats(window(lynx,end=1920))
# Refit on all
fit2 <- tbats(lynx, model=fit)
# Forecast - working
forecast(fit2)
# Does work for lynx!
forecast(lynx, model = fit2)

# Fit on subset
fit <- tbats(window(AirPassengers, end=1959))
# Refit on all
fit2 <- tbats(AirPassengers, model=fit)
# Forecast - working
forecast(fit2)
# Does not work
forecast(AirPassengers, model = fit2)

forecast(AirPassengers, model = fit2)
Error in x - fits : non-numeric argument to binary operator
In addition: Warning message:
In mean.default(x, na.rm = TRUE) :
  argument is not numeric or logical: returning NA

**Comment by robjhyndman** [comment]
This is not a bug. When you call forecast with the first argument a time series, it uses an ets model applied to the data, and then forecasts from that model. When you also pass it a model argument, it will try to use that model inside the ets() function.

In your first example, tbats is default to a BATS model because there is no seasonality, and a BATS model is very similar to an ets model, so the ets() function can figure out what to do with it.

In your second example, tbats fits a TBATS model, and then the ets() function can't figure out what to do.

**Comment by robjhyndman** [comment]
Fixed the tbats problem here: https://github.com/robjhyndman/forecast/commit/5ab6737f9b56b64349ab88fea7b943b8b568adf6

Can you provide a reproducible example of the nnetar problem?

**Comment by MarkLondon** [comment]
Many thanks for getting back to me, this explains a lot, I think.

Regards,

Mark

**Comment by MarkLondon** [comment]
That's great, thanks. I'll see if I can reproduce the nnetar.

**Comment by mitchelloharawild** [comment]
Closed due to no MRE in over a year.
