### ISSUE TITLE
tsCV is very slow when run against different horizons

### ISSUE THREAD

**Issue by dlindelof** [robjhyndman/forecast#614]
I'm interested in evaluating different algorithms for short-term climate forecasts (hourly scale, horizon less than 24 hours). I'm currently using `tsCV` to calculate the forecast accuracy for different horizons (say 1h, 6h, etc).

The 'canonical' way to do this seems to be something like a `for` loop:

```
for (h in 1:6) {
  error <- tsCV(data, forecastFunction, h)
  # do something with the error
}
```
Obviously, the same data (and hence, the same model) is going to be used for each possible horizon, but `tsCV` seems to recalculate the model each time. This can result in very long running times, depending on the forecast function.

I would suggest extending the `tsCV` function to accept a vector for `h`, so that the above `for` loop reduces to

`error <- tsCV(data, forecastFunction, h = 1:6)`

so that the same model is used for evaluating the forecast errors for each horizon. This would presumably imply extending the `forecast` methods to also accept a vector for their `h` argument.

**Comment by david-jankoski** [comment]
just a suggestion - you could maybe estimate the model outside of the loop and move just the forecasts with different horizons inside

**Comment by robjhyndman** [comment]
This has been on my to-do list for a while, so thanks for the prompt. Now updated in https://github.com/robjhyndman/forecast/commit/abc29c07fdae738a4b75f2668842b640752d221c.

**Comment by dlindelof** [comment]
Wow, thanks for the fast fix ;-)
