### ISSUE TITLE
baggedModel cannot be used through "forecast::baggedModel" without loading "library(forecast)"

### ISSUE THREAD

**Issue by githubERIK** [robjhyndman/forecast#628]
\> forecast::meanf(WWWusage)
    Point Forecast    Lo 80    Hi 80    Lo 95    Hi 95
101         137.08 85.21691 188.9431 57.31663 216.8434
102         137.08 85.21691 188.9431 57.31663 216.8434
103         137.08 85.21691 188.9431 57.31663 216.8434
104         137.08 85.21691 188.9431 57.31663 216.8434
105         137.08 85.21691 188.9431 57.31663 216.8434
106         137.08 85.21691 188.9431 57.31663 216.8434
107         137.08 85.21691 188.9431 57.31663 216.8434
108         137.08 85.21691 188.9431 57.31663 216.8434
109         137.08 85.21691 188.9431 57.31663 216.8434
110         137.08 85.21691 188.9431 57.31663 216.8434
\> forecast::baggedModel(WWWusage)
**Error in get(as.character(FUN), mode = "function", envir = envir) : 
  object 'ets' of mode 'function' was not found**
\> library(forecast)
\> baggedModel(WWWusage)
Series: WWWusage 
Model:  baggedModel 
Call:   baggedModel(y = WWWusage)

**Comment by robjhyndman** [comment]
Fixed in https://github.com/robjhyndman/forecast/commit/e47f5bb6e1a4fd1f90750274f139454bcb4debd2
