### ISSUE TITLE
trace broken in parallel operation? 

### ISSUE THREAD

**Issue by landroni** [robjhyndman/forecast#631]
When using `trace = TRUE` at the same time as `stepwise = FALSE, parallel = TRUE`, I notice that the list of ARIMA models considered is not being reported: 
```auto.arima(euretail, stepwise = FALSE, trace = TRUE, parallel = TRUE, num.cores = 1)```

Is `trace` expected to work in `parallel = TRUE` mode? 

(Using `forecast_8.2`.)

**Comment by mitchelloharawild** [comment]
I've added a message to make this clearer, currently tracing auto.arima paths in parallel is not supported.
