### ISSUE TITLE
understanding the unit circle plots

### ISSUE THREAD

**Issue by landroni** [robjhyndman/forecast#632]
This is more a question than a report. Consider the Cortecosteroid example from `fpp2`: 
http://otexts.org/fpp2/seasonal-arima.html

```
(fit <- Arima(h02, order=c(3,0,1), seasonal=c(0,1,2), lambda=0))
#> Series: h02 
#> ARIMA(3,0,1)(0,1,2)[12] 
#> Box Cox transformation: lambda= 0 
#> 
#> Coefficients:
#>          ar1    ar2    ar3    ma1    sma1    sma2
#>       -0.160  0.548  0.568  0.383  -0.522  -0.177
#> s.e.   0.164  0.088  0.094  0.190   0.086   0.087
#> 
#> sigma^2 estimated as 0.00428:  log likelihood=250
#> AIC=-486   AICc=-485   BIC=-463
```

If I plot the model fit, I'm a bit confused about interpreting the unit circle plots: 
```fit %>% autoplot```
![screenshot_2017-12-17_22-48-39](https://user-images.githubusercontent.com/1318567/34093432-0318e0fa-e37d-11e7-8950-d8c93a01382c.png)

So two questions: 
- How far from the unit circle is 'far enough'? For both AR and MA roots I see points very close, or almost on the unit circle. Is this problematic in terms of numeric stability? 
- Is it normal that there are so many MA roots on the plot?

**Comment by robjhyndman** [comment]
The MA characteristic polynomial is of order 2*12+1 = 25 so there are 25 MA roots. auto.arima requires roots to be greater than 1.01 for numerical stability. So inverse need to be less than 0.99.

**Comment by landroni** [comment]
Thank you, very helpful.
