### ISSUE TITLE
Making forecast library more accessible for basic scenarios

### ISSUE THREAD

**Issue by tilayealemu** [robjhyndman/forecast#635]
Thanks for this useful library. I came here to see if you'd be interested in making forecast more accessible.

Currently, forecast requires too much work to integrate with other systems. Consider a java system that wants to provide historical data, horizon, and get back forecasted numbers. It may not be interested in setting (seasonality, stationary, etc) nor getting back the model object. Nevertheless, to achieve this one has to,
- install R dependencies
- install RServe
- install forecast library
- write a java client to RServe
- wrap all of that as a service

It's a lot of plumbing for such a well defined problem. I've been working on a generic docker image that bundles RServe and forecast, and provides an HTTP POST interface to a simple `auto.arima` call. All a user has to do to get forecasts is run the docker container and make an http call from any language. I think it makes the library more accessible because it doesn't need too much engineering work and statistics background.

A statistician may frown upon blindly calling `auto.arima` and using the returned forecasts. But still, there's interest in forecasting from users who are not interested in the details and just want a reasonable guess.

I'd be happy to polish up my work and contribute it somewhere. Have you thought in this direction, and any future plans?

**Comment by robjhyndman** [comment]
I have no plans to write interfaces to other languages or platforms. I'm happy for other people to pursue such endeavours.
