### ISSUE TITLE
when set beta a default value throw error

### ISSUE THREAD

**Issue by nsy3694** [robjhyndman/forecast#639]
time series 
x<-c(59231.00 ,30878.00,39125.00 ,52716.00 ,110511.00 ,40663.00,39197.00,106440.00,
140230.00,67790.00,128565.00,164099.00,59789.00,28011.00 ,104353.00,41277.00 ,155587.00,137916.00,
42332.00,120647.00,134741.00,93769.00,113481.00,151424.00,40610.00,56368.00,50954.00,81204.00,  93976.00,168235.00,65459.00,106955.00,136526.00,170665.00,125928.00,123386.00,54859.00,105600.00,152335.00)
y<-ts(x,frequency=12)
fit <- ets(y,model = "AAA",beta=0.049)
[1] "Model: ETS(A,Ad,A)"
Error in etsmodel(y, errortype[i], trendtype[j], seasontype[k], damped[l],  : 
  Parameters out of range
i have set model="AAA" 
1 WHY the result show "Model: ETS(A,Ad,A)
2 beta =0.049  out of range?

**Comment by robjhyndman** [comment]
Update to the latest version of the package and this does not occur.

**Comment by nsy3694** [comment]
my forecast package version is 8.2 ,download from cran ,is it the latest version?

**Comment by robjhyndman** [comment]
No. The latest version is here on github.

**Comment by nsy3694** [comment]
it  does  works,i have another question ,i want to use ets to prediction sales volume，i think ets is the best function i have find ,but i use the same data in tableau ,it gave me a better result .
ets(y,ic="aic")
Smoothing parameters:
    alpha = 0.0277 
    beta  = 4e-04 
    gamma = 3e-04 
    AIC     AICc      BIC 
965.7387 994.8816 994.0192 
tableau
RMSE	MAE	      MASE	MAPE	AIC		Alpha	Beta	     Gamma
￥29,135	￥21,718	0.46	25.8%	836		0.000	0.049	0.000	
i know when i don't set params ,ets will select the best one ,but none is better than tableau's result 
i want to know  how to set params can get a result better than tableau

**Comment by robjhyndman** [comment]
This is not a help site. It is for reporting bugs and feature requests. Please ask general questions on crossvalidated.com
