### ISSUE TITLE
Are Croston predition intervals for deman and period models gone?

### ISSUE THREAD

**Issue by rulero** [robjhyndman/forecast#642]
- OS version: Windows 10 Enterprise 1709 x64
- R version: 3.4.3
- forecast version: 8.1

-----

In a previous version of the package (forecast 7.1 in R3.1.2) executing the `croston` method returned the prediction intervals for the demand and period models used internally.

This commands used to display the intervals of the `demand` model:
``` R
y <- rpois(20, lambda=1)
fcast <- croston(y)
demand <- fcast$model$demand
plot(demand)
```

But in the new version 8.1 the commands above don't display them because the elements `demand$lower` and `demand$upper` are no longer included

Although the documentation still mentions them:
> Note that prediction intervals are not computed as Croston's method has no underlying stochastic model. The separate forecasts for the non-zero demands, and for the times between non-zero demands do have prediction intervals based on ETS(A,N,N) models.

There is something wrong with either the method or the documentation.

**Comment by robjhyndman** [comment]
They were removed in https://github.com/robjhyndman/forecast/commit/c36d9c18074c8057628ee4fd242808491bcba729#diff-0df290d165cc214e8770adaef179f9e5. I'll fix the docs.

**Comment by robjhyndman** [comment]
Fixed in https://github.com/robjhyndman/forecast/commit/a31fa1b1bba522bea8d815bc5d7178b4f9e7e7d3
