### ISSUE TITLE
autoplot missing

### ISSUE THREAD

**Issue by gehusi** [robjhyndman/forecast#643]
Getting a "could not find function" error with autoplot:

```
library(forecast)
autoplot(WWWusage)
```

Error: could not find function "autoplot"

`
version
`
               _                           
platform       x86_64-w64-mingw32          
arch           x86_64                      
os             mingw32                     
system         x86_64, mingw32             
status                                     
major          3                           
minor          4.3                         
year           2017                        
month          11                          
day            30                          
svn rev        73796                       
language       R                           
version.string R version 3.4.3 (2017-11-30)
nickname       Kite-Eating Tree

**Comment by mitchelloharawild** [comment]
In order for autoplot to work, you need to also load in ggplot2.

```R
library(forecast)
library(ggplot2)
autoplot(WWWusage)
```

**Comment by gehusi** [comment]
*headslap*

Thanks...
