### ISSUE TITLE
ggseasonplot with polar coords has odd axis

### ISSUE THREAD

**Issue by robjhyndman** [robjhyndman/forecast#644]
```r
library(fpp2)
ggseasonplot(a10, polar=TRUE) +
  ylab("$ million") + ggtitle("Polar seasonal plot: antidiabetic drug sales")
```

The Jan axis label is "Jan/". Where did the / come from?

**Comment by mitchelloharawild** [comment]
That comes from wrapping the years in a continuous way (as years are discrete here, an added data point with label "" is added). ggplot2 realises that in polar coordinates, position 0 and 1 (labelled "Jan" and "") are overlapped, and joins them with "/". Should be easy to fix by asking ggplot not to display a label for 1.
