### ISSUE TITLE
incomprehensible fitted values from "Random walk with drift" 

### ISSUE THREAD

**Issue by mbflex** [robjhyndman/forecast#648]
Based on package fpp2 (data: "goog") and based on description in the ebook (second edition, chapter 3):

I understand results of: 
naive(goog)$fitted  --> same shape as the original data (goog), just shifted  by one to the right
meanf(goog)$fitted --> horizontal line, each point = mean of the whole time series
   
I do _not_ understand result of:
rwf(goog, drift=TRUE)$fitted

I would expect a straight line with an upward trend.
However, even the drift parameter is set to "true", the fitted values looks more or less equal to the native method (without the trend parameter)

**Comment by robjhyndman** [comment]
The model is y[t] = y[t-1] + c + e[t]. So the fitted values are y[t-1] + c. The value of c is quite small.
