### ISSUE TITLE
tsdiag implicitly uses fitdf=0

### ISSUE THREAD

**Issue by Daumantas-Bloznelis** [robjhyndman/forecast#660]
I tend to agree with a [criticism](http://www.stat.pitt.edu/stoffer/tsa4/Rissues.htm) by David S. Stoffer of the `tsdiag` function.

Shouldn't the `Box.test` function inside of the `tsdiag` function use option `fitdf=p+q` rather than `fitdf=0` (where p+q are the AR and the MA orders)?

**Comment by robjhyndman** [comment]
Of course it should, but tsdiag is not part of the forecast package and I have no control over it. I wrote `checkresiduals()` to do a similar job, and the degrees of freedom are handled corrected in that function.

**Comment by Daumantas-Bloznelis** [comment]
You are right. I am sorry, I should have checked that before opening the thread.
