### ISSUE TITLE
nnetar residuals

### ISSUE THREAD

**Issue by gabrielcaceres** [robjhyndman/forecast#665]
I noticed when `type = "innovations"` and `lambda` is not NULL, `residuals.nnetar` [returns a matrix](https://github.com/robjhyndman/forecast/blob/c60c3a38b762d08904e7e137fcc5bda4783d5108/R/residuals.R#L152) (one column for each fitted network) while in other cases it returns a single vector with the average value from all  networks. Is this intended behavior?

**Comment by mitchelloharawild** [comment]
Refer to #441

**Comment by mitchelloharawild** [comment]
This definitely needs more documentation, I'll fix this.

**Comment by gabrielcaceres** [comment]
Ah, I had forgotten about that! Yeah, updating the documentation would help avoid any confusion between the differing behavior.

**Comment by gabrielcaceres** [comment]
I was thinking more about this and, in the spirit of #441, it might make more sense to return a matrix of residuals whenever `type = "innovations"` regardless of whether `lambda` is NULL. Thoughts?
