### ISSUE TITLE
AR-style forecasting with other functions besides nnet

### ISSUE THREAD

**Issue by gabrielcaceres** [robjhyndman/forecast#668]
I often am curious how other algorithms may perform when used to forecast an AR-type model in a similar manner to how neural networks are used in `nnetar`. It is convenient to have something automatically set up the lags for the fitting and forecasting, so I modified the internals of `nnetar` to allow for a user-defined function provided as an argument. For example, I've played around with it using things like `randomForest` and `glm`, as well as "recreating" `nnetar` to make sure the results are equivalent. 

Let me know if it's something that might be of interest and I can send a PR for you to take a look at it.

**Comment by mitchelloharawild** [comment]
We're about to push 8.3 to CRAN, let's leave that to a later version. However if you make the pull we'll look at it for the next version :smile:

**Comment by gabrielcaceres** [comment]
Sounds good 👍
