### ISSUE TITLE
Missing BoxCox Inversion in ARIMA(x, model = fit)

### ISSUE THREAD

**Issue by gorgia** [robjhyndman/forecast#669]
```
fit_bc = Arima(x_training, order = c(1,1,0), lambda = box_cox_lambda)
summary(fit_bc) #OK
plot(fitted(fit_bc)) #OK

fit_bc_test = Arima(x_test, model = fit_bc)
# fit_bc_test = Arima(x_test, model = fit_bc, lambda = box_cox_lambda) #looks like the same since lambda param is ignored
summary(fit_bc_test ) #NO!
plot(fitted(fit_bc_test )) #NO!
plot(InvBoxCox(fitted(fit_bc_test), lambda = box_cox_lambda) #OK!
```

Am I missing something?
Thanks in advance

**Comment by robjhyndman** [comment]
I don't understand the problem. Are you using v8.3 from github? Perhaps the problem was fixed here: https://github.com/robjhyndman/forecast/commit/4cb3201e78330365f75c7d9accd28e30b3b80228#diff-41f5327cd19283f9b6db38e23fe9d563

**Comment by gorgia** [comment]
Yes, that was the problem: the fitted data did not get back-transformed when a model was passed to the `Arima(x, model = modelwithboxcox )` function.
Sorry I was using version 8.2 from CRAN repo.
In 8.3 this problem has been solved.
Thanks, professor!
