### ISSUE TITLE
Fitting TBATS model without re-estimating parameters and non-integer frequency time-series

### ISSUE THREAD

**Issue by matthijsvanderloos** [robjhyndman/forecast#672]
Hi Rob,

I fit a TBATS model on non-integer frequency time series data. Then, I apply the same model to the same data but this returns different fitted values:

```R
> library(forecast)
> 
> model <- Arima(ts(rnorm(1000),freq=365.25/7), order=c(1,1,1), seasonal=c(1,1,1),
+                fixed=c(phi=0.5, theta=-0.4, Phi=0.3, Theta=-0.2))
> foo <- simulate(model, nsim=100)
> 
> fit <- tbats(foo)
> refit <- tbats(foo, model = fit)
> 
> all(fitted.values(fit) == fitted.values(refit))
[1] FALSE
```

I think this issue is caused by these lines in `fitPreviousTBATSModel`:

https://github.com/robjhyndman/forecast/blob/f2556177915363907634f033ae69745cd2f524b1/R/fitTBATS.R#L3-L5

**Comment by robjhyndman** [comment]
Thanks. Now fixed in https://github.com/robjhyndman/forecast/commit/a0d7d9a0ac744eaece563383970086f399a8a102
