### ISSUE TITLE
Forecast customer's spending

### ISSUE THREAD

**Issue by Jimnguyen94** [robjhyndman/forecast#674]
Dear Sir,

I have been struggling with forecasting customer's spending and would really appreciate if you could help me or give me some hints on this problems. Here is my data set:
[time series spending.xlsx](https://github.com/robjhyndman/forecast/files/1906439/time.series.spending.xlsx)
I have been trying to use Arima model to forecast the customers' spending daily. However, due to a special event on every first day of the month, the customer's spending on that day is always extremely higher than other days. I have been doing research on how to solve this so that I can forecast accurately the customer's spending on both normal days and first day of month. Following one of you instructions on cross-validated website, I changed the data set a bit so that each month only contains 28 days, and numbered them from 1 to 28. After that, I ended up with this coding:
df <- read.csv("C:/Users/ADMIN_VP/Desktop/tdg-ts.csv", header = TRUE) #file updated daily

xreg <- cbind(Date=model.matrix(~as.factor(df$Date)), Holiday=df$Holiday, Weekend=df$Weekend, KMDT=df$Promotion, fdom=df$Firstdayofmonth)

xreg
xreg <- xreg[,-1]

tsspending <- ts(df$Spending, frequency=28)
nrow(df)
fit <- auto.arima(tsspending, xreg=xreg)

I am stucked at this line when it shows the error that there isn't any suitable Arima models for this situation.

I did also substitute auto.arima function to tbats function and it did work. The predicted results did follow the trend of the time series (spending on first day of month is higher than that on normal days) but the error percentage is from 2-4%, which is quite high to me because the error percentage is allowed to be 1.5% or less. 

I am really appreciate if you can help me with this problems. Thank you very much!

Best regards.

**Comment by robjhyndman** [comment]
This is not a place for obtaining help. Please ask your question on stackoverflow.com.
