### ISSUE TITLE
Questions: Ljung-Box results & Tidy results

### ISSUE THREAD

**Issue by rsangole** [robjhyndman/forecast#677]
Dr Hyndman,

- Today `checkresiduals` doesn't return any of the results performed by the Ljung box test. Have you considered modifying this to return the calculated values in a tidy data frame? It would make the model selection in a tidy & pipeable fashion possible using pipes and the `purrr` functions.

- On similar lines, along with printing the results of a model using `summary`, returning all the results (smoothing params, initial states, AIC etc, error measures etc) in a tidy data-frame and perhaps even making the results accessible via the `broom` package would proof very useful towards automating model selection in a tidy framework.

I'm more than happy to work on these and send a PR if you'd be willing to implement these features in your package.

**Comment by robjhyndman** [comment]
Good point. I'm actually working on a completely new package that will replace forecast. It will use a tidy framework and will hopefully make it easier to do the things you mention. See https://github.com/tidyverts/tidyforecast for details. The sweep package does (most of?) what you say in your second point. 

How much we want to duplicate these efforts in the forecast package needs to be determined.

**Comment by rsangole** [comment]
Ah, lovely, I did not know `sweep` existed. It seems to be exactly what I am looking for. 

Looking forward to `tidyforecast`!
