### ISSUE TITLE
Error in forecast.stlm function

### ISSUE THREAD

**Issue by mbanco** [robjhyndman/forecast#678]
Hi, Rob

I've the next error message when run the forecast.stlm function:

datos <- c(0.21, 0.21, 0.21, 0.21, 0.21, 0.21, 0.21, 0.21, 0.21, 0.21, 0.21, 0.21, 0.21, 0.22, 0.22, 0.22, 0.22, 0.22, 0.22, 0.22, 0.22, 0.22, 0.22, 0.22, 0.23, 0.23, 0.23, 0.24, 0.25, 0.24, 0.25, 0.25, 0.25, 0.27, 0.3, 0.28, 0.26, 0.25, 0.25, 0.26, 0.25, 0.25, 0.25, 0.25, 0.27, 0.28, 0.28, 0.29, 0.29, 0.29, 0.29, 0.29, 0.29, 0.29, 0.29, 0.29, 0.29, 0.29, 0.28, 0.28, 0.27, 0.26, 0.25, 0.25, 0.25, 0.24, 0.24, 0.24, 0.23, 0.23, 0.22, 0.22, 0.22, 0.21, 0.21, 0.21, 0.21, 0.21, 0.21, 0.2, 0.2, 0.2, 0.2, 0.19, 0.19, 0.19, 0.19, 0.19, 0.19, 0.18, 0.18, 0.18, 0.18, 0.18, 0.18, 0.18, 0.18, 0.18, 0.18, 0.18, 0.18, 0.17, 0.17, 0.18, 0.18, 0.18, 0.18, 0.18, 0.18, 0.18, 0.18, 0.18, 0.18, 0.18, 0.18, 0.18, 0.19, 0.19, 0.19, 0.19, 0.19, 0.19, 0.19, 0.19, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.21, 0.21, 0.21, 0.21, 0.21, 0.22, 0.22, 0.22, 0.22, 0.22, 0.22, 0.22, 0.22, 0.22, 0.22, 0.21, 0.22, 0.22, 0.22, 0.22, 0.22, 0.22, 0.22, 0.22);

y <- ts(datos, frequency = 365.25/7, class = 'ts');

tsmod <- stlm(y);

plot(forecast(tsmod, h=10));

Error in `[.default`(object$stl, n - rev(seq_len(mp)) + 1, colname) : 
  subscript out of bounds

Regards,

**Comment by mitchelloharawild** [comment]
Fixed, thanks.
