### ISSUE TITLE
Documentation to add other R forecasting methods as forecast objects

### ISSUE THREAD

**Issue by alexcombessie** [robjhyndman/forecast#680]
I am thinking specifically about Facebook Prophet. They do not follow exactly the forecast structure. Do you have some documentation or example on how to make an external forecasting method from R into a proper forecast object? I really like the forecast project, and this would greatly help provide a consistent API and way to evaluate performance (nice one, tsCV!)

**Comment by robjhyndman** [comment]
See help(forecast). Value section

**Comment by alexcombessie** [comment]
Thanks a lot Rob for your swift reply! Sorry for asking the question twice on Twitter, I figured asking the question here could benefit others. 
Indeed "help(forecast) - Value section" is very helpful. It looks like Facebook prophet is not too far from this structure 😃 .  Quick question: what do we expect for "fitted: Fitted values (one-step forecasts)"? Is it only defined after applying with fitted model to new test data (cf. https://robjhyndman.com/hyndsight/out-of-sample-one-step-forecasts/)?

**Comment by robjhyndman** [comment]
No. Fitted values are one-step forecasts on the training data. They are not real forecasts, as they use the estimated parameters. See https://otexts.org/fpp2/residuals.html
