### ISSUE TITLE
auto.arima can sometimes return model with class(xreg) == "data.frame" this causes badness in forecast()

### ISSUE THREAD

**Issue by MilesMcBain** [robjhyndman/forecast#686]
This was quite the bug to track down! It results in this strange warning, see this reprex:

```r
library(forecast)
library(fpp2)
data(uschange)

uschange <- as.data.frame(uschange)
uschange <- cbind(uschange, regressor = rnorm(nrow(uschange)))

train <- 1:100
test <- 101:187

Y_train <- uschange[train,"Consumption"]
X_train <- uschange[train, c("Unemployment","Savings","regressor")]
X_test <- as.data.frame(uschange[test, c("Unemployment","Savings","regressor")])


lm_ar_fit <- auto.arima(y = Y_train,
                    xreg = as.data.frame(X_train))
class(lm_ar_fit$xreg)

forecast(lm_ar_fit, xreg = X_test)
```

Notice how `lm_ar_fit$xreg` is a data.frame? This results in the warning you get from the forecast call. Specifically: 
```
Warning message:
In cbind(intercept = rep(1, n), xreg) :
  number of rows of result is not a multiple of vector length (arg 2)
```
So this happens because when the data.frame eventually makes its way down to `stats::predict.Arima`, that function tries to remove the class of `xreg`, assuming it is matrix-like. [See this line](https://github.com/wch/r-source/blob/af7f52f70101960861e5d995d3a4bec010bc89e6/src/library/stats/R/arima.R#L413). Since it is a dataframe this converts it to a plain list of lists. This causes a warning to be thrown [on this line](https://github.com/wch/r-source/blob/af7f52f70101960861e5d995d3a4bec010bc89e6/src/library/stats/R/arima.R#L421). Which can be reproduced with this simpler code:  

```
cbind(list(list(1,2,3), list(4,5,6)), c(1,1,1) )
``` 

But notice that if the length of 1's to be bound is a multiple of the number of columns (now lists), no warning is given: 
```
cbind(list(list(1,2,3), list(4,5,6)), c(1,1))
```
So the warning can be somewhat hard to reproduce!

I thought I could be cool and provide a pull for `auro.arima` but that function is a bit hectic, with lots going on in regard to `xreg`!

Maybe a really simple fix could be just to ensure it is a matix within `forecast()`, like this: https://github.com/MilesMcBain/forecast/commit/1c3acf9c7693621382cc71a6a7fe5ac5bf27488e

Sorry if that was TMI, but I spent a lot of time nailing this down, so now you have to listen to the story of the bug that I caught.

**Comment by MilesMcBain** [comment]
PS even though it seems like this should be catastrophic for predict.Arima, that `xreg` never ends up being used for anything... it's just dead end code :hankey: . So no urgency.

**Comment by robjhyndman** [comment]
Thanks Miles. Even though the help file says xreg should be a matrix, we should capture the error. Doing a straight `as.matrix()` will work if there are only numerical values in xreg, but if it contains factors, that will cause issues which may not be apparent to the user. It is probably better to just force the user to do the conversion with an error message explaining what to do.

**Comment by MilesMcBain** [comment]
Sounds sensible :+1:

**Comment by tararae7** [comment]
Excellent information here, but I am getting the same warning with or without converting to a matrix and all of my regressor values are numeric. I am stumped. 
 
Warning message:
In cbind(intercept = rep(1, n), xreg) :
  number of rows of result is not a multiple of vector length (arg 2)

Regressors
Unemployment, Temperature, Amount Sold

When i take out the Unemployment regressor the warning goes away. Any ideas?

This is the structure of my xreg

> str(xreg_forecast)
'data.frame':	40 obs. of  3 variables:
 $ Unemployment   : num  
 $ Avg_Temperature: num  
 $ Total_Sold: num

**Comment by robjhyndman** [comment]
Fixed in https://github.com/robjhyndman/forecast/commit/a36021348edd09d1bd4874f4cd7683c9aed9e05e

@tararae7 : it must be a matrix, not a data frame.
