### ISSUE TITLE
Out-of-sample residuals for nnetar forecast PI

### ISSUE THREAD

**Issue by gabrielcaceres** [robjhyndman/forecast#692]
Curious about your thoughts on including an option in `forecast.nnetar` to bootstrap out-of-sample residuals when calculating prediction intervals.

I recently [answered a question on stackoverflow](https://stackoverflow.com/questions/50098866/r-narrow-prediction-intervals-when-forecasting-with-nnetar/) about dealing with `nnetar` prediction intervals that are unrealistically narrow. Posting the suggestions made me think that it could be a useful addition to `forecast.nnetar` (I calculated the out-of-sample residuals with `CVar` and then passed them using the `innov` argument).

While on one hand I feel like it could be helpful, particularly since the current prediction intervals can often be quite narrow, I also worry it might get a bit cumbersome to include too many arguments and calculations. Adding more arguments (say a `cv.innov` flag plus any other CV related arguments) could be confusing, especially if they're unique to just `nnetar` forecasts, in addition to slowing down the PI computation even more by recalculating the model multiple times.

Alternatively, we could simply add an example to illustrate how it can be done.

Any thoughts?

**Comment by robjhyndman** [comment]
Rather than add more options, I think it would be better to give an example to show how CV errors could be used via the innov argument. Something like this:

```r
# Fit model
fit <- nnetar(USAccDeaths, size=2, repeats=50)
# Set up new innovations using cross-validation
fit_test_cv <- CVar(USAccDeaths,  size=2, repeats=50) 
res_sd <- sd(fit_test_cv$residuals, na.rm=TRUE) 
myinnovs <- rnorm(24*100, mean=0, sd=res_sd)
# Forecast using new innovations
fit_test_fc <- forecast(fit, h=24, PI=TRUE, npaths=100, innov=myinnovs) 
plot(fit_test_fc)
```
