### ISSUE TITLE
tsCV does not support multivariate forecast methods

### ISSUE THREAD

**Issue by alexcombessie** [robjhyndman/forecast#693]
This is mainly to confirm my understanding of the [doc](https://cran.r-project.org/web/packages/forecast/forecast.pdf):
![screen shot 2018-05-15 at 17 52 42](https://user-images.githubusercontent.com/4739848/40071519-e91a97fa-5868-11e8-9aea-ffc7ccab2fe4.png)

At the moment, tsCV does not support multivariate mforecast objects, correct?

**Comment by robjhyndman** [comment]
That is correct.

**Comment by alexcombessie** [comment]
Thanks Rob!
