### ISSUE TITLE
ndiffs with "adf" test results in error.

### ISSUE THREAD

**Issue by orcu** [robjhyndman/forecast#695]
```
ndiffs(WWWusage, test="adf")
Error in xy.coords(x, y, setLab = FALSE) : 'x' and 'y' lengths differ
```

Also affects the auto.arima function.

**Comment by mitchelloharawild** [comment]
This has been fixed in the development version.

**Comment by avsdev-cw** [comment]
Any chance of merging this (very trivial) fix (https://github.com/robjhyndman/forecast/commit/3838f78b5de40ec4c413d1fc22d7ae25848eaf58) into 8.3 stable branch? From our (customers) point of view this is a very problematic and breaking regression (they are not happy to switch to master as it is already delivered)

**Comment by mitchelloharawild** [comment]
An update to CRAN will happen soon. It is also necessary to resolve some issues with the next version of ggplot2.
