### ISSUE TITLE
xreg is rank deficient Error while doing auto.arima

### ISSUE THREAD

**Issue by 123saga** [robjhyndman/forecast#699]
Hi @robjhyndman, 
I am running the following snippet in a loop. in few instance I am receiving the following error.
`Error in auto.arima(a, xreg = b) : xreg is rank deficient`  Could you please help me in understanding the error better. 

**a and b in an error scenario:**
`a is time series`

`Qtr1       Qtr2       Qtr3       Qtr4
1  49775.900  39473.920  22219.080  18756.150
2  25969.300  16864.650  27190.050  27727.250
3  19155.100  13979.700  18888.200  18041.650
4  46214.300  29888.950   7250.480  17743.450
5   8813.270  -9866.660  25981.020      0.000
6      0.000   1095.969      0.000      0.000
7  23818.161  30738.710  81058.047 133312.094`

`b is a matrix`

` Q-1       Q-2 Q-3 Q-4         Q0
 1: 0.0000000 0.0000000   0   0 0.00000000
 2: 0.0000000 0.0000000   0   0 0.00000000
 3: 0.0000000 0.0000000   0   0 0.00000000
 4: 0.0000000 0.0000000   0   0 0.00000000
 5: 0.0000000 0.0000000   0   0 0.00000000
 6: 0.0000000 0.0000000   0   0 0.00000000
 7: 0.0000000 0.0000000   0   0 0.00000000
 8: 0.0000000 0.0000000   0   0 0.00000000
 9: 0.0000000 0.0000000   0   0 0.00000000
10: 0.0000000 0.0000000   0   0 0.00000000
11: 0.0000000 0.0000000   0   0 0.00000000
12: 0.0000000 0.0000000   0   0 0.00000000
13: 0.0000000 0.0000000   0   0 0.00000000
14: 0.0000000 0.0000000   0   0 0.00000000
15: 0.0000000 0.0000000   0   0 0.00000000
16: 0.0000000 0.0000000   0   0 0.00000000
17: 0.0000000 0.0000000   0   0 0.00000000
18: 0.0000000 0.0000000   0   0 0.00000000
19: 0.0000000 0.0000000   0   0 0.00000000
20: 0.0000000 0.0000000   0   0 0.00000000
21: 0.0000000 0.0000000   0   0 0.00000000
22: 0.0000000 0.0000000   0   0 0.00000000
23: 0.0000000 0.0000000   0   0 0.00000000
24: 0.0000000 0.0000000   0   0 0.00000000
25: 0.0000000 0.0000000   0   0 0.00000000
26: 0.0000000 0.0000000   0   0 0.70461721
27: 0.7046172 0.0000000   0   0 0.17423047
28: 0.1742305 0.7046172   0   0 0.09846093`

**Comment by robjhyndman** [comment]
You appear to have a column in `xreg` with all zeros.

**Comment by sakshisharma28** [comment]
@robjhyndman

**Comment by robjhyndman** [comment]
Remove the offending column. If you have a column with all zeros, get rid of it.

**Comment by AbhishekHP2016** [comment]
Hi Professor,

Thanks for helping us.
I am facing the same issue:
xreg is rank deficient but I should not get rid of columns with zeros because it was obtained after one-hot encoding.

So, I was wondering how to resolve this. 
In order to explain in detail, 
I had 6 columns where Data and Output are 1st and the last column.
Rest 4 columns are Countries, Car models, Pincode and Names.
When I tranformed this using **one-hot encoding**, It turned to 103 coulmns from 6 columns. 
Due to onehot encoding, most columns are zeroes.

**Comment by GDC997** [comment]
Hello prof.,
I have the same issue but not having any zero column. 
Can you help me?

**Comment by robjhyndman** [comment]
Rank deficiencies can occur when you have a constant column, or two columns the same.

**Comment by GDC997** [comment]
> Rank deficiencies can occur when you have a constant column, or two columns the same.
In my case I have 6 columns that are open, high, low, volume, market cap and average daily price. They are neither the same nor constants. It's strange.

**Comment by antonysamuelb** [comment]
In my case, I had columns that were exact complements of each other. That too caused this issue.
