### ISSUE TITLE
R: time series Error in attributes(best.model$errors) <- attributes(origy) : invalid time series parameters specified

### ISSUE THREAD

**Issue by jasperDD** [robjhyndman/forecast#702]
I perform time series analysis
mydat=structure(list(id = c(1030879980L, 1030879980L, 1030879980L, 
1030879980L, 1030879980L, 1030879980L, 1030879980L, 1030879980L, 
1030879980L, 1030879980L, 1030879980L, 1030880090L, 1030880090L, 
1030880090L, 1030880090L, 1030880090L, 1030880090L, 1030880090L, 
1030880090L, 1030880090L, 1030879980L, 1030879980L, 1030879980L, 
1030879980L, 1030879980L, 1030879980L, 1030879980L, 1030879980L, 
1030879980L, 1030879980L, 1030879980L, 1030880090L, 1030880090L, 
1030880090L, 1030880090L, 1030880090L, 1030880090L, 1030880090L, 
1030880090L, 1030880090L), variable = structure(c(1L, 1L, 1L, 
1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 
1L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 
2L, 2L, 2L, 2L, 2L), .Label = c("Jan.14", "Jan.15"), class = "factor"), 
    value = c(170L, 265L, 571L, 961L, 0L, 418L, 70L, 278L, 68L, 
    164L, 454L, 180L, 349L, 125L, 368L, 286L, 64L, 179L, 187L, 
    46L, 170L, 265L, 571L, 961L, 0L, 418L, 70L, 278L, 68L, 164L, 
    454L, 180L, 349L, 125L, 368L, 286L, 64L, 179L, 187L, 46L)), .Names = c("id", 
"variable", "value"), class = "data.frame", row.names = c(NA, 
-40L))

msts <- msts(mydat$value, seasonal.periods = c(2014,1),start = 12)
tbats <- tbats(msts)
and i get error
Error in attributes(best.model$errors) <- attributes(origy) : 
  invalid time series parameters specified
In addition: Warning message:
In tbats(msts) :
  Missing values encountered. Using longest contiguous portion of time series

How to fix this error?

**Comment by mitchelloharawild** [comment]
I can't reproduce this issue. Are you using the latest version?

**Comment by jasperDD** [comment]
I just now have updated forecast pack, this error was fixed, but
Warning message:
In bats(as.numeric(y), use.box.cox = use.box.cox, use.trend = use.trend,  :
  optim() did not converge.
what does this mean
Here the real data

[timeseries.zip](https://github.com/robjhyndman/forecast/files/2098471/timeseries.zip)

**Comment by robjhyndman** [comment]
This is not a general help site. Ask generic R questions at stackoverflow.com and use this site to report bugs.
