### ISSUE TITLE
error in refitting stlm model to the whole training set with xreg

### ISSUE THREAD

**Issue by ndricca** [robjhyndman/forecast#704]
I would like to use a previously fitted stlm model with "arima" method and a matrix of regressors on the whole training set, but I am encountering an error. Here a reproducible example:
`library(forecast)
set.seed(12345)

xa <- sample(c(0,1),length(wineind),replace = T,prob = c(0.2,0.8))
xb <- sample(c(0,1),length(wineind),replace = T,prob = c(0.99,0.01))
t1 <- window(wineind, end = c(1989,12))
xa1 <- xa[1:length(t1)]
xb1 <- xb[1:length(t1)]

m1 <- stlm(t1,method = "arima",
           robust = T,
           xreg = cbind(xa1,xb1),
           lambda = "auto")

t2 <- window(wineind, end = c(1992,12))
xa2 <- xa[1:length(t2)]
xb2 <- xb[1:length(t2)]

m2 <- stlm(t2,model = m1,xreg = cbind(xa2,xb2))`

The error is: "Error in arima2(x, model, xreg = xreg, method = method) : No regressors provided"

May anyone help me understand this?

Please apologize for crossposting with [stackoverflow](https://stackoverflow.com/questions/50910182/error-in-refitting-stlm-model-to-the-whole-training-set)

**Comment by robjhyndman** [comment]
Now fixed in https://github.com/robjhyndman/forecast/commit/31b7dc65881bb056e737124190c1b127347de0cf
