### ISSUE TITLE
Remove html vignette

### ISSUE THREAD

**Issue by robjhyndman** [robjhyndman/forecast#709]
The vignette on CRAN is a badly formatted html version: https://cran.r-project.org/web/packages/forecast/vignettes/JSS2008.html
It should be the pdf version. We need to figure this out before the next release.

**Comment by mitchelloharawild** [comment]
winbuilder is giving this issue on the fixed version.
Do you know if it is possible to set version requirements for pandoc?

> Error: processing vignette 'JSS2008.Rmd' failed with diagnostics:
> pandoc version 2.2 or higher is required and was not found (see the help page ?rmarkdown::pandoc_available).
> Execution halted

**Comment by robjhyndman** [comment]
This shouldn't happen if the pdf is part of the submission. We can't rely on pandoc being available. See http://r-pkgs.had.co.nz/vignettes.html#vignette-cran
