### ISSUE TITLE
rwf(drift = TRUE) overwrites "upper"/"lower" column names

### ISSUE THREAD

**Issue by andybega** [robjhyndman/forecast#712]
Hello, this is maybe bordering on pedantic, but it caused a bug for me:

```
f1 <- forecast(rwf(gold[1:60], h=50))
colnames(f1$upper)
```

Gives `[1] "80%" "95%"`

When I set `drift = TRUE`, the column names change:

```
f2 <- forecast(rwf(gold[1:60], h=50, drift = TRUE))
colnames(f2$upper)
```

Output:

```
[1] "(fc$upper - fc$mean) * ratio.(fc$upper - fc$mean).fc$upper.80%"
[2] "(fc$upper - fc$mean) * ratio.(fc$upper - fc$mean).fc$upper.95%"
```

Looks like with drift they are overwritten when the original forecast is adjusted in `lagwalk()` in [`naive.R`](https://github.com/robjhyndman/forecast/blob/master/R/naive.R). 

This is with the current version on CRAN, 8.4.

**Comment by mitchelloharawild** [comment]
Thanks, should be fixed now.
