### ISSUE TITLE
Question: lag in auto.arima forecast creation

### ISSUE THREAD

**Issue by sllevy** [robjhyndman/forecast#714]
Hi Professor Hyndman,

Is it possible to induce a lag of one period while creating an ARIMA model with the Arima() or auto.arima() functions? I would like to create an ARIMA model which forecasts yt+1 from observations yt-1, yt-2, yt-3, etc. -- I would like to introduce a lag of one period, so that yt is not considered in the model when forecasting yt+1.

Additionally, if this is possible, after creating this altered model, will the calculated MAPE value from accuracy() use this "lagged" forecasted value? That is, if I am calculating the MAPE value for the month of May, will the function then use the value fitted without consuming April data?

I have read through the details you have provided in the documentation for the forecast package and your Forecasting: principles and practice and have not found a solution.

Thank you for your help!

**Comment by robjhyndman** [comment]
No. This is called "direct forecasting", as distinct from "recursive forecasting". The forecast package only does recursive forecasting.
