### ISSUE TITLE
No suitable ARIMA model found

### ISSUE THREAD

**Issue by sakshisharma28** [robjhyndman/forecast#716]
I have data on a daily basis. I created dummy variables for weekdays (mon, tue, wed, etc.) and holidays (just one column- 0,1)

My model is :
modArima <- auto.arima(x, xreg = cbind(holiday_train, weekday_train))

It give me the following error msg:
Error in auto.arima(x, xreg = cbind(holiday_train, weekday_train)) : 
  No suitable ARIMA model found

>colSums(weekday_train)
   Monday   Tuesday Wednesday  Thursday    Friday  Saturday    Sunday 
       65              65        65                      65           65        65               65 

Where am I going wrong?

**Comment by robjhyndman** [comment]
You should have one fewer columns than days of the week. See https://otexts.org/fpp2/useful-predictors.html#seasonal-dummy-variables

**Comment by sakshisharma28** [comment]
Thanks
