### ISSUE TITLE
Flexible tests for differences.

### ISSUE THREAD

**Issue by robjhyndman** [robjhyndman/forecast#717]
Just a suggestion for possible future update: it would be convenient if auto.arima had an option to specify the use.lag for ur.kpss and the critical threshold for seas. -- David Reilly

**Comment by mitchelloharawild** [comment]
Most support for this is added in 17953321acc49e40d85c19c8849e74ff8fef72db
Threshold for seas needs further thinking for the functionality of `seas.heuristic`

**Comment by davidreilly007** [comment]
Hi Rob, Mitchell,

Thanks again for implementing my suggestion. I really appreciate it!

I tried the following:

ap=ts(AirPassengers,start=c(1949,1),frequency=12)
x=log(ap)
fit <- auto.arima(x,test.args= list(use.lag = trunc(10*sqrt(length(x))/14)))

and get:

Warning message:
In value[[3L]](cond) :
  The chosen test encountered an error, so no differencing is selected. Check the time series data.

**Comment by mitchelloharawild** [comment]
Specifying use.lag for kpss tests should now be possible (cfb4bd286d68d9aa1c3da5864e497d29296d40f6)

**Comment by davidreilly007** [comment]
Thanks Mitchell!

**Comment by davidreilly007** [comment]
Hi Mitchell, Rob,

We have an issue in that we do not know the length of dx for ndiffs.  So would it be possible to modify the argument to specify one of four options: ts_short, ts_long, ur_short, or ur_long?

**Comment by mitchelloharawild** [comment]
It you wanted this level of flexibility, I would prefer to use function
inputs rather than character inputs.

**Comment by davidreilly007** [comment]
That will work!

**Comment by davidreilly007** [comment]
Update, I will be fine with the current enhancement to experiment with different values of use.lag.  Thank you for providing that capability.

**Comment by mitchelloharawild** [comment]
We still wanted to experiment with different thresholds for the seasonal test, right?

**Comment by davidreilly007** [comment]
Possibly.  I'm still crunching SEAS versus MASE for D=0 and D=1 for M4.  It will be another day or two.

**Comment by davidreilly007** [comment]
Hi Mitchell, after reviewing the seas heuristic threshold with M4 there is no clear benefit from adjusting for frequency.
