### ISSUE TITLE
forecast.lm not handling missing values

### ISSUE THREAD

**Issue by robjhyndman** [robjhyndman/forecast#718]
```r
> library(fpp2)
> fit <- tslm(mens400 ~ trend)
> forecast(fit)
   Point Forecast Lo 80 Hi 80 Lo 95 Hi 95
1        42.04231    NA    NA    NA    NA
2        41.78402    NA    NA    NA    NA
3        41.52572    NA    NA    NA    NA
4        41.26742    NA    NA    NA    NA
5        41.00913    NA    NA    NA    NA
6        40.75083    NA    NA    NA    NA
7        40.49254    NA    NA    NA    NA
8        40.23424    NA    NA    NA    NA
9        39.97595    NA    NA    NA    NA
10       39.71765    NA    NA    NA    NA
```

**Comment by mitchelloharawild** [comment]
This is because predict.lm computes the variance of the residuals without removing NA values.
Should these be removed before calling predict.lm? My view is that the user should remove it from mens400 or predict.lm should change.

**Comment by robjhyndman** [comment]
I tend to think they should be removed before the call to predict.lm. Even better would be for predict.lm to change, but that's pretty unlikely. I don't like to push this back to the user.
