### ISSUE TITLE
Inconsistent tsclean results in version 8.3 vs 8.4

### ISSUE THREAD

**Issue by nblaffey** [robjhyndman/forecast#719]
I recently reran a script that called tsclean on a PC with version 8.4 of forecast installed. Despite having the same input and running the same code, I got different results from tsclean. The data contained a single large outlier and overall the results were very close at all points except the outlier where the discrepancy was largest. Was there any updates in 8.4 (or even an older version) that could have possibly led to changes in the output of tsclean?

**Comment by robjhyndman** [comment]
There was a change introduced in 8.3 that would have modified the output from tsclean. It now uses mstl to do the decomposition, with a different s.window than was used before.

**Comment by nblaffey** [comment]
Thank you for the clarification.
