### ISSUE TITLE
Issue with tslm

### ISSUE THREAD

**Issue by AnscombesGimlet** [robjhyndman/forecast#720]
Hi - I am getting NAs returned from forecasting this and some of the other annual series using M3 data. 
See:
</br>
```lambda <- BoxCox.lambda(M3[[8]]$x)```
</br>
```h <- M3[[8]]$h```
</br>
```x <- BoxCox(M3[[8]]$x, lambda = lambda)```
</br>
```tslm.forecast <- forecast(tslm(x ~ trend), h = h, lambda = lambda)$mean```
</br>
```tslm.forecast```
</br>
The above code will work on M3[[7]] for reference.

**Comment by mitchelloharawild** [comment]
It is better to specify transformations when fitting the model.

```{r}
library(Mcomp)
lambda <- BoxCox.lambda(M3[[8]]$x)
h <- M3[[8]]$h
x <- M3[[8]]$x
tslm.forecast <- forecast(tslm(x ~ trend, lambda = lambda), h = h)
tslm.forecast %>% autoplot
```

The NA values occur when backtransforming your forecasts because all of the forecasts satisfy:
```{r}
  if (lambda < 0) {
    x[x > -1 / lambda] <- NA
  }
```
