### ISSUE TITLE
Supporting `plotly` for interactive plots?

### ISSUE THREAD

**Issue by Gayyam** [robjhyndman/forecast#729]
Hi,

I was introduced to the several timeseries visualisation plots while reading fpp2 (especially chapter 2) online. I was wondering if you would be interested in adding `plotly`  support to some of the plots like `seassonplot` or `subseriesplot`?

I am willing to be guided and can have a crack at writing some of the functions.

Thanks

**Comment by robjhyndman** [comment]
Just use ggseasonplot followed by ggplotly. No need to add other plotly support.

**Comment by Gayyam** [comment]
I find the conversion of ggplot to plotly to be imperfect at times. Consider `ggseasonplot` for instance.

Using it on `fpp2::a10` with `year.labels` on both sides, we get - 
![ggpplotly](https://user-images.githubusercontent.com/9971062/44142178-86739eae-a0d3-11e8-887a-414eadb1caf6.png)

whereas the native `plotly` version looks something like this - 
![plotly](https://user-images.githubusercontent.com/9971062/44142165-7de6cad6-a0d3-11e8-8639-f265e390180e.png)

For completeness' sake, here's the native `ggseasonplot` output.
![ggplot](https://user-images.githubusercontent.com/9971062/44142205-a41e5a2a-a0d3-11e8-93cd-8cb8b4df8d13.png)

As can be seen, the legend has been needlessly added in the `ggplotly` output. I think the non interactive plot is the best looking, whereas if you restrict the competition to interactive ones, `plotly` is arguably better.

An added advantage of using plotly natively is [speed](https://www.r-bloggers.com/comparing-plotly-ggplotly-plot-generation-times/) , although I'm not sure how much of a focus plotting speed is to the vision of `forecast`.

**Comment by robjhyndman** [comment]
I think it is good enough. In any case, you should be aware that the forecast package is being superceded by the fable package (github.com/tidyverts/fable); the forecast package will continue to be maintained but not extended. Plotting in the fable package is still under development, but having good integration with plotly is an important objective.
