### ISSUE TITLE
Upper prediction intervals are not finite

### ISSUE THREAD

**Issue by PurplePolarbear123** [robjhyndman/forecast#731]
Im am creating a SARIMAX model using the Arima() function with daily data. I want to forecast my model using the forecast () function and have made many successful forecasts using this function.

fcast<-  forecast(fit4, xreg=cbind(.......all xreg included in model fit 4.....), h=20)

However, I have tried to forecast one of my final models and I have now received a warning message as follows:

In forecast.Arima(fit4, xreg= cbind(, 
Upper prediction intervals are not finite

which then means that the confidence intervals aren't plotted on my forecast plot.

The model I have fitted has orders of (1,1,7)(1,1,1)[7] with many xreg time series as explanatory variables including two dummy variables accounting for certain events in the month.

I am new to time series modelling so I am not sure what is needed to know how to fix this issue.

Thankyou

**Comment by robjhyndman** [comment]
Most likely the model is degenerate in some way -- possibly the MA(7) in the non-seasonal part of the model is confounded with the MA(1) in the seasonal part.
