### ISSUE TITLE
Forecasting Test Dataset Manually

### ISSUE THREAD

**Issue by alstat** [robjhyndman/forecast#733]
I have the following model:
```
BV = -3851.172 * TMAX + 0.9912 * TOURIST + eta
```
where
```
eta = error - 0.6899 * error[t-1]
```
where `error ~ NID(0, 7.66e+10)`, where `sigma^2 = 7.66e+10`.

I can do forecasting in the testing dataset using the `forecast` function. However, I want to do the forecasting manually in the testing dataset instead of using the `forecast` function. Here is my initial code:

```r
f_test <- eta <- error <- c(); 
eta[1] <- error[1] <- rnorm(1, 0, sqrt(7.66e+10))
for (i in 2:nrow(testing)) {
    error[i] <- rnorm(1, 0, sqrt(7.66e+10))
    eta[i] <- error[i] - 0.6899 * error[i - 1]
    f_test[i] <- -3851.172 * testing[i, "TMAX"] + 0.9912 * testing[i, "Tourist"] + eta[i] - error[i]
}
```
Is this correct? I'm not getting close (given that error is randomly generated in this case) forecast values with that of `forecast` function.

**Comment by robjhyndman** [comment]
This is not a help site. Please ask questions on stackoverflow.com
