### ISSUE TITLE
ets forecast error: missing value where TRUE/FALSE needed

### ISSUE THREAD

**Issue by nickgriffith** [robjhyndman/forecast#734]
Getting the following error when running forecast() on an AAN damped model. Error message is unclear. Let me know if this is a bug or if my issue should be posted elswhere (help forum). Thanks. 

R Version: 3.4.0

Code for reproducting error: 
train <- ts(c(5,52,28,210,206,406,352,349,304,394,335,377,558,425,595,727,748,785,1127,1398,985,415), frequency = 12);
model.des <- ets(train,model="AAN", damped = 0.9);
fc.des = forecast(model.des, h=18);

Error in if (damped) H[1, 2] <- par["phi"] else H[1, 2] <- 1 : 
  missing value where TRUE/FALSE needed

**Comment by robjhyndman** [comment]
Presumably you mean `forecast(model.des, h=18)`.
