### ISSUE TITLE
snaive very slow with long seasonal periods

### ISSUE THREAD

**Issue by robjhyndman** [robjhyndman/forecast#739]
```r
x <- ts(rnorm(2000), frequency=365)
system.time(snaive(x))
```

**Comment by robjhyndman** [comment]
Most likely due to implementation via `arima()`. Probably better to write our own code, rather than rely on `stats:arima()` to handle this.

**Comment by mitchelloharawild** [comment]
Slowdown appears to be coming from the predict method.
![image](https://user-images.githubusercontent.com/16127127/46384684-e02d7800-c6fa-11e8-88e9-c3d243857812.png)

**Comment by mitchelloharawild** [comment]
Resolved in #759
