### ISSUE TITLE
Problems with the vignette

### ISSUE THREAD

**Issue by AHoerner** [robjhyndman/forecast#740]
When I look at the vignette on Cran using the Firefox or Chrome browser, or using the R vignette function in the RStudio help window, the math is pretty badly mangled. I have pasted a copy of the "Point forecasts" section. The cut and paste strips off some of the font formatting, but otherwise this is pretty much what I see: latex code instead of rendered math. 

A few things render, but not correctly. For example, the "y1,y2," etc in the first line is rendered as if it were.a subscript, below the line and in tiny characters. 

Point forecasts for all methods
We denote the observed time series by y1,y2,…,yn. A forecast of yt+h based on all of the data up to time t is denoted by ^yt+h|t. To illustrate the method, we give the point forecasts and updating equations for method (A,A), the Holt-Winters' additive method: \begin{subequations}\label{eq:AMmethod}\vspace{-15pt} \begin{align} \mbox{Level:}\quad &\ellt = \alpha (y_t - s{t-m}) + (1-\alpha)(\ell{t-1} + b{t-1})\hspace{1cm} \label{eq:3-44a}\ \mbox{Growth:}\quad &b_t = \beta^(\ellt - \ell{t-1}) + (1-\beta*)b_{t-1} \label{eq:3-45a}\ \mbox{Seasonal:}\quad &st = \gamma(y_t - \ell{t-1} -b{t-1}) + (1-\gamma)s{t-m}\label{eq:3-46a}\ \mbox{Forecast:}\quad &\hat{y}{t+h|t} = \ell_t + b_th +s{t-m+hm+}. \label{eq:3-47a} \end{align} \end{subequations} where m is the length of seasonality (e.g., the number of months or quarters in a year), ℓt represents the level of the series, bt denotes the growth, st is the seasonal component, $\hat{y}{t+h|t}$ is the forecast for h periods ahead, and h+m=[(h−1) mod m]+1. To use method (???), we need values for the initial states ℓ0, b0 and s1−m,…,s0, and for the smoothing parameters α, β∗ and γ. All of these will be estimated from the observed data.
Equation (???) is slightly different from the usual Holt-Winters equations such as those in @MWH3 or @BOK05. These authors replace (???)withst=γ∗(yt−ℓt)+(1−γ∗)st−m.If ℓt is substituted using (???), we obtainst=γ∗(1−α)(yt−ℓt−1−bt−1)+{1−γ∗(1−α)}st−m.Thus, we obtain identical forecasts using this approach by replacing γ in (???) with γ∗(1−α). The modification given in (???) was proposed by @OKS97 to make the state space formulation simpler. It is equivalent to Archibald's (1990)\nocite{Archibald90} variation of the Holt-Winters' method.
\begin{sidewaystable} \begin{small} \begin{center} \begin{tabular}{|c|lll|} \hline & \multicolumn{3}{c|}{Seasonal} \ {Trend} & \multicolumn{1}{c}{N} & \multicolumn{1}{c}{A} & \multicolumn{1}{c|}{M}\ \cline{2-4} & \(\ell_t = \alpha y_t + (1-\alpha) \ell_{t-1}\) & \(\ell_t = \alpha (y_t - s_{t-m}) + (1-\alpha) \ell_{t-1}\) & \(\ell_t = \alpha (y_t / s_{t-m}) + (1-\alpha) \ell_{t-1}\)\ {N} & & \(s_t = \gamma (y_t - \ell_{t-1}) + (1-\gamma) s_{t-m}\) & \(s_t = \gamma (y_t / \ell_{t-1}) + (1-\gamma) s_{t-m}\) \ & \(\hat{y}_{t+h|t} = \ell_t\) & \(\hat{y}_{t+h|t} = \ell_t + s_{t-m+h_m^+}\) & \(\hat{y}_{t+h|t}= \ell_ts_{t-m+h_m^+}\) \ \hline & \(\ell_t = \alpha y_t + (1-\alpha) (\ell_{t-1}+b_{t-1})\) & \(\ell_t = \alpha (y_t - s_{t-m}) + (1-\alpha) (\ell_{t-1}+b_{t-1})\) & \(\ell_t = \alpha (y_t / s_{t-m}) + (1-\alpha) (\ell_{t-1}+b_{t-1})\)\ {A} & \(b_t = \beta^* (\ell_t-\ell_{t-1}) + (1-\beta^*) b_{t-1}\) & \(b_t = \beta^* (\ell_t-\ell_{t-1}) + (1-\beta^*) b_{t-1}\) & \(b_t = \beta^* (\ell_t-\ell_{t-1}) + (1-\beta^*) b_{t-1}\)\ & & \(s_t = \gamma (y_t - \ell_{t-1}-b_{t-1}) + (1-\gamma) s_{t-m}\) & \(s_t = \gamma (y_t / (\ell_{t-1}-b_{t-1})) + (1-\gamma) s_{t-m}\)\ & \(\hat{y}_{t+h|t} = \ell_t+hb_t\) & \(\hat{y}_{t+h|t} = \ell_t +hb_t +s_{t-m+h_m^+}\) & \(\hat{y}_{t+h|t}= (\ell_t+hb_t)s_{t-m+h_m^+}\) \ \hline & \(\ell_t = \alpha y_t + (1-\alpha) (\ell_{t-1}+\phi b_{t-1})\) & \(\ell_t = \alpha (y_t - s_{t-m}) + (1-\alpha) (\ell_{t-1}+\phi b_{t-1})\) & \(\ell_t = \alpha (y_t / s_{t-m}) + (1-\alpha) (\ell_{t-1}+\phi b_{t-1})\)\ {A\damped } & \(b_t = \beta^* (\ell_t-\ell_{t-1}) + (1-\beta^*) \phi b_{t-1}\) & \(b_t = \beta^* (\ell_t-\ell_{t-1}) + (1-\beta^*) \phi b_{t-1}\) & \(b_t = \beta^* (\ell_t-\ell_{t-1}) + (1-\beta^*) \phi b_{t-1}\)\ & & \(s_t = \gamma (y_t - \ell_{t-1}-\phi b_{t-1}) + (1-\gamma) s_{t-m}\) & \(s_t = \gamma (y_t / (\ell_{t-1}-\phi b_{t-1})) + (1-\gamma) s_{t-m}\)\ & \(\hat{y}_{t+h|t} = \ell_t+\dampfactor b_t\) & \(\hat{y}_{t+h|t} = \ell_t+\dampfactor b_t+s_{t-m+h_m^+}\) & \(\hat{y}_{t+h|t}= (\ell_t+\dampfactor b_t)s_{t-m+h_m^+}\) \ \hline & \(\ell_t = \alpha y_t + (1-\alpha) \ell_{t-1}b_{t-1}\) & \(\ell_t = \alpha (y_t - s_{t-m}) + (1-\alpha) \ell_{t-1}b_{t-1}\) & \(\ell_t = \alpha (y_t / s_{t-m}) + (1-\alpha) \ell_{t-1}b_{t-1}\)\ {M} & \(b_t = \beta^* (\ell_t/\ell_{t-1}) + (1-\beta^*) b_{t-1}\) & \(b_t = \beta^* (\ell_t/\ell_{t-1}) + (1-\beta^*) b_{t-1}\) & \(b_t = \beta^* (\ell_t/\ell_{t-1}) + (1-\beta^*) b_{t-1}\)\ & & \(s_t = \gamma (y_t - \ell_{t-1}b_{t-1}) + (1-\gamma) s_{t-m}\) & \(s_t = \gamma (y_t / (\ell_{t-1}b_{t-1})) + (1-\gamma) s_{t-m}\)\ & \(\hat{y}_{t+h|t} = \ell_tb_t^h\) & \(\hat{y}_{t+h|t} = \ell_tb_t^h + s_{t-m+h_m^+}\) & \(\hat{y}_{t+h|t}= \ell_tb_t^hs_{t-m+h_m^+}\) \ \hline & \(\ell_t = \alpha y_t + (1-\alpha) \ell_{t-1}b^\phi_{t-1}\) & \(\ell_t = \alpha (y_t - s_{t-m}) + (1-\alpha)\ell_{t-1}b^\phi_{t-1}\) & \(\ell_t = \alpha (y_t / s_{t-m}) + (1-\alpha)\ell_{t-1}b^\phi_{t-1}\)\ {M\damped } & \(b_t = \beta^* (\ell_t/\ell_{t-1}) + (1-\beta^*) b^\phi_{t-1}\) & \(b_t = \beta^* (\ell_t/\ell_{t-1}) + (1-\beta^*) b^\phi_{t-1}\) & \(b_t = \beta^* (\ell_t/\ell_{t-1}) + (1-\beta^*) b^\phi_{t-1}\)\ & & \(s_t = \gamma (y_t - \ell_{t-1}b^\phi_{t-1}) + (1-\gamma) s_{t-m}\) & \(s_t = \gamma (y_t / (\ell_{t-1}b^\phi_{t-1})) + (1-\gamma) s_{t-m}\)\ & \(\hat{y}_{t+h|t} = \ell_tb_t^{\phi_h}\) & \(\hat{y}_{t+h|t} = \ell_tb_t^{\phi_h} + s_{t-m+h_m^+}\) & \(\hat{y}_{t+h|t}= \ell_tb_t^{\phi_h}s_{t-m+h_m^+}\) \ \hline \end{tabular} \end{center} \end{small}
\caption{Formulae for recursive calculations and point forecasts. In each case, ℓt denotes the series level at time t, bt denotes the slope at time t, st denotes the seasonal component of the series at time t, and m denotes the number of seasons in a year; α, β∗, γ and ϕ are constants, ϕh=ϕ+ϕ2+⋯+ϕh and h+m=[(h−1) mod m]+1.}\label{table:pegels} \end{sidewaystable}
Table ??? gives recursive formulae for computing point forecasts h periods ahead for all of the exponential smoothing methods. Some interesting special cases can be obtained by setting the smoothing parameters to extreme values. For example, if α=0, the level is constant over time; if β∗=0, the slope is constant over time; and if γ=0, the seasonal pattern is constant over time. At the other extreme, naïve forecasts (i.e., ^yt+h|t=yt for all h) are obtained using the (N,N) method with α=1. Finally, the additive and multiplicative trend methods are special cases of their damped counterparts obtained by letting ϕ=1.

**Comment by robjhyndman** [comment]
I'm aware of the issue and it will be fixed in the next CRAN update
