### ISSUE TITLE
Allow auto.arima to return approximate model (not refit using ML)

### ISSUE THREAD

**Issue by robjhyndman** [robjhyndman/forecast#741]
See http://disq.us/p/1wby4q4

**Comment by mitchelloharawild** [comment]
I think it's best to more appropriately handle the `method` argument, so that the final model is always fit using the method specified by `method`.

Thoughts?

**Comment by davidreilly007** [comment]
method="CSS-ML" might be confusing.  I assume that would be the same as "ML"?
