### ISSUE TITLE
Error with one of the M4 Monthly data

### ISSUE THREAD

**Issue by davidreilly007** [robjhyndman/forecast#742]
library(forecast)

library(M4comp2018)
data(M4) #load data
names(M4[[1]])
M4.sub <- Filter(function(l) l$period == "Monthly", M4)
x <- M4.sub[[14369]]$x

aarimafit <- auto.arima(x)

Error in `[<-`(`*tmp*`, k, , value = c(p, d, q - 1, P, D, Q, constant,  : 
  subscript out of bounds

**Comment by mitchelloharawild** [comment]
@robjhyndman 
Any preference for how this should be approached?
This series has tried >94 unique models in the search.

Should the bound be removed, or should the search stop immediately once the limit has been reached?

**Comment by robjhyndman** [comment]
It is not clear to me why this is generating an error. The loop is supposed to stop if k gets too big.

We could probably update the size to something larger (maybe 200?)

If the limit is reached, I suggest we return the best model found along with a warning.

**Comment by mitchelloharawild** [comment]
The issue is that the loop condition isn't checked on every new fit. As inside the loop >1 models are considered, then k can increase from <94 to >94.

**Comment by mitchelloharawild** [comment]
I'll add a `nmodels` argument with a warning if the limit is hit.
