### ISSUE TITLE
Export Wh Forecasting using R 

### ISSUE THREAD

**Issue by MaySKTN** [robjhyndman/forecast#743]
Hi all, 

I am doing project on forecasting data of export Wh. I tried to use ARIMA method but still could not get the forecasted data of export Wh. 

My objective: 
Data are from Pacan's street -get export Wh of gas meters from neighbour homes. 
Since the existing plot (till 01-Apr-2016 04:59:58)  are increasing over period, I expect there will be up-down plot for next 8 months (which means predict till end of 31-Dec-2016 11:59:59) 
That forecast will be used for learning purpose that I have learned how to predict using R. 

In the original csv file, there are 1,584,823 total records, with 157 meters.
Recorded from 1-Oct-2015 00:05:10 to 01-Apr-2016 04:59:58

In the csv file, there are three columns: local minutes, dataID, meter_value.

Export Wh means for meter_value, 
DataID  means for each meter ID 

Original csv file (org_data.csv) that I m analyzing can be found in this link:
[https://drive.google.com/open?id=12a3EfbSKKuPRAYUC-c58tbnBaiVlweVI 

[ALL.pdf](https://github.com/robjhyndman/forecast/files/2454240/ALL.pdf)-plotting all 157 meters using existing data. 

I tried using ARIMA method to forecast next 24 hours but I could not get the forecasted meter_value. 

I appreciate your help, to get the forecasted meter_value. 

```
sensor_data <- data.table::fread("org_data.csv") #For this big CSV file(0.056GB), “data.table::fread” is *much* faster than “read.csv”, Read 1,584,823 rows and 3 columns in 5sec.
 
sensor_data <- sensor_data %>% mutate(localminute =lubridate::as_datetime(localminute),dataid=factor(dataid)) # convert dataid (integer type) to factor type # convert localminute to datetime (fread imports it as character)

str(sensor_data)  #sensor_data is original data set 
sensor_dataTS = ts(sensor_data$localminute)
meterValueTS = ts(sensor_data$meter_value)
Alldata <- data.frame(sensor_dataTS,sensor_data$dataid,meterValueTS)
arima_fit=auto.arima(Alldata[,1])
arima_forecast = forecast(arima_fit, h = 10)
#output as below
Point Forecast      Lo 80      Hi 80      Lo 95      Hi 95
1584824     1459486811 1459484733 1459488890 1459483633 1459489990
1584825     1459486825 1459483762 1459489888 1459482141 1459491509
1584826     1459486838 1459483004 1459490673 1459480974 1459492702
1584827     1459486852 1459482351 1459491353 1459479968 1459493735
1584828     1459486865 1459481761 1459491970 1459479059 1459494672
1584829     1459486879 1459481213 1459492544 1459478214 1459495543
1584830     1459486892 1459480697 1459493088 1459477417 1459496367
1584831     1459486906 1459480203 1459493608 1459476655 1459497156
1584832     1459486919 1459479727 1459494111 1459475920 1459497918
1584833     1459486932 1459479265 1459494600 1459475206 1459498659
```

**Comment by robjhyndman** [comment]
This is not a help site. Please ask such questions on crossvalidated.com or stackoverflow.com
