### ISSUE TITLE
Ability to create custom opt.crit functions?  

### ISSUE THREAD

**Issue by dclengacher** [robjhyndman/forecast#744]
For experimentation, this would be a great feature to design our own and link to them within the etc(), auto.arima(), and aroma()  models.

**Comment by mitchelloharawild** [comment]
Good idea - with the development of the [fable package](https://github.com/tidyverts/fable), new functionality will not be added to the forecast package (bugfixing will continue). I've moved this issue to the fable repository, where I think this feature will be useful.
https://github.com/tidyverts/fable/issues/84
