### ISSUE TITLE
NSE scoping of getResponse.Arima searches too far

### ISSUE THREAD

**Issue by davidreilly007** [robjhyndman/forecast#747]
```r
library(forecast)
library(fpp2)

xreg <- cbind(MaxTemp = elecdaily[, "Temperature"],
              MaxTempSq = elecdaily[, "Temperature"]^2,
              Workday = elecdaily[, "WorkDay"])

fit_st <- auto.arima(elecdaily[, "Demand"], xreg = xreg)


Error in NextMethod(.Generic) : 
  dims [product 365] do not match the length of object [366]
In addition: Warning message:
In `-.default`(x, xreg %*% as.matrix(object$coef[(norder + 1):length(object$coef)])) :
  longer object length is not a multiple of shorter object length
```

**Comment by davidreilly007** [comment]
Hi Rob, that’s strange.  The issue occurred on the latest Github but not on 8.5.  Also on the latest R, RStudio, Rtools and all packages.

Maybe I have some lurking variables.  I’ll see what I can find.

**Comment by mitchelloharawild** [comment]
I also cannot reproduce this issue with the current github version of forecast and fpp2.

**Comment by davidreilly007** [comment]
I am stumped.  I replicate on two different machines (both 64 bit versions of R 3.5.1, running windows 10, latest Github version of forecast).

When I turn trace on:
fit_st <- auto.arima(elecdaily[, "Demand"], xreg = xreg, trace=TRUE)

I get:

** Fitting models using approximations to speed things up...

 Regression with ARIMA(2,1,2)(1,0,1)[7] errors : 2442.105
 Regression with ARIMA(0,1,0)           errors : 2534
 Regression with ARIMA(1,1,0)(1,0,0)[7] errors : 2490.112
 Regression with ARIMA(0,1,1)(0,0,1)[7] errors : 2499.747
 ARIMA(0,1,0)                              : 2531.962
 Regression with ARIMA(2,1,2)(0,0,1)[7] errors : 2475.42
 Regression with ARIMA(2,1,2)(1,0,0)[7] errors : 2460.363
 Regression with ARIMA(2,1,2)(2,0,1)[7] errors : 2341.105
 Regression with ARIMA(2,1,2)(2,0,0)[7] errors : 2349.072
 Regression with ARIMA(2,1,2)(2,0,2)[7] errors : 2327.677
 Regression with ARIMA(1,1,2)(2,0,2)[7] errors : 2361.457
 Regression with ARIMA(2,1,1)(2,0,2)[7] errors : Inf
 Regression with ARIMA(3,1,2)(2,0,2)[7] errors : Inf
 Regression with ARIMA(2,1,3)(2,0,2)[7] errors : Inf
 Regression with ARIMA(1,1,1)(2,0,2)[7] errors : 2360.616
 Regression with ARIMA(1,1,3)(2,0,2)[7] errors : 2356.799
 Regression with ARIMA(3,1,1)(2,0,2)[7] errors : Inf
 Regression with ARIMA(3,1,3)(2,0,2)[7] errors : Inf
 ARIMA(2,1,2)(2,0,2)[7]                    : 2325.659
 ARIMA(2,1,2)(1,0,2)[7]                    : 2431.378
 ARIMA(2,1,2)(2,0,1)[7]                    : 2339.212
 ARIMA(2,1,2)(1,0,1)[7]                    : 2440.621
 ARIMA(1,1,2)(2,0,2)[7]                    : 2359.355
 ARIMA(2,1,1)(2,0,2)[7]                    : Inf
 ARIMA(3,1,2)(2,0,2)[7]                    : Inf
 ARIMA(2,1,3)(2,0,2)[7]                    : Inf
 ARIMA(1,1,1)(2,0,2)[7]                    : 2358.551
 ARIMA(1,1,3)(2,0,2)[7]                    : 2354.661
 ARIMA(3,1,1)(2,0,2)[7]                    : Inf
 ARIMA(3,1,3)(2,0,2)[7]                    : Inf

 Now re-fitting the best model(s) without approximations...

 ARIMA(2,1,2)(2,0,2)[7]                    : Inf
 Regression with ARIMA(2,1,2)(2,0,2)[7] errors : Inf
 ARIMA(2,1,2)(2,0,1)[7]                    : Inf
 Regression with ARIMA(2,1,2)(2,0,1)[7] errors : Inf
 Regression with ARIMA(2,1,2)(2,0,0)[7] errors : 2424.151Error in NextMethod(.Generic) : 
  dims [product 365] do not match the length of object [366]
In addition: Warning message:
In `-.default`(x, xreg %*% as.matrix(object$coef[(norder + 1):length(object$coef)])) :
  longer object length is not a multiple of shorter object length
> **

Any ideas?

**Comment by davidreilly007** [comment]
Thanks for the suggestion. 

> library(devtools)
> install_github("robjhyndman/forecast")
Skipping install of 'forecast' from a github remote, the SHA1 (a1ce31d1) has not changed since last install.
  Use `force = TRUE` to force installation
> install_github("robjhyndman/fpp2-package")
Skipping install of 'fpp2' from a github remote, the SHA1 (df7c93ea) has not changed since last install.
  Use `force = TRUE` to force installation
> remove(elecdaily)
Warning message:
In remove(elecdaily) : object 'elecdaily' not found
> library(forecast)
> library(fpp2)
Loading required package: ggplot2
Loading required package: fma
Loading required package: expsmooth
> xreg <- cbind(MaxTemp = elecdaily[, "Temperature"], MaxTempSq = elecdaily[, "Temperature"]^2, Workday = elecdaily[, "WorkDay"])
> fit_st <- auto.arima(elecdaily[, "Demand"], xreg = xreg, trace=TRUE)

 Fitting models using approximations to speed things up...

 Regression with ARIMA(2,1,2)(1,0,1)[7] errors : 2442.105
 Regression with ARIMA(0,1,0)           errors : 2534
 Regression with ARIMA(1,1,0)(1,0,0)[7] errors : 2490.112
 Regression with ARIMA(0,1,1)(0,0,1)[7] errors : 2499.747
 ARIMA(0,1,0)                              : 2531.962
 Regression with ARIMA(2,1,2)(0,0,1)[7] errors : 2475.42
 Regression with ARIMA(2,1,2)(1,0,0)[7] errors : 2460.363
 Regression with ARIMA(2,1,2)(2,0,1)[7] errors : 2341.105
 Regression with ARIMA(2,1,2)(2,0,0)[7] errors : 2349.072
 Regression with ARIMA(2,1,2)(2,0,2)[7] errors : 2327.677
 Regression with ARIMA(1,1,2)(2,0,2)[7] errors : 2361.457
 Regression with ARIMA(2,1,1)(2,0,2)[7] errors : Inf
 Regression with ARIMA(3,1,2)(2,0,2)[7] errors : Inf
 Regression with ARIMA(2,1,3)(2,0,2)[7] errors : Inf
 Regression with ARIMA(1,1,1)(2,0,2)[7] errors : 2360.616
 Regression with ARIMA(1,1,3)(2,0,2)[7] errors : 2356.799
 Regression with ARIMA(3,1,1)(2,0,2)[7] errors : Inf
 Regression with ARIMA(3,1,3)(2,0,2)[7] errors : Inf
 ARIMA(2,1,2)(2,0,2)[7]                    : 2325.659
 ARIMA(2,1,2)(1,0,2)[7]                    : 2431.378
 ARIMA(2,1,2)(2,0,1)[7]                    : 2339.212
 ARIMA(2,1,2)(1,0,1)[7]                    : 2440.621
 ARIMA(1,1,2)(2,0,2)[7]                    : 2359.355
 ARIMA(2,1,1)(2,0,2)[7]                    : Inf
 ARIMA(3,1,2)(2,0,2)[7]                    : Inf
 ARIMA(2,1,3)(2,0,2)[7]                    : Inf
 ARIMA(1,1,1)(2,0,2)[7]                    : 2358.551
 ARIMA(1,1,3)(2,0,2)[7]                    : 2354.661
 ARIMA(3,1,1)(2,0,2)[7]                    : Inf
 ARIMA(3,1,3)(2,0,2)[7]                    : Inf

 Now re-fitting the best model(s) without approximations...

 ARIMA(2,1,2)(2,0,2)[7]                    : Inf
 Regression with ARIMA(2,1,2)(2,0,2)[7] errors : Inf
 ARIMA(2,1,2)(2,0,1)[7]                    : Inf
 Regression with ARIMA(2,1,2)(2,0,1)[7] errors : Inf
 Regression with ARIMA(2,1,2)(2,0,0)[7] errors : 2424.151Error in NextMethod(.Generic) : 
  dims [product 365] do not match the length of object [366]
In addition: Warning message:
In `-.default`(x, xreg %*% as.matrix(object$coef[(norder + 1):length(object$coef)])) :
  longer object length is not a multiple of shorter object length
> sessionInfo()
R version 3.5.1 (2018-07-02)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                           LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] fpp2_2.3        expsmooth_2.3   fma_2.3         ggplot2_3.0.0   forecast_8.5    devtools_1.13.6

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.19      urca_1.3-0        pillar_1.3.0      compiler_3.5.1    git2r_0.23.0      plyr_1.8.4        tseries_0.10-45   tools_3.5.1      
 [9] xts_0.11-1        digest_0.6.17     memoise_1.1.0     tibble_1.4.2      gtable_0.2.0      nlme_3.1-137      lattice_0.20-35   rlang_0.2.2      
[17] rstudioapi_0.8    curl_3.2          parallel_3.5.1    withr_2.1.2       httr_1.3.1        lmtest_0.9-36     grid_3.5.1        nnet_7.3-12      
[25] R6_2.3.0          TTR_0.23-4        magrittr_1.5      scales_1.0.0      quantmod_0.4-13   timeDate_3043.102 colorspace_1.3-2  fracdiff_1.4-2   
[33] quadprog_1.5-5    lazyeval_0.2.1    munsell_0.5.0     crayon_1.3.4      zoo_1.8-4

**Comment by davidreilly007** [comment]
Note that when I revert to CRAN 8.4, it works fine.

**Comment by davidreilly007** [comment]
First, cool trick with the debug statement.  Thanks!

Browse[2]> dim(xreg)
[1] 365   4
Browse[2]> head(xreg)
Time Series:
Start = c(1, 1) 
End = c(1, 6) 
Frequency = 7 
         drift xreg.MaxTemp xreg.MaxTempSq xreg.Workday
1.000000     1         26.0         676.00            0
1.142857     2         23.0         529.00            1
1.285714     3         22.2         492.84            1
1.428571     4         20.3         412.09            0
1.571429     5         26.1         681.21            0
1.714286     6         19.6         384.16            1
Browse[2]> tail(xreg)
Time Series:
Start = c(52, 3) 
End = c(53, 1) 
Frequency = 7 
         drift xreg.MaxTemp xreg.MaxTempSq xreg.Workday
52.28571   360         20.1         404.01            0
52.42857   361         22.2         492.84            0
52.57143   362         31.2         973.44            0
52.71429   363         26.2         686.44            1
52.85714   364         24.4         595.36            1
53.00000   365         25.5         650.25            1
Browse[2]> length(x)
[1] 366
Browse[2]> head(x)
        Jan    Feb    Mar    Apr    May    Jun
1985 3057.3 3346.3 3861.1 3577.0 4296.5 5691.6
Browse[2]> tail(x)
        Jan    Feb    Mar    Apr    May    Jun
2015 1186.2 1554.5 1641.1 1204.9 1835.2 1759.8

**Comment by robjhyndman** [comment]
OK. It looks like your response variable is being over-written by something else with 366 observations rather than 365 observations.  What do you get with `head(elecdaily)` and `tail(elecdaily)`? Also please provide the output of `search()` and `ls()` after the error occurs.

**Comment by mitchelloharawild** [comment]
I've found the issue: it is due to bad NSE in `getResponse.Arima` that extracts the wrong value for `x`.

MRE:
``` r
library(forecast)
library(fpp2)
#> Loading required package: ggplot2
#> Loading required package: fma
#> Loading required package: expsmooth

x <- USAccDeaths
xreg <- cbind(MaxTemp = elecdaily[, "Temperature"],
              MaxTempSq = elecdaily[, "Temperature"]^2,
              Workday = elecdaily[, "WorkDay"])

fit_st <- auto.arima(elecdaily[, "Demand"], xreg = xreg)
#> Error in `-.default`(x, xreg %*% as.matrix(object$coef[(norder + 1):length(object$coef)])): time-series/vector length mismatch
```

Created on 2018-10-11 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by robjhyndman** [comment]
OK, I was getting there with my request for `search()` and `ls()`. Can you please fix it.

**Comment by mitchelloharawild** [comment]
More minimal/local example:

``` r
library(forecast)
x <- rnorm(10)
auto.arima(mdeaths, xreg = fdeaths)
#> Error in `-.default`(x, xreg %*% as.matrix(object$coef[(norder + 1):length(object$coef)])): time-series/vector length mismatch
```

Created on 2018-10-11 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by davidreilly007** [comment]
Rob, Mitchell, thanks for taking care of this.  I'll give it a test run when fixed.

Question, why did this occur on my machine(s) but not yours?

**Comment by robjhyndman** [comment]
Presumably because you had an object called `x` in your workspace.

**Comment by davidreilly007** [comment]
Yes, that's it!
