### ISSUE TITLE
Bug in residuals with mstl and lambda=0

### ISSUE THREAD

**Issue by davidreilly007** [robjhyndman/forecast#748]
library(forecast)
ap=ts(AirPassengers,start=c(1949,1),frequency=12)
ap.stl <- mstl(ap,lambda=0)
ap.stl.for <- forecast(ap.stl,h=24,method="arima",lambda=0)
ap.stl.for$residuals

rowse[5]> ap.stl.for$residuals
          Jan      Feb      Mar      Apr      May      Jun      Jul      Aug      Sep      Oct      Nov      Dec
1949 107.2863 113.2625 127.1005 124.1476 116.1521 130.0610 142.9769 142.9898 131.1080 114.2260  99.3548 113.2209

Fitted is ok, but the x data needs to be transformed before:
  fcast$residuals <- fcast$x - fcast$fitted

I assume that, as usual, you want the transformed residuals, not the InvBoxCox.

**Comment by davidreilly007** [comment]
I said fitted was ok, but looking again they are not ok.  They are way off.

**Comment by robjhyndman** [comment]
There are some other issues here as well, possibly related:

```{r}
ap.stl <- mstl(ap,lambda=0)
ap.stl.for <- forecast(ap.stl,h=24,method="arima")
plot(ap.stl.for)
```

```{r}
ap.stl.for <- forecast(ap.stl,h=24,method="arima", lambda=0)
plot(ap.stl.for)
```
