### ISSUE TITLE
auto.arima producing non-gaussian residuals

### ISSUE THREAD

**Issue by Jakobhenningjensen** [robjhyndman/forecast#751]
It seems like auto.arima does not always produce gaussian residuals. How is the estimate found in that case?

**Comment by robjhyndman** [comment]
Estimation does not require Gaussian errors, even when a Gaussian likelihood is being used. A Gaussian likelihood is almost the same as least squares and will give consistent estimates for any error distribution with finite variance.

The only time that the distribution of residuals really matters is when producing prediction intervals. If the residuals are not Gaussian, the default prediction intervals will not necessarily have the correct coverage. But then you can set `bootstrap=TRUE` and get bootstrapped prediction intervals which are based on the empirical distribution of the residuals.
