### ISSUE TITLE
simulate.Arima doesn't work with non-stationary specification

### ISSUE THREAD

**Issue by tamas-ferenci** [robjhyndman/forecast#752]
My understanding is that `simulate.Arima`˙is supposed to work with non-stationary specifications as well, however, this doesn't seem to be the case:

    simulate( Arima( ts( rnorm( 1000 ) ), order = c( 1, 0, 0 ), fixed = c( phi = 2 ),
      include.mean = FALSE ), nsim = 1000, future = FALSE )

(I followed the logic presented [here](https://robjhyndman.com/hyndsight/simulating-from-a-specified-seasonal-arima-model/).)

**Comment by robjhyndman** [comment]
You specify non-stationarity using the differencing operators, not by setting phi outside the stationary region.

**Comment by robjhyndman** [comment]
If you just want to simulate from an AR(1), write your own code. It is easy. See exercise 6 at https://otexts.org/fpp2/arima-exercises.html

**Comment by tamas-ferenci** [comment]
@robjhyndman Thanks, but I originally hoped that `simulate.Arima` would solve this problem generally for any ARMA(p,q) model... (without manual coding, which is of course an option).

**Comment by robjhyndman** [comment]
I'm afraid not.

**Comment by tamas-ferenci** [comment]
@robjhyndman OK, thank you very much for your prompt response!
