### ISSUE TITLE
Can I create a python implementation of the entire package ?

### ISSUE THREAD

**Issue by Ic3fr0g** [robjhyndman/forecast#754]
## What?
I want to create a python implementation of this package.

## Why?
There is a lack of good python libraries that support time-series analysis and forecasting models. For example, `prophet` is limited by daily forecasting, `statsmodels.tsa` supports ARIMA models, `pyflux` supports GARCH models and `scikit-learn` does not have forecasting models. In short, there's no library out there that is quite like `forecast` for R, having metrics, models, seasonal-plots, etc. all in one place. Creating an implementation in python will help to compare statistical models with deep learning models in the same environment. Moreover, this would be a great project to include native ways to handle multivariate time-series forecasting, XGBoost Regression (à la `forecastxgb`) and possibly even LSTMs.

Would you accept a pull request for the same? Or would you rather it be a different repository?

**Comment by robjhyndman** [comment]
In principle I am ok with a python version of the package provided it remains GPL-licensed. However, we are currently rewriting the package from scratch (https://github.com/tidyverts/fable) and some of that work might be better ported than the older forecast package code.

Unfortunately, I don't have time to be actively involved. It would be best to be a different repo.

**Comment by Ic3fr0g** [comment]
Wow! I just spent an entire afternoon looking at tidyverts and all repos associated with it. This is fantastic but it's going to take me a while to get started.
