### ISSUE TITLE
not able to apply the hybrid model on new data

### ISSUE THREAD

**Issue by jenlygao** [robjhyndman/forecast#755]
I used one time series (ts_training) to fit a hybridModel, and would like to apply the model to new data (ts). But it doesn't seem to work. forecast(ts, model=fit, h=1) throws the error "not known model class". Please help. Thanks.
fit <- hybridModel(ts_training, models = "et", weights = "insample.errors", errorMethod = "MASE")
out <- forecast(ts, model=fit, h=1)

**Comment by robjhyndman** [comment]
Wrong package. hybridModel is part of the forecastHybrid package.
