### ISSUE TITLE
ggAcf for multivariate time-series

### ISSUE THREAD

**Issue by tvatter** [robjhyndman/forecast#760]
I am trying to get the Acf for multivariate time-series, e.g.:
```
forecast::ggAcf(fpp2::uschange)
```
But it returns the following error message:
```
Error in if (data$Lag[1] == 0 && object$type == "correlation") { : 
  missing value where TRUE/FALSE needed
```
Any idea what might be wrong? I have the latest version of R and of the forecast package installed.

**Comment by mitchelloharawild** [comment]
Multivariate ACF plotting with `ggAcf` currently isn't supported. I'll add this functionality for parity with `Acf`

**Comment by mitchelloharawild** [comment]
Once PR #761 is merged, it should be possible to do this now.

``` r
library(forecast)
Acf(fpp2::uschange)
```

![](https://i.imgur.com/pFkP2Ip.png)

``` r
ggAcf(fpp2::uschange)
```

![](https://i.imgur.com/1WrMpAA.png)

``` r
Pacf(fpp2::uschange)
```

![](https://i.imgur.com/nP7qKxM.png)

``` r
ggPacf(fpp2::uschange)
```

![](https://i.imgur.com/Ile0BtE.png)

<sup>Created on 2018-11-20 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>
