### ISSUE TITLE
checkresiduals() cannot find residuals for snaive()

### ISSUE THREAD

**Issue by EconProf** [robjhyndman/forecast#765]
library(fpp2)
beer <- window(ausbeer, start = 1992)
fc <- snaive(beer)
checkresiduals(fc)

returns "Error in checkresiduals(fc) : No residuals found" in the 8.5 development version. It works in version 8.4.

This is my first GitHub issue post, so please let me know if this is the wrong place or format.

**Comment by robjhyndman** [comment]
Thanks John. This is exactly how you should report problems, with a simple reproducible example. We will get it fixed asap.

**Comment by mitchelloharawild** [comment]
Great first issue, it was indeed a mistake with the recent changes to snaive, naive, and rwf.
It can be easier to produce reproducible examples using the [reprex package](https://github.com/tidyverse/reprex), however it more-or less produces the same result as what you have provided.

## Before

``` r
library(fpp2)
#> Loading required package: ggplot2
#> Loading required package: forecast
#> Loading required package: fma
#> Loading required package: expsmooth
beer <- window(ausbeer, start = 1992)
fc <- snaive(beer)
checkresiduals(fc)
#> Error in checkresiduals(fc): No residuals found
```

<sup>Created on 2018-12-30 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

## After

``` r
library(fpp2)
#> Loading required package: ggplot2
#> Loading required package: forecast
#> Loading required package: fma
#> Loading required package: expsmooth
beer <- window(ausbeer, start = 1992)
fc <- snaive(beer)
checkresiduals(fc)
#> 
#>  Ljung-Box test
#> 
#> data:  Residuals from Seasonal naive method
#> Q* = 32.269, df = 8, p-value = 8.336e-05
#> 
#> Model df: 0.   Total lags used: 8
```
![](https://i.imgur.com/7GyXC3K.png)

<sup>Created on 2018-12-30 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>
