### ISSUE TITLE
Revised kpss lag default with log AirPassengers

### ISSUE THREAD

**Issue by davidreilly007** [robjhyndman/forecast#776]
auto.arima now gives (2,0,0) (0,1,1) with drift, rather than the classical (0,1,1) (0,1,1).

**Comment by mitchelloharawild** [comment]
I've reverted the change for now, as I'm working on a push to CRAN (fixing some changes made in the upcoming version of R) and this needs further thought.

**Comment by davidreilly007** [comment]
Thanks Mitchell!  I look forward to seeing any future developments on this.
