### ISSUE TITLE
Quantile Error when using PI = TRUE and boxcox transformation in fit method using nnetar

### ISSUE THREAD

**Issue by AdityaRon** [robjhyndman/forecast#778]
Error in the forecast method while using PI = TRUE in nnetar.

fit = nnetar(x_stats[x_stats$X__objectId == 'XXXXXXXXXXX',][,10], lambda="auto", scale.inputs = TRUE),
 forecast = forecast(fit, h =30, level = 90, PI = TRUE, bootstrap = TRUE, npaths=100)

Error in quantile.default(newX[, i], ...) : 
  missing values and NaN's not allowed if 'na.rm' is FALSE

The fit method runs fine but I believe while doing simulations to generate the Prediction Interval we are running into the above stated error.

**Comment by mitchelloharawild** [comment]
Please provide a minimally reproducible example (https://www.tidyverse.org/help/).

It looks to work fine on the `lynx` dataset.
``` r
library(forecast)
nnetar(lynx, lambda = "auto", scale.inputs = TRUE) %>% 
  forecast(h = 30, level = 90, PI=TRUE, bootstrap = TRUE, npaths = 100)
#>      Point Forecast      Lo 90     Hi 90
#> 1935      3968.0375 3114.60179 4460.9421
#> 1936      3567.8116 2727.28918 4487.9306
#> 1937      1013.5804  627.41362 1588.8839
#> 1938       180.6393  101.32434  285.5965
#> 1939       145.8745   66.17553  212.2266
#> 1940       159.1772   79.54315  246.0927
#> 1941       225.8460  104.87757  492.9950
#> 1942       426.1107  185.62585 1481.1613
#> 1943      1228.8252  482.83084 3218.5239
#> 1944      2903.8750 1184.35128 5158.8522
#> 1945      4061.2879 2422.71037 5297.4533
#> 1946      3083.4136 1301.39540 4110.7583
#> 1947      1136.0081  516.32611 1740.6744
#> 1948       391.3985  145.70127  496.2380
#> 1949       329.8370  120.38536  460.5515
#> 1950       418.7615  158.20584  696.8428
#> 1951       932.9771  357.31637 1910.0504
#> 1952      1927.0122  748.72381 3123.6509
#> 1953      2784.1672 1670.56618 4652.0807
#> 1954      4426.4024 2872.51661 6233.2645
#> 1955      3710.1980 1561.65453 5950.8310
#> 1956      1597.0135  692.36423 4103.1516
#> 1957       655.2334  245.04988 1602.6991
#> 1958       335.6340  115.38133  496.9331
#> 1959       208.4336   88.97759  437.9501
#> 1960       368.7197  125.17445 1048.5186
#> 1961       795.0371  211.38421 2286.6028
#> 1962      1779.1530  340.08617 3726.4252
#> 1963      3376.9272  802.27565 4864.3193
#> 1964      4168.8544 1476.72305 5499.8465
```

<sup>Created on 2019-02-21 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by AdityaRon** [comment]
library(tidyverse)
#> Warning: package 'dplyr' was built under R version 3.5.1

data = c(0.002462333,
         0.002399763,
         0.002479442,
         0.002472447,
         0.001778820,
         0.001022061,
         0.001086568,
         0.001055917,
         0.001285278,
         0.001055037,
         0.001059742,
         0.001068711,
         0.001068838,
         0.001091119,
         0.001090023,
         0.003728220,
         0.004104825,
         0.004059515,
         0.005133325,
         0.004175806,
         0.004309640,
         0.004186098,
         0.004174362,
         0.004171816,
         0.004182172,
         0.004183899,
         0.004194499,
         0.004219197,
         0.004205973,
         0.004210140,
         0.004150385,
         0.004890672,
         0.004618897,
         0.004491290,
         0.001626662,
         0.001572917,
         0.001565940,
         0.005102964,
         0.003222867,
         0.002254940,
         0.001373915,
         0.001388403,
         0.001392120,
         0.001408384,
         0.001410213,
         0.001415421,
         0.001427885,
         0.001439469,
         0.001444361,
         0.001459017,
         0.001761851,
         0.001650718,
         0.001660917,
         0.001618616,
         0.001649464,
         0.001635187,
         0.001630823,
         0.001376236)

fit = nnetar(data,lambda = "auto")
#> Error in nnetar(data, lambda = "auto"): could not find function "nnetar"
forecast(fit,h=30,level=90,PI=TRUE)
#> Error in forecast(fit, h = 30, level = 90, PI = TRUE): could not find function "forecast"

**Comment by mitchelloharawild** [comment]
Fixed MRE:
---
``` r
library(forecast)

data = c(0.002462333,
         0.002399763,
         0.002479442,
         0.002472447,
         0.001778820,
         0.001022061,
         0.001086568,
         0.001055917,
         0.001285278,
         0.001055037,
         0.001059742,
         0.001068711,
         0.001068838,
         0.001091119,
         0.001090023,
         0.003728220,
         0.004104825,
         0.004059515,
         0.005133325,
         0.004175806,
         0.004309640,
         0.004186098,
         0.004174362,
         0.004171816,
         0.004182172,
         0.004183899,
         0.004194499,
         0.004219197,
         0.004205973,
         0.004210140,
         0.004150385,
         0.004890672,
         0.004618897,
         0.004491290,
         0.001626662,
         0.001572917,
         0.001565940,
         0.005102964,
         0.003222867,
         0.002254940,
         0.001373915,
         0.001388403,
         0.001392120,
         0.001408384,
         0.001410213,
         0.001415421,
         0.001427885,
         0.001439469,
         0.001444361,
         0.001459017,
         0.001761851,
         0.001650718,
         0.001660917,
         0.001618616,
         0.001649464,
         0.001635187,
         0.001630823,
         0.001376236)

fit = nnetar(data,lambda = "auto")
forecast(fit,h=30,level=90,PI=TRUE)
#> Error in quantile.default(newX[, i], ...): missing values and NaN's not allowed if 'na.rm' is FALSE
```

<sup>Created on 2019-02-21 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by AdityaRon** [comment]
It looks like quantile is used in producing lower and upper forecasts according to https://github.com/robjhyndman/forecast/blob/master/R/nnetar.R . I remember there was similar error with respect to auto.arima as well. Making na.rm = TRUE in lower and upper section could fix it may be? previous fix for auto.arima

https://github.com/robjhyndman/forecast/commit/8b67cf35aa702ebb41c558a4523b4b447fd0001a

**Comment by mitchelloharawild** [comment]
Looks like that would fix the issue, but we will need to investigate why the missing values are occurring in the first place.

**Comment by AdityaRon** [comment]
I believe it is happening only when I am using boxcox transformation for values that are already normalized and are very small. I am trying to forecast a percentage ranging from 0 - 100. The example where i ran into the issue happens to be one where the percentage is very low and applying boxcox transformation on top it is somehow leading to missing values?

**Comment by mitchelloharawild** [comment]
That's my suspicion too, but I will need to step through the code to confirm it.

**Comment by mitchelloharawild** [comment]
Fixed thanks.
