### ISSUE TITLE
autoplot with one forecast

### ISSUE THREAD

**Issue by robjhyndman** [robjhyndman/forecast#779]
```r
austres %>% hw(1) %>% autoplot()
```

**Comment by mitchelloharawild** [comment]
How do you feel about removing the forecast interval code in `autoplot.forecast()`, and using `geom_forecast()` instead (as is used by `autolayer.forecast()`)?

Colour arguments will need to be deprecated, as `geom_forecast()` only accepts one colour (and applies shading to it). autoplot.forecast() currently has an argument for the forecast line colour, and the interval colours.

``` r
library(forecast)
library(ggplot2)
austres %>% hw(1) %>% {autoplot(austres) + autolayer(.)}
```

![](https://i.imgur.com/cVrevIA.png)

<sup>Created on 2019-02-28 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by robjhyndman** [comment]
Sounds ok. Avoids some duplication which is good.
