### ISSUE TITLE
Add dynamic S3 registration for forecast generic with fablelite

### ISSUE THREAD

**Issue by mitchelloharawild** [robjhyndman/forecast#782]

**Comment by mitchelloharawild** [comment]
@robjhyndman 
Is it possible to change the class structure for Arima() objects to have a different subclass?
Instead of `"ARIMA"` which conflicts with fable, could we use `"arima"` or some other variant?

**Comment by robjhyndman** [comment]
Yes, this is only used internally as far as I know. So we can call it whatever we want. It was introduced to distinguish objects created by the forecast package from those created by the stats package.
