### ISSUE TITLE
ggCcf() fails to register na.action = na.pass

### ISSUE THREAD

**Issue by timothymodel** [robjhyndman/forecast#783]
When I attempt to use na.action = na.pass in the ggCcf() function, I get the following error: 

Error in `dimnames<-`(object$acf, list(NULL, object$snames, object$snames)) : 
  length of 'dimnames' [2] not equal to array extent

In the base ccf function (stats::ccf()), na.action = na.pass return proper results.

**Comment by robjhyndman** [comment]
Please provide a minimal reproducible example. The following works using the current github version:

```r
ggCcf(mdeaths, fdeaths, na.action=na.pass)
```

**Comment by timothymodel** [comment]
I did get it to work but in the process learned that I only receive this error when x and y were defined as DF$X and DF$Y rather separately as X and Y.

For example,

`X <- c(10, 15, 20, 1, 2, 0, 1, 3, NA, NA, NA, NA, 5, 1, 1)`
`Y <- c(10, 15, 20, NA, NA, NA, NA, 1, 2, 0, 1, 3, 5, 1, 1)`
`DF <- as.data.frame(cbind(X, Y))`
`ggCcf(x = DF$X, y = DF$Y, lag.max = 10, type = "correlation", plot = TRUE, na.action = na.pass)`

Thanks for the response.

**Comment by robjhyndman** [comment]
Thanks. That helped me track down the issue. Now fixed in https://github.com/robjhyndman/forecast/commit/5e1dd0797e54ff92b6b24e5d5751e2b91e39f221
