### ISSUE TITLE
Problem with auto.arima

### ISSUE THREAD

**Issue by mbanco** [robjhyndman/forecast#784]
Hi,
It seems to me that there is a problem when I use the forecast function, because the forecast it throws is inconsistent:

datos <- c(195604452.00, 160599506.00, 135322311.00, 154160556.00, 169070740.00, 168253197.00, 140658355.00, 137780852.00, 135403394.00, 168591150.00, 198584077.00, 227204286.00, 180556215.00, 165263511.00, 129456852.04, 144753813.64, 166643905.77, 176668161.35, 158053555.62, 141897394.36, 144800158.68, 167836612.34, 208804803.32, 201689210.16, 190075980.73, 167516319.57, 137313143.68, 142167781.18, 197590764.53, 192876711.00, 163662934.00, 133558120.00, 137391606.00, 157536647.00, 189444911.00);

y <- ts(datos, frequency = 12, start = c(2016, 2), class = 'ts');

t_arima <- auto.arima(y, xreg=NULL, stepwise=TRUE, lambda='auto');

forecast(t_arima, h=12, level=90)

Thanks!

**Comment by mitchelloharawild** [comment]
I am unable to reproduce this issue with the development version.
``` r
library(forecast)
library(purrr)
datos <- c(195604452.00, 160599506.00, 135322311.00, 154160556.00, 169070740.00, 168253197.00, 140658355.00, 137780852.00, 135403394.00, 168591150.00, 198584077.00, 227204286.00, 180556215.00, 165263511.00, 129456852.04, 144753813.64, 166643905.77, 176668161.35, 158053555.62, 141897394.36, 144800158.68, 167836612.34, 208804803.32, 201689210.16, 190075980.73, 167516319.57, 137313143.68, 142167781.18, 197590764.53, 192876711.00, 163662934.00, 133558120.00, 137391606.00, 157536647.00, 189444911.00);
y <- ts(datos, frequency = 12, start = c(2016, 2), class = 'ts');
map(1:10,
    function(...){
      t_arima <- auto.arima(y, xreg=NULL, stepwise=TRUE, lambda='auto');
      forecast(t_arima, h=12, level=90)
    }
) %>% 
  unique
#> [[1]]
#>          Point Forecast    Lo 90    Hi 90
#> Jan 2019       1.000076 1.000076 1.000076
#> Feb 2019       1.000076 1.000076 1.000076
#> Mar 2019       1.000076 1.000076 1.000076
#> Apr 2019       1.000076 1.000076 1.000076
#> May 2019       1.000076 1.000076 1.000076
#> Jun 2019       1.000076 1.000076 1.000076
#> Jul 2019       1.000076 1.000076 1.000076
#> Aug 2019       1.000076 1.000076 1.000076
#> Sep 2019       1.000076 1.000076 1.000076
#> Oct 2019       1.000076 1.000076 1.000076
#> Nov 2019       1.000076 1.000076 1.000076
#> Dec 2019       1.000076 1.000076 1.000076
```

<sup>Created on 2019-03-20 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by mitchelloharawild** [comment]
This issue is due to `stats::arima()` being dependent on scale (#756).
The automatically selected value for lambda is very extreme, leading to values with very small scale changes (which are not handled well by `stats::arima()`).

Using a more appropriate transformation (or none at all) will work much better for this series. Automatic Box-Cox transformation selection should be used with caution.
