### ISSUE TITLE
Inconsistent results following update

### ISSUE THREAD

**Issue by pseudorational** [robjhyndman/forecast#790]
I can't thank you enough for your painstaking work with the forecast package. 
I am writing because I have found the ets() and auto.arima() functions are behaving differently following the Jan 19, 2019 update to the forecast library. Is this to be expected?

To illustrate, 
`ets(AirPassengers,'AAA')$aicc # Old version: 1569.390; New version: 1570.729
auto.arima(AirPassengers)       # Selected model in old version is ARIMA(0,1,1)(0,1,0)[12] and in new is ARIMA(2,1,1)(0,1,0)[12] `

**Comment by robjhyndman** [comment]
There are often minor changes between versions. You can see all the changes to the ets function here, for example: https://github.com/robjhyndman/forecast/commits/master/R/ets.R

Major changes are listed at http://pkg.robjhyndman.com/forecast/news/index.html

On auto.arima, we modified the search algorithm in v8.5.
