### ISSUE TITLE
simulate.Arima with future = FALSE and nsim != model$nobs

### ISSUE THREAD

**Issue by ishisht** [robjhyndman/forecast#791]
I am trying to simulate data from the following Arima model:
`my.ts <- structure(c(-0.72710285274926, -0.636562243226358, -0.412713004464652, 
-0.20570216031996, 0.288262882236603, 0.587164108960259, 0.505851231820449, 
0.725133324351724, 0.536283849559325, 0.452109804992907, 0.27234025896445, 
0.0512870983858069, -0.123207435520391, -0.113830568990913, 0.0432590973005853, 
0.0543977566584668, 0.64579471070166, 0.674264371658353, 0.492724661853852, 
0.363813214210173, -0.142495893075002, -0.428640816193083, -0.351479505984154, 
-0.34177215615448, -0.11653737364848, 0.0644877896457769, -0.167275191542641, 
-0.343523787281245, -0.0272354100029988, 0.027205105330804, -0.430002579573372, 
-0.387403515545396, 0.113384485238563, 0.111117192936022, 0.0382076513928054, 
-0.0383802847674248, -0.0345928805691509, 0.31521432938814, 0.500590435481963, 
0.274349581196531, -0.0566772258443873, -0.301184602659325, -0.134577123956938, 
0.268293399213986, 0.226832549057356, 0.143901836956282, 0.430543515323571, 
0.367551186757243, -0.00667420505310279, -0.102429579073809, 
-0.0422583238557095, -0.00788146325462369, 0.035915723177176, 
-0.291145906223931, -0.440239639488505, -0.408442150064617, -0.0876272279644027, 
0.0784761243617915, 0.344972775818974, 0.35691581272597), .Tsp = c(1, 
4.6875, 16), class = "ts")`

`my.arima <- Arima(my.ts, order = c(2, 0.5, 1)`

Since the 'ar' part of the model is non-stationary, I cannot (easily) do this using stats::arima.sim. If I use simulate.Arima instead, it works fine with 'future = TRUE' (the default). However, when I set 'future = FALSE', it only works if nsim == my.arima$nobs, but I want to simulate with nsim != my.arima$nobs.
I am trying to do this in particular because simulate.Arima does not support the n.start argument that arima.sim uses to specify a 'burn-in' period, and the simulated time-series does indeed show unexpected behavior in the first few samples. Hence, what I would like to do is simulate a somewhat longer time series and discard the first few observations.

If I do set nsim != my.arima$nobs, I get the following error:
`Error in attr(x, "tsp") <- value : 
  invalid time series parameters specified`

I have traced the error to line 453 of simulate.R:
`tsp(sim) <- tsp(x)`
Obviously, this will give an error if length(sim) != length(x). If I semi-manually construct the model and change the call to arima.sim in line 451 from:
`sim <- ts(tail(arima.sim(model, nsim, innov = e), nsim) + xm)`
to:
`sim <- ts(tail(arima.sim(model, nsim, innov = e, n.start = sum(model$order), start.innov = f), nsim) + xm)`
then I do seem to obtain reasonable results.

I am pretty new to ARIMA models and time series analysis, so I am aware that what I am trying to do may be nonsensical. However, even in that case I would expect simulate.Arima to throw out a warning or a specific error message, rather than running into an external error.

**Comment by robjhyndman** [comment]
Thanks. Fixed in https://github.com/robjhyndman/forecast/commit/4e34ffc0cd712b17ee84790213e28e0e6d6a906a

Note that Arima does not handle fractional differencing, so your 0.5 is converted to 0 and your model is stationary.
