### ISSUE TITLE
multivariate package coming soon?

### ISSUE THREAD

**Issue by randomgambit** [robjhyndman/forecast#797]
@robjhyndman thanks for this amazing package. It is really useful (as well as the book)!

I wonder if you have any plans of writing a tidy `forecast_multivariate` package (VARs, etc) that would be the natural complement to `forecast`. What do you think?

Thanks!

**Comment by mitchelloharawild** [comment]
Tidy forecasting is currently being developed in the [fable](https://github.com/tidyverts/fable) package. VAR and VARMA models are actually going to be the next supported model classes. We're currently thinking about how this would be implemented in the fable framework.

**Comment by randomgambit** [comment]
@mitchelloharawild ha that is pretty cool. Is there anything I can test? Happy to help! do you have a timeline for this?

**Comment by mitchelloharawild** [comment]
Hard to say regarding a time estimate, the interface is mostly figured out however we still need to think more about how this works with the forecast distributions and plotting functionality.

**Comment by mitchelloharawild** [comment]
VAR models are now implemented in the fable package: https://fable.tidyverts.org/reference/VAR.html

It's more of a test/prototype for multivariate modelling in the framework, and so documentation is limited at the moment. Nonetheless, feel free to try it out.

Other multivariate models will be added in the second half of the year, after the first version of the package is put on CRAN.
