### ISSUE TITLE
Add ARAR

### ISSUE THREAD

**Issue by robjhyndman** [robjhyndman/forecast#8]
I would like an arar() function, or better still an ararma function().

See Newton-Parzen for details.

There is an arar() function already in the itsmr package.

**Comment by dashaub** [comment]
Is this something you'd still like to merge? Would you want an Rcpp implementation or take a plain R implementation?

The implementation in ismr has some troubles (e.g. arar(taylor) or arar(ausair)).

**Comment by robjhyndman** [comment]
This is on the long-term plans for addition. If someone was to write one, I'd include it. Faster is obviously better. I don't know what the best references are.
