### ISSUE TITLE
myarima.sim(model, nsim, x - oldxm, e = e), xm): time-series/vector length mismatch

### ISSUE THREAD

**Issue by GANESHSAMA** [robjhyndman/forecast#811]
There is an issue whenever I am trying to simulate by simulate.Arima function for ARIMA with drift and xreg of one regressor.
the dimension of xm and myariam.sim are not coming the same.

xreg=xreg, having one regressor
model=model_fit 
Series: y 
Regression with ARIMA(0,0,0)(0,1,1)[12] errors 

Coefficients:
         sma1      drift    xreg
      -0.6361  -18463168  0.4328
s.e.   0.4382    5237117  0.2331

sigma^2 estimated as 2.437e+17:  log likelihood=-708.71
AIC=1425.42   AICc=1426.85   BIC=1431.4
which is having drift .

to overcome this problem I tried before the simulation below code, now it is working properly

###Simulate auto.arima with drift
  if(!is.null(xreg))
  {
    if(is.element("drift", names(model_fit$auto.arima$coef)))
    {
      if(NROW(xreg)==sim_steps)
      {
        xreg_arima <-  data.frame(xreg, drift = 1:sim_steps)
      }
      else if(NROW(xreg)>sim_steps)
      {
        if(NCOL(xreg)!=1)
        {
          xreg <- data.frame(xreg);  xreg_arima<- data.frame(xreg[1:sim_steps,], drift = 1:sim_steps)
        }
        else {xreg_arima<- data.frame(xreg=xreg[1:sim_steps], drift = 1:sim_steps)}
      }
      else {stop("NROW of xreg is less than sim_steps")}
    }
    else{xreg_arima <-xreg}
  }
  else{xreg_arima <-NULL}

Now simulate(model_fit$auto.arima,xreg=xreg_arima,future=TRUE,nsim=sim_steps) is working.

**Comment by mitchelloharawild** [comment]
MRE:
``` r
library(forecast)
fit <- auto.arima(mdeaths + (1:72)*30, xreg = fdeaths)
simulate(fit, xreg = fdeaths)
#> Error in `+.default`(myarima.sim(model, nsim, x - oldxm, e = e), xm): time-series/vector length mismatch
```

<sup>Created on 2019-08-19 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by mitchelloharawild** [comment]
Thanks for the bug report!
