### ISSUE TITLE
Wrong forecasting with a moving average model

### ISSUE THREAD

**Issue by rafaospina** [robjhyndman/forecast#812]
I have a time series. I compute a moving average model using the ma() function. 
After that, I compute forecasting using the forecast() function. 
Because I am using a moving average model, I was expecting a line for the projection to the future. However, the output seems to be a forecast from an ets model.

Thus, a forecasting value using the ma model for a window of 5 should be:
y(t+1) =  ( y(t-4) + y(t-3) + y(t-2) + y(t-1) + y(t) ) / 5

**Comment by robjhyndman** [comment]
The ma function does not compute a moving average model. Read the help file.

The forecast function will use an ETS model by default if you pass it a time series. Again, read the help file.

There is no function in the forecast package which will use the average of the last five values as a forecast.
