### ISSUE TITLE
regularize regression with ARIMA errors

### ISSUE THREAD

**Issue by fissehab** [robjhyndman/forecast#816]
I am fitting regression with ARIMA errors using auto.arima. Since I suspect the models could be over-fit, I want to use regularization with it. Is it possible to implement lasso or elastic net regularization ?

**Comment by robjhyndman** [comment]
Not using the existing code.

**Comment by fissehab** [comment]
Thanks for the response.  Is there any resource that I can use that you are aware of?

**Comment by robjhyndman** [comment]
I don't know of anything.

**Comment by mitchelloharawild** [comment]
Closing as this package is retired is now in "retired" state. We are maintaining it, and doing any bug fixes, but not adding new features. Instead, we are working on the new fable package at https://fable.tidyverts.org.
