### ISSUE TITLE
Set project to retired

### ISSUE THREAD

**Issue by mitchelloharawild** [robjhyndman/forecast#819]
As fable is now on CRAN we should think about labelling forecast as retired.

> A retired package is no longer under active development, and a known better alternative is available. We will only make the necessary changes to ensure that retired packages remain on CRAN. No new features will be added, and only the most critical of bugs will be fixed.

**Comment by robjhyndman** [comment]
Yes, happy to do that and gently push people towards fable.

**Comment by stevehansen** [comment]
Wasn't this a bit soon? The fable package is still "experimental" so we have no stable package to choose from at the moment, this one is retired and the new one still being experimental.

**Comment by mitchelloharawild** [comment]
The `{fable}` package is currently in the maturing stage, meaning that the design of the core functionality is figured out and for the most part stable. It is too early to mark it as stable as there are more incremental improvements we plan to make (for example, having `fitted()` (possibly with an option) return a fable with distributions instead of point predictions.

The `{forecast}` package is retired/superceded, meaning that while no new features will be added it will continue to be available and make necessary bug fixes. In this sense `{forecast}` is more stable than it has ever been, as the only development being done on it is to make it more stable.
