### ISSUE TITLE
Thetaf: seasonality detected, failure

### ISSUE THREAD

**Issue by catapulta** [robjhyndman/forecast#820]
Hi, I found an issue when trying to forecast a bad-behaving time-series. Here's the MRE (please note that the 1s are spaced by frequency=12):

`library(forecast);
thetaf(ts(c(1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.), frequency=12))`

and the error is:

`Error in decompose(x, type = "multiplicative") : 
  time series has no or less than 2 periods`

R version is 3.5.2, forecast is 8.5.

**Comment by robjhyndman** [comment]
Thanks. Fixed in https://github.com/robjhyndman/forecast/commit/4ca7d83b418d1ab2698748d9a1052b726399e45a
