### ISSUE TITLE
 object 'trend' not found

### ISSUE THREAD

**Issue by ahash52** [robjhyndman/forecast#821]
When I run my model with a polynomial trend, I get the following error:

Error in structure(x, class = unique(c("AsIs", oldClass(x)))) : 
  object 'trend' not found

Here is my R code:

mymodel <- tslm(activations ~ trend*season + I(trend^2) + I(sqrt(sold)) + I(sqrt(sold1)) + I(sqrt(sold2)), my_df_ts_all) #final model
my_fc <- forecast(mymodel, h = 12, newdata = tvs_data_test[1:12, ])
my_fc

Any ideas?

**Comment by mitchelloharawild** [comment]
Please provide a [minimally reproducible example](https://www.tidyverse.org/help/).
Without your `my_df_ts_all` dataset, I am unable to get this same error.

I also recommend trying to use `TSLM()` from the [fable package](http://fable.tidyverts.org/), which should work more reliably.

**Comment by mitchelloharawild** [comment]
Closing as `forecast::tslm()` is not designed to handle transformations of `trend` or `season`. For this you should use the fable package.
