### ISSUE TITLE
Forecasting for Regression with sARIMA errors only needing new xreg's

### ISSUE THREAD

**Issue by TheXu** [robjhyndman/forecast#823]
I would like to get a better sense of why we **only need new exogenous regressor data** for forecasting Regression with sARIMA errors to new time periods, and **not new time series data.**

Specifically what would we use for lagged error values in a Regression with sARIMA errors model, if there is no new time series data supplied? 
How would it be calculated when we don't have the time series values in the past? 
I figured previous lagged residual values are stored in the model object. However I want to forecast values in the far future (say 70 time steps), and not the immediate time steps after the model is training. Therefore, I would want to residuals up to the far future (say for time steps 65, 66, 67, 68, 69). In order to calculate those, I would need the new time series data inputted.

The forecast function currently can't take in both new time series data and exogenous regressor data.

Using the lagged predictors example from the online textbook (https://otexts.com/fpp2/lagged-predictors.html):
`forecast(object = **insurance[21:40,1]**, model = fit1, h = 6, xreg = **Advert[21:40, 1:4]**)`
`Error in forecast.Arima(fit, h = h, level = level, fan = fan) : 
  No regressors provided`

Using just xreg parameters and model object would work.

**Comment by robjhyndman** [comment]
This is not a help site. Please ask such questions on crossvalidated.com.
