### ISSUE TITLE
Inconsistency in SES, Holt, Holt-Winters and ETS models

### ISSUE THREAD

**Issue by datawookie** [robjhyndman/forecast#825]
Hi!

First off: I love this package! Fulfills most of my forecasting needs.

I just wanted to mention an inconsistency. Not a big issue, but it's nice to have a uniform interface to model objects.

For the results of `ses()`, `holt()` and `hw()` the model is accesssed via `$model`. For example:

```
airpassengers_ses$model$sigma2 %>% sqrt()
airpassengers_holt$model$sigma2 %>% sqrt()
airpassengers_hw$model$sigma2 %>% sqrt()
```

But for the result of `ets()` the result *is* the model (there is no `$model`). For example:

```
airpassengers_ets$sigma2 %>% sqrt()
```

Potentially there is a reason for why this is the case. However, it would be great if the results of these functions presented the same interface.

Thanks,
Andrew.

**Comment by robjhyndman** [comment]
`ets` returns a model, while `ses`, `holt` and `hw` return forecasts. So there is going to be a different structure. If you pass the `ets` object to `forecast`, you get the same structure as the other functions.

The new `fable` package has a more consistent interface -- one of the reasons we wrote it.
