### ISSUE TITLE
Contributing to bootstrap methods for bagging forecasts

### ISSUE THREAD

**Issue by PetoLau** [robjhyndman/forecast#826]
Hi,

I would like to contribute to your bootstrap methods and add there three new methods (to the script bootstrap.R).
I would also add new examples to the bagged model script how to use them.
These methods are based on my blog post: [Bootstrapping time series for improving forecasting accuracy](https://petolau.github.io/Bootstrapping-time-series-for-improving-forecasting-in-R/) and also published in journal: [Density-based unsupervised ensemble learning methods for time series forecasting of aggregated or clustered electricity consumption](https://link.springer.com/article/10.1007%2Fs10844-019-00550-3).
The script for these three methods can be found on [my repo](https://github.com/PetoLau/petolau.github.io/blob/master/_Rscripts/11post-BootstrappingTimeSeries.R), and methods are at the beginning. 

Would you be interested and can I make pull request?

Thanks

**Comment by robjhyndman** [comment]
This package is now in "retired" state. We are maintaining it, and doing any bug fixes, but not adding new features. Instead, we are working on the new fable package at https://fable.tidyverts.org.

**Comment by mitchelloharawild** [comment]
Bagging (and additional bagging methods) will be added to fabletools this year. The relevant issue is here: https://github.com/tidyverts/fabletools/issues/217

If you'd like to be involved in the discussion (and possibly have the methods above implemented), feel free to contribute in that issue.
