### ISSUE TITLE
Add forecast.gam() for use with the mgcv package

### ISSUE THREAD

**Issue by robjhyndman** [robjhyndman/forecast#83]
Model on forecast.lm(). Only implement when family =gaussian for now.

**Comment by terrytangyuan** [comment]
Hi Rob, is this issue still open? I might be able to help with this while getting familiar with your package and mgcv. 

Thanks,
Yuan

**Comment by robjhyndman** [comment]
Thanks. There has been no progress on that one. It requires a forecast.gam() function to work in a similar way to forecast.lm(). Note that there is an outstanding bug in forecast.lm() [see http://github.com/robjhyndman/forecast/issues/113] which we don't want to replicate. As my first comment stated, I think forecast.gam should be restricted to the gaussian family to start with.
