### ISSUE TITLE
Different lambda values for BoxCox.lambda and TBATS

### ISSUE THREAD

**Issue by isezen** [robjhyndman/forecast#834]
Hello,
Why following calculated lambda values are different by different lower and upper bounds and also in TBATS?

```R
library(forecast)
set.seed(1)
y <- rlnorm(3000)
t <- msts(y, seasonal.periods = c(24, 168))
bounds <- matrix(c(-2, -1, 0, 0, 2, 2, 1, 1.5), ncol = 2)
apply(bounds, 1, function(x) BoxCox.lambda(t, lower = x[1], upper = x[2]))
apply(bounds, 1, function(x) BoxCox.lambda(y, lower = x[1], upper = x[2]))
tb <- tbats(t)
cat("tbats_lambda: ", as.numeric(tb$lambda))
```

Results:
```
[1] -1.601259e+00 -9.999242e-01  6.610696e-05  5.847034e-05
[1] -1.535313e-01 -1.535165e-01  6.610696e-05  5.847034e-05
tbats_lambda:  0.01284863
```

**Comment by robjhyndman** [comment]
`BoxCox.lambda` takes seasonality into account, so the first two will be different. `tbats` uses a different method to estimate `lambda`, so there is no reason to think it would give the same result.

**Comment by isezen** [comment]
Thanks Mr. Hyndman,
1- Is it a good practice to transform data before TBATS  and use `use.box.cox = FALSE` or should we let TBATS to handle all of the process?
2- Do you lead me to the resources for BoxCox seasonal adjusted transformation and for TBATS one? Or should we examine the code?

**Comment by robjhyndman** [comment]
This is not a help site. Please ask such questions at crossvalidated.com
