### ISSUE TITLE
Suggestion: auto.arima option "save_models = FALSE"

### ISSUE THREAD

**Issue by sbcalaff** [robjhyndman/forecast#840]
In order to save RAM memory, I was wondering if it would be possible to add an option to `forecast::auto.arima` that makes not saving the models that have been tested. For example, something like `save_models = FALSE`. This option could be `TRUE` by default, but if many models are tested, RAM could be saved with a `FALSE` value.

**Comment by robjhyndman** [comment]
You can easily remove any elements you do not want to save. e.g., if fc is your forecast object, fc$model ← NULL will remove the model component.

---------------------------------------
*Rob J Hyndman*
robjhyndman.com ( https://robjhyndman.com )
