### ISSUE TITLE
nnetar: is retraining daily necessary for next 24 hour daily forecast

### ISSUE THREAD

**Issue by rajdeepdas** [robjhyndman/forecast#843]
Hi,
I am training nnetar for hourly traffic forecast with xreg (hour,rain etc). Each day, I am forecasting next 24 hours traffic. My question is do I have to retrain nnetar model every day until the last known hour to predict the next 24 hours?  What I am thinking is since forecast works iteratively to feed the lagged values (past y terms), if I don't retrain and keep using a model to predict daily forecast further out, say for example 10 days out, then the prediction quality will fall significantly. Can someone please answer?
Thanks
Ron

**Comment by robjhyndman** [comment]
This is not a help site. Please ask questions on crossvalidated.com or stackoverflow.com
