### ISSUE TITLE
msts documentation example error?

### ISSUE THREAD

**Issue by stenevang** [robjhyndman/forecast#844]
The taylor dataset is described as ranging between June 5, 2000 andAugust 27, 2000. To create a msts object that will be timestamped between the above, which can be tested with start(), end(), time(), tsp(), you need to do the following, where `2*24*365 == 17520` (i.e. the number of half-hours in a standard ts year):

`x <- forecast::msts(taylor, seasonal.periods=c(48, 336, 17520), start=2000+22/52)
`
if instead you do this, which is what is in the forecast documentation, you will get an msts object which is somekind of 336-observations-a-year timeseries ranging from 2000 to 2012

`x <- msts(taylor, seasonal.periods=c(48,336), start=2000+22/52)`

**Comment by robjhyndman** [comment]
Thanks. Fixed in https://github.com/robjhyndman/forecast/commit/11eb20e78d533120545fddd5080d654d9b259e4d
