### ISSUE TITLE
tsoutliers save model

### ISSUE THREAD

**Issue by VincentTennanty** [robjhyndman/forecast#846]
Hi 
How can you save a tso model for re-use on other data?
Im trying to use tsoutliers in a webservice deployment but cant figure out how to saveRDS a tso model.

Step 1) Convert Data to Timeseries
ts_data<-ts(data$var1, frequency=365, start = data$Date[1])

Step 2) Call tso function and id AO outliers
final_model<-tso(ts_data,types=c("AO"))

Step 3) Save Model
saveRDS(final_model,"./final_model.rds")

However, when I try to use the model on another timeseries dataset i get "Error in tso0(x = y, xreg = xreg, cval = cval, delta = delta, types = types, : trying to get slot "y" from an object (class "tsoutliers") that is not an S4 object"

Best regards
Vincent

**Comment by mitchelloharawild** [comment]
The `tso()` function is also from the tsoutliers package, not the forecast package. Please ask your questions there.

Also, when providing code please provide a minimally reproducible example (https://www.tidyverse.org/help/).
I don't have access to your `data`, and so cannot reproduce the error.

**Comment by VincentTennanty** [comment]
Yes I know but the tsoutliers github is read only. I have emailed the author.  Im also having the same issue trying to save a forecast model. My variable field is numeric. I want to forecast next 7 days, save the model and re-use on other datasets. Have you any experience saving a forecast model?

**Comment by robjhyndman** [comment]
This is not a general help site for time series questions. Please ask on crossvalidated.com or stackoverflow.com.

**Comment by VincentTennanty** [comment]
Apologies Rob.  best regards
