### ISSUE TITLE
infinite intervals in forecast function 

### ISSUE THREAD

**Issue by camilosierra12** [robjhyndman/forecast#847]
view(airmiles)
TRM <- Pronostico_IPP$TRM
IPC <- Pronostico_IPP$IPC
AGR <- Pronostico_IPP$`Agricultura(0.13)`
MIN <- Pronostico_IPP$`mineria(0.04)`
IND <- Pronostico_IPP$`industria(0.83)`

M <- matrix(c(TRM, AGR, MIN, IND), nrow = 219, ncol = 4)

air.m1=Arima(IPP.ts, order=c(1,0,1), seasonal = list(order=c(2,0,0), period=12), xreg = M)
summary(air.m1)
coeftest(air.m1)
checkresiduals(air.m1)
fun.fore1 <- forecast(air.m1, xreg = M, h =12)
plot(fun.fore1)
summary(fun.fore1)

i run this code, but when i run the forecast function, either the plot or the summary it gives me an interval like for 100 periods after:

Forecasts:
         Point Forecast         Lo 80         Hi 80         Lo 95         Hi 95
Apr 2020   0.0496672440  4.848364e-02  0.0508508506  0.0478570738  0.0514774141
May 2020   0.0365061240  3.477581e-02  0.0382364386  0.0338598362  0.0391524118
Jun 2020   0.0350780056  3.312779e-02  0.0370282221  0.0320954068  0.0380606043
Jul 2020   0.0247356251  2.268269e-02  0.0267885589  0.0215959336  0.0278753165
Aug 2020   0.0221816551  2.007846e-02  0.0242848536  0.0189650905  0.0253982196
Sep 2020   0.0293500850  2.722180e-02  0.0314783658  0.0260951604  0.0326050095
Oct 2020   0.0403529951  3.821208e-02  0.0424939064  0.0370787540  0.0436272363
Nov 2020   0.0496081413  4.746084e-02  0.0517554410  0.0463241298  0.0528921527
Dec 2020   0.0687864561  6.663592e-02  0.0709369942  0.0654974920  0.0720754203
Jan 2021   0.0912422564  8.909008e-02  0.0933944379  0.0879507790  0.0945337339
Feb 2021   0.0907778646  8.862485e-02  0.0929308805  0.0874851110  0.0940706182
Mar 2021   0.0965105087  9.435707e-02  0.0986639484  0.0932171069  0.0998039105
Apr 2021   0.1080229981  1.058045e-01  0.1102415198  0.1046300619  0.1114159343
May 2021   0.1182008269  1.159078e-01  0.1204938085  0.1146940140  0.1217076397
Jun 2021   0.1190996044  1.167697e-01  0.1214295040  0.1155363304  0.1226628783
Jul 2021   0.1229234413  1.205750e-01  0.1252718748  0.1193318223  0.1265150604
Aug 2021   0.1164156240  1.140578e-01  0.1187734178  0.1128096896  0.1200215584
Sep 2021   0.1112388467  1.088763e-01  0.1136013817  0.1076256611  0.1148520322
Oct 2021   0.1020331022  9.966816e-02  0.1043980424  0.0984162382  0.1056499661
Nov 2021   0.0901737250  8.780756e-02  0.0925398862  0.0865549937  0.0937924563
Dec 2021   0.0677793380  6.541256e-02  0.0701461194  0.0641596584  0.0713990177
Jan 2022   0.0545929826  5.222589e-02  0.0569600789  0.0509728212  0.0582131440
Feb 2022   0.0623466279  5.997937e-02  0.0647138842  0.0587262218  0.0659670340
Mar 2022   0.0575335352  5.516620e-02  0.0599008728  0.0539130048  0.0611540657
Apr 2022   0.0512802337  4.891234e-02  0.0536481237  0.0476588584  0.0549016090
May 2022   0.0472675470  4.489914e-02  0.0496359564  0.0436453774  0.0508897165
Jun 2022   0.0438779616  4.150929e-02  0.0462466348  0.0402553886  0.0475005346
Jul 2022   0.0419323387  3.956353e-02  0.0443011458  0.0383095607  0.0455551166
Aug 2022   0.0547466406  5.237777e-02  0.0571155159  0.0511237585  0.0583695227
Sep 2022   0.0590095313  5.664062e-02  0.0613784411  0.0553865963  0.0626324663
Oct 2022   0.0529865659  5.061764e-02  0.0553554934  0.0493636041  0.0566095278
Nov 2022   0.0524280575  5.005912e-02  0.0547969938  0.0488050820  0.0560510330
Dec 2022   0.0572737781  5.490484e-02  0.0596427190  0.0536507957  0.0608967606
Jan 2023   0.0604016942  5.803275e-02  0.0627706374  0.0567787082  0.0640246802
Feb 2023   0.0555366745  5.316773e-02  0.0579056189  0.0519136867  0.0591596623
Mar 2023   0.0458721565  4.350321e-02  0.0482411014  0.0422491678  0.0494951451
Apr 2023   0.0436906067  4.131612e-02  0.0460650971  0.0400591371  0.0473220764
May 2023   0.0425323156  4.015150e-02  0.0449131270  0.0388911787  0.0461734525
Jun 2023   0.0492419950  4.685798e-02  0.0516260114  0.0455959565  0.0528880335
Jul 2023   0.0418605017  3.947486e-02  0.0442461448  0.0382119755  0.0455090280
Aug 2023   0.0286223038  2.623583e-02  0.0310087728  0.0249725143  0.0322720932
Sep 2023   0.0274239203  2.503703e-02  0.0298108090  0.0237734892  0.0310743515
Oct 2023   0.0302481802  2.786108e-02  0.0326352820  0.0265974232  0.0338989373
Nov 2023   0.0291987699  2.681156e-02  0.0315859799  0.0255478473  0.0328496925
Dec 2023   0.0223254619  1.993820e-02  0.0247127269  0.0186744552  0.0259764687
Jan 2024   0.0203205956  1.793330e-02  0.0227078886  0.0166695461  0.0239716451
Feb 2024   0.0170129203  1.462561e-02  0.0194002274  0.0133618491  0.0206639915
Mar 2024   0.0216143357  1.922702e-02  0.0240016500  0.0179632535  0.0252654179
Apr 2024   0.0245134613  2.212529e-02  0.0269016348  0.0208610652  0.0281658574
May 2024   0.0172561079  1.486692e-02  0.0196453006  0.0136021529  0.0209100629
Jun 2024   0.0146972303  1.230752e-02  0.0170869407  0.0110424836  0.0183519770
Jul 2024   0.0335288245  3.113885e-02  0.0359187979  0.0298736756  0.0371839734
Aug 2024   0.0420298661  3.963976e-02  0.0444199731  0.0383745130  0.0456852193
Sep 2024   0.0488575119  4.646734e-02  0.0512476867  0.0452020549  0.0525129689
Oct 2024   0.0539031459  5.151294e-02  0.0562933552  0.0502476362  0.0575586556
Nov 2024   0.0524650530  5.007483e-02  0.0548552799  0.0488095165  0.0561205895
Dec 2024   0.0579262697  5.553603e-02  0.0603165054  0.0542707196  0.0615818198
Jan 2025   0.0517474671  4.935723e-02  0.0541377073  0.0480919100  0.0554030241
Feb 2025   0.0511163997  4.872616e-02  0.0535066422  0.0474608392  0.0547719602
Mar 2025   0.0542447954  5.185455e-02  0.0566350392  0.0505892331  0.0579003578
Apr 2025   0.0484149465  4.602468e-02  0.0508052174  0.0447593427  0.0520705503
May 2025   0.0486687706  4.627847e-02  0.0510590694  0.0450131241  0.0523244171
Jun 2025   0.0424198781  4.002957e-02  0.0448101910  0.0387642100  0.0460755462
Jul 2025   0.0229881886  2.059787e-02  0.0253785087  0.0193325094  0.0266438677
Aug 2025   0.0057116178  3.321294e-03  0.0081019416  0.0020559331  0.0093673026
Sep 2025  -0.0110694888 -1.345981e-02 -0.0086791632 -0.0147251764 -0.0074138012
Oct 2025  -0.0193271255 -2.171745e-02 -0.0169367989 -0.0229828145 -0.0156714364
Nov 2025  -0.0165588443 -1.894917e-02 -0.0141685173 -0.0202145341 -0.0129031546
Dec 2025  -0.0091793237 -1.156965e-02 -0.0067889964 -0.0128350139 -0.0055236336
Jan 2026  -0.0056574658 -8.047793e-03 -0.0032671383 -0.0093131561 -0.0020017754
Feb 2026   0.0044719831  2.081656e-03  0.0068623106  0.0008162927  0.0081276736
Mar 2026   0.0126020837  1.021176e-02  0.0149924112  0.0089463932  0.0162577742
Apr 2026   0.0223491379  1.995871e-02  0.0247395664  0.0186932930  0.0260049828
May 2026   0.0384692220  3.607868e-02  0.0408597663  0.0348132000  0.0421252440
Jun 2026   0.0328837566  3.049315e-02  0.0352743598  0.0292276446  0.0365398686
Jul 2026   0.0368515009  3.446087e-02  0.0392421340  0.0331953432  0.0405076586
Aug 2026   0.0517605675  4.936992e-02  0.0541512157  0.0481043866  0.0554167484
Sep 2026   0.0757887308  7.339807e-02  0.0781793867  0.0721325381  0.0794449235
Oct 2026   0.0924852747  9.009461e-02  0.0948759345  0.0888290759  0.0961414734
Nov 2026   0.0880974009  8.570674e-02  0.0904880627  0.0844411991  0.0917536027
Dec 2026   0.0930731525  9.068249e-02  0.0954638153  0.0894169492  0.0967293558
Jan 2027   0.1124506933  1.100600e-01  0.1148413567  0.1087944892  0.1161068974
Feb 2027   0.1047077877  1.023171e-01  0.1070984513  0.1010515832  0.1083639922
Mar 2027   0.0875003721  8.510971e-02  0.0898910359  0.0838441674  0.0911565768
Apr 2027   0.0643506374  6.195996e-02  0.0667413130  0.0606944146  0.0680068603
May 2027   0.0633971954  6.100651e-02  0.0657878852  0.0597409509  0.0670534399
Jun 2027   0.0704838874  6.809319e-02  0.0728745843  0.0668276319  0.0741401428
Jul 2027   0.0682292857  6.583859e-02  0.0706199863  0.0645730246  0.0718855467
Aug 2027   0.0565454167  5.415471e-02  0.0589361191  0.0528891528  0.0602016806
Sep 2027   0.0298132558  2.742255e-02  0.0322039592  0.0261569904  0.0334695211
Oct 2027   0.0179212557  1.553055e-02  0.0203119596  0.0142649896  0.0215775218
Nov 2027   0.0155816380  1.319093e-02  0.0179723421  0.0119253715  0.0192379044
Dec 2027  -0.0085035880 -1.089429e-02 -0.0061128838 -0.0121598546 -0.0048473214
Jan 2028  -0.0351641775 -3.755488e-02 -0.0327734732 -0.0388204443 -0.0315079108
Feb 2028  -0.0354655134 -3.785622e-02 -0.0330748090 -0.0391217801 -0.0318092466
Mar 2028  -0.0208983064 -2.328901e-02 -0.0185076020 -0.0245545732 -0.0172420396
Apr 2028   0.0032558793  8.651740e-04  0.0056465846 -0.0004003889  0.0069121475
May 2028  -0.0055636141 -7.954320e-03 -0.0031729079 -0.0092198838 -0.0019073445
Jun 2028  -0.0033620667 -5.752773e-03 -0.0009713600 -0.0070183372  0.0002942037
Jul 2028   0.0014062010 -9.845060e-04  0.0037969080 -0.0022500698  0.0050624719
Aug 2028   0.0120417635  9.651056e-03  0.0144324707  0.0083854925  0.0156980346
Sep 2028   0.0204634294  1.807272e-02  0.0228541366  0.0168071583  0.0241197005
Oct 2028   0.0169865827  1.459588e-02  0.0193772899  0.0133303115  0.0206428539
Nov 2028   0.0184145071  1.602380e-02  0.0208052144  0.0147582359  0.0220707783
Dec 2028   0.0213217157  1.893101e-02  0.0237124230  0.0176654445  0.0249779869
Jan 2029   0.0253680313  2.297732e-02  0.0277587386  0.0217117601  0.0290243026
Feb 2029   0.0353574584  3.296675e-02  0.0377481657  0.0317011872  0.0390137297
Mar 2029   0.0424406453  4.004994e-02  0.0448313525  0.0387843740  0.0460969165
Apr 2029   0.0416330060  3.924230e-02  0.0440237151  0.0379767320  0.0452892800
May 2029   0.0437152563  4.132455e-02  0.0461059674  0.0400589791  0.0473715335
Jun 2029   0.0475960125  4.520530e-02  0.0499867247  0.0439397337  0.0512522913
Jul 2029   0.0444756670  4.208495e-02  0.0468663798  0.0408193874  0.0481319466
Aug 2029   0.0458028995  4.341219e-02  0.0481936125  0.0421466195  0.0494591796
Sep 2029   0.0451096435  4.271893e-02  0.0475003567  0.0414533633  0.0487659238
Oct 2029   0.0459057212  4.351501e-02  0.0482964344  0.0422494408  0.0495620015
Nov 2029   0.0519242305  4.953352e-02  0.0543149438  0.0482679501  0.0555805109
Dec 2029   0.0641334811  6.174277e-02  0.0665241943  0.0604772006  0.0677897615
Jan 2030   0.0791072212  7.671651e-02  0.0814979345  0.0754509408  0.0827635017
Feb 2030   0.0683099554  6.591924e-02  0.0707006687  0.0646536750  0.0719662359
Mar 2030   0.0532441285  5.085342e-02  0.0556348418  0.0495878480  0.0569004090
Apr 2030   0.0367560284  3.436531e-02  0.0391467418  0.0330997477  0.0404123091
May 2030   0.0265710207  2.418031e-02  0.0289617343  0.0229147397  0.0302273017
Jun 2030   0.0152470886  1.285637e-02  0.0176378023  0.0115908074  0.0189033697
Jul 2030   0.0152604518  1.286974e-02  0.0176511655  0.0116041706  0.0189167330
Aug 2030   0.0083909094  6.000196e-03  0.0107816232  0.0047346282  0.0120471907
Sep 2030  -0.0050115986 -7.402312e-03 -0.0026208848 -0.0086678798 -0.0013553173
Oct 2030  -0.0015582507 -3.948964e-03  0.0008324631 -0.0052145319  0.0020980306
Nov 2030   0.0015451382 -8.455756e-04  0.0039358520 -0.0021111431  0.0052014195
Dec 2030   0.0014850194 -9.056945e-04  0.0038757332 -0.0021712619  0.0051413006
Jan 2031  -0.0100526956 -1.244341e-02 -0.0076619818 -0.0137089769 -0.0063964143
Feb 2031  -0.0189595200 -2.135023e-02 -0.0165688062 -0.0226158013 -0.0153032387
Mar 2031  -0.0269723548 -2.936307e-02 -0.0245816409 -0.0306286360 -0.0233160735
Apr 2031  -0.0233322027 -2.572292e-02 -0.0209414888 -0.0269884840 -0.0196759214
May 2031  -0.0226702999 -2.506101e-02 -0.0202795860 -0.0263265812 -0.0190140185
Jun 2031  -0.0170520741 -1.944279e-02 -0.0146613602 -0.0207083555 -0.0133957927
Jul 2031  -0.0211563507 -2.354706e-02 -0.0187656368 -0.0248126321 -0.0175000694
Aug 2031  -0.0184476379 -2.083835e-02 -0.0160569240 -0.0221039193 -0.0147913565
Sep 2031  -0.0019718557 -4.362570e-03  0.0004188583 -0.0056281371  0.0016844258
Oct 2031  -0.0002897784 -2.680492e-03  0.0021009355 -0.0039460598  0.0033665030
Nov 2031  -0.0045174462 -6.908160e-03 -0.0021267323 -0.0081737276 -0.0008611648
Dec 2031  -0.0117806406 -1.417135e-02 -0.0093899267 -0.0154369220 -0.0081243592
Jan 2032  -0.0171961529 -1.958687e-02 -0.0148054390 -0.0208524343 -0.0135398715
Feb 2032  -0.0123445212 -1.473524e-02 -0.0099538073 -0.0160008026 -0.0086882398
Mar 2032  -0.0043983916 -6.789105e-03 -0.0020076777 -0.0080546730 -0.0007421102
Apr 2032   0.0024121780  2.146409e-05  0.0048028920 -0.0012441034  0.0060684595
May 2032   0.0122279833  9.837269e-03  0.0146186973  0.0085717018  0.0158842648
Jun 2032   0.0248163047  2.242559e-02  0.0272070187  0.0211600231  0.0284725862
Jul 2032   0.0320360728  2.964536e-02  0.0344267868  0.0283797913  0.0356923544
Aug 2032   0.0287593764  2.636866e-02  0.0311500904  0.0251030948  0.0324156579
Sep 2032   0.0234464365  2.105572e-02  0.0258371505  0.0197901549  0.0271027180
Oct 2032   0.0212923252  1.890161e-02  0.0236830393  0.0176360437  0.0249486068
Nov 2032   0.0281298529  2.573914e-02  0.0305205669  0.0244735714  0.0317861345
Dec 2032   0.0354558102  3.306510e-02  0.0378465242  0.0317995286  0.0391120918
Jan 2033   0.0481473954  4.575668e-02  0.0505381094  0.0444911138  0.0518036770
Feb 2033   0.0508563032  4.846559e-02  0.0532470172  0.0472000216  0.0545125848
Mar 2033   0.0624164087  6.002569e-02  0.0648071227  0.0587601271  0.0660726903
Apr 2033   0.0624703954  6.007968e-02  0.0648611094  0.0588141138  0.0661266770
May 2033   0.0499706298  4.757992e-02  0.0523613439  0.0463143483  0.0536269114
Jun 2033   0.0513874699  4.899676e-02  0.0537781839  0.0477311883  0.0550437515
Jul 2033   0.0425667546  4.017604e-02  0.0449574686  0.0389104730  0.0462230362
Aug 2033   0.0361995045  3.380879e-02  0.0385902186  0.0325432230  0.0398557861
Sep 2033   0.0479459044  4.555519e-02  0.0503366184  0.0442896228  0.0516021860
Oct 2033   0.0615174060  5.912669e-02  0.0639081200  0.0578611244  0.0651736875
Nov 2033   0.0775957652  7.520505e-02  0.0799864792  0.0739394836  0.0812520467
Dec 2033   0.0847637166  8.237300e-02  0.0871544307  0.0811074351  0.0884199982
Jan 2034   0.0810009632  7.861025e-02  0.0833916772  0.0773446816  0.0846572448
Feb 2034   0.0878980500  8.550734e-02  0.0902887640  0.0842417684  0.0915543316
Mar 2034   0.0948873503  9.249664e-02  0.0972780643  0.0912310687  0.0985436319
Apr 2034   0.0996821413  9.729143e-02  0.1020728553  0.0960258597  0.1033384228
May 2034   0.1091507055  1.067600e-01  0.1115414195  0.1054944239  0.1128069871
Jun 2034   0.0856495034  8.325879e-02  0.0880402174  0.0819932218  0.0893057849
Jul 2034   0.0872616291  8.487092e-02  0.0896523432  0.0836053476  0.0909179107
Aug 2034   0.1026347603  1.002440e-01  0.1050254743  0.0989784787  0.1062910419
Sep 2034   0.1003712656  9.798055e-02  0.1027619796  0.0967149840  0.1040275472
Oct 2034   0.0887412105  8.635050e-02  0.0911319245  0.0850849289  0.0923974921
Nov 2034   0.0511810380  4.879032e-02  0.0535717520  0.0475247564  0.0548373196
Dec 2034   0.0351875740  3.279686e-02  0.0375782880  0.0315312924  0.0388438556
Jan 2035   0.0353925929  3.300188e-02  0.0377833069  0.0317363113  0.0390488744
Feb 2035   0.0393161416  3.692543e-02  0.0417068556  0.0356598600  0.0429724232
Mar 2035   0.0162499341  1.385922e-02  0.0186406482  0.0125936526  0.0199062157
Apr 2035   0.0092090623  6.818348e-03  0.0115997763  0.0055527807  0.0128653439
May 2035  -0.0012034548 -3.594169e-03  0.0011872592 -0.0048597364  0.0024528268
Jun 2035   0.0048448028  2.454089e-03  0.0072355169  0.0011885213  0.0085010844
Jul 2035   0.0028985513  5.078373e-04  0.0052892653 -0.0007577303  0.0065548329
Aug 2035  -0.0032816087 -5.672323e-03 -0.0008908947 -0.0069378903  0.0003746729
Sep 2035  -0.0104200075 -1.281072e-02 -0.0080292935 -0.0140762891 -0.0067637259
Oct 2035  -0.0048465411 -7.237255e-03 -0.0024558271 -0.0085028227 -0.0011902595
Nov 2035   0.0092806777  6.889964e-03  0.0116713917  0.0056243961  0.0129369593
Dec 2035   0.0116647017  9.273988e-03  0.0140554157  0.0080084201  0.0153209833
Jan 2036   0.0136177199  1.122701e-02  0.0160084340  0.0099614384  0.0172740015
Feb 2036   0.0134365286  1.104581e-02  0.0158272427  0.0097802471  0.0170928102
Mar 2036   0.0191294391  1.673873e-02  0.0215201531  0.0154731575  0.0227857207
Apr 2036   0.0147129635  1.232225e-02  0.0171036776  0.0110566819  0.0183692451
May 2036   0.0191850652  1.679435e-02  0.0215757792  0.0155287836  0.0228413468
Jun 2036   0.0173872085  1.499649e-02  0.0197779225  0.0137309269  0.0210434901
Jul 2036   0.0196828263  1.729211e-02  0.0220735403  0.0160265447  0.0233391079
Aug 2036   0.0289582060  2.656749e-02  0.0313489201  0.0253019245  0.0326144876
Sep 2036   0.0325298642  3.013915e-02  0.0349205783  0.0288735826  0.0361861458
Oct 2036   0.0250044395  2.261373e-02  0.0273951536  0.0213481580  0.0286607211
Nov 2036   0.0240804890  2.168977e-02  0.0264712030  0.0204242074  0.0277367706
 [ reached 'max' / getOption("max.print") -- omitted 19 rows ]

**Comment by robjhyndman** [comment]
You're providing the `M` matrix to the forecast function via the `xreg` argument, so it uses the number of rows of `M` rather than the value of `h`. This is explained in the help file. The `xreg` argument passed to `forecast()` should contain the **future** values of the regressors, not the past values.
