### ISSUE TITLE
Add function to do multi-step in-sample forecasts

### ISSUE THREAD

**Issue by robjhyndman** [robjhyndman/forecast#85]
See discussion at https://stackoverflow.com/questions/25167292/function-for-extracting-counter-factual-arima-forecasts-in-r

**Comment by paulhendricks** [comment]
@robjhyndman Is this issue still open? I'm encountering a similar need across multiple model typess (not just arima) and may implement this functionality.

**Comment by robjhyndman** [comment]
Yes, but no progress has been made.

**Comment by robjhyndman** [comment]
This has been resolved with the h argument in fitted.Arima, fitted.ets, etc.
