### ISSUE TITLE
Question: How to extract moving seasonality component?

### ISSUE THREAD

**Issue by nba2020gr** [robjhyndman/forecast#850]
I have a time-serie with daily observations and length of ~4 years which I want to deseasonalize and extract its values without the seasonal related variation. The time-serie has weekly and annually seasonality. However, on top of these 2 regular seasonality, it has also seasonality related to moving holidays (Black Friday, Easter etc.). So far I managed to take out weekly and annually seasonality with the below code:
```
ts <- xts(x=DataFrame$MetricColumn,order.by=as.Date(DataFrame$DateColumn,"%Y/%m/%d"))
ts <- msts(as.numeric(ts [,1]),seasonal.periods=c(7,365))
ts_deseasonal <- mstl(ts,t.window=1)
```
How may I extract seasonality of a moving holiday? For example, Black Friday was in 29 Nov in 2019 but 23 Nov in 2018.

**Comment by robjhyndman** [comment]
You will need to fit a model that accounts for these holidays. See https://otexts.com/fpp2/weekly.html.
In general, please only use this site for bug reports. General questions should go on community.rstudio.com.
