### ISSUE TITLE
Question about variance of innovations in simulate.lagwalk

### ISSUE THREAD

**Issue by e3bo** [robjhyndman/forecast#851]
I was wondering why step sizes are calculated as 
        
    se <- sqrt(object$sigma2*nsim + (nsim*object$par$drift.se)^2)
     e <- rnorm(nsim, 0, se)

on line [542](https://github.com/robjhyndman/forecast/blob/9d0dbf887b603be9f0e51db724407f55ccab60d2/R/simulate.R#L542)-543 of simulate.R instead of

     se <- sqrt(object$sigma2)
     e <- rnorm(nsim, 0, se)

**Comment by robjhyndman** [comment]
You're right.  The standard errors are wrong here. Now fixed in https://github.com/robjhyndman/forecast/commit/e530f6a12497d9e931b5160bec7c6083897d6413
