### ISSUE TITLE
Stepwise for selection of covariates

### ISSUE THREAD

**Issue by betmar78** [robjhyndman/forecast#856]
The auto.arima function applies stepwise presenting the best regression model with ARIMA errors when the xreg parameter is used. However, it does not select the most significant covariates; presenting all covariates, whether significant or no.

Is it also possible to apply stepwise to select the significant covariates (xreg) in the result presented by the auto.arima function for the best model?

How to define the final model with only the significant regressive variables (xreg)?

**Comment by robjhyndman** [comment]
It is possible, but not implemented. You can manually select the model with the smallest AICc value.

**Comment by betmar78** [comment]
But this function does for ARIMA errors. It does not do for covariates. Thanks for the reply.
