### ISSUE TITLE
fitted reported incorrectly in forecast.StructTS

### ISSUE THREAD

**Issue by eeholmes** [robjhyndman/forecast#858]
The forecast.StructTS code has the following for the fitted values
```
fits <- ts(c(x - residuals(object)))
```
However the residuals returned by `StructTS` are the standardized residuals (see ?StructTS). You would need the unstandardized residuals to get the one-step-ahead values with that code. But probably easier just to get innovations from a Kalman filter as filter that outputs that. The base R filter doesn't (it gives predictions conditioned on the data up to t).

**Comment by robjhyndman** [comment]
Thanks. Perhaps `rowSums(fitted(object))` would be the simplest way of getting the fitted values?

**Comment by eeholmes** [comment]
`fitted(object)` is returning the expected value of y conditioned on the data 1 to t. The info in `?forecast.StructTS` indicates that `fitted` returned by `forecast.StructTS` is the one-step ahead prediction so expected value of y conditioned on 1 to t-1.

If you want instead the same thing that `fitted(object)` is returning it'd be
```
if(type="level") fitted.vals <- fitted(object)$level
if(type="trend") fitted.vals <- fitted(object)$level
if(type="BSM") fitted.vals <- fitted(object)$level + fitted(object)$seas
```
Given the way the `StructTS` constructs its level, trend and BSM models, the trend estimate affect level but not y directly.

I came across this while working on the update to MARSS and coding up the StructTS models to use in my unit tests.


`

**Comment by robjhyndman** [comment]
Now fixed in https://github.com/robjhyndman/forecast/commit/53486f86fb27501042635112d69c5c82573f58dc. Thanks for the bug report.
