### ISSUE TITLE
 is your package can be used for multivariate time series ?

### ISSUE THREAD

**Issue by Sandy4321** [robjhyndman/forecast#860]
can you pls clarify 
I see from 
https://cran.r-project.org/web/packages/forecast/index.html
that your package is for univariate time series 
Methods and tools for displaying and analysing univariate time series forecasts including exponential smoothing via state space models and automatic ARIMA modelling

but in 
https://arxiv.org/pdf/1704.04110.pdf
DeepAR: Probabilistic Forecasting with
Autoregressive Recurrent Networks

it used as baseline
however 
from 
https://docs.aws.amazon.com/sagemaker/latest/dg/deepar.html#deepar_best_practices

we see that sagemaker used for multivariate time series ?

then is your package can be used for multivariate time series ?

**Comment by robjhyndman** [comment]
There are no truly multivariate modelling functions in the package.

**Comment by Sandy4321** [comment]
thanks for soon answer
hopefully you do know package for multivariate modelling
