### ISSUE TITLE
Auto.arima with xreg 

### ISSUE THREAD

**Issue by azev77** [robjhyndman/forecast#865]
Suppose I want to estimate an AR1 w/ an x variable: 
`y_t = \mu + \rho * y_t-1 + \beta * x_t + \epsilon_t`
how is this possible w/ auto.arima()? 

It appears from the [example in fpp2](https://otexts.com/fpp2/regarima.html) that 
`auto.arima(y, xreg=x)`
only fits regression models w/ ARIMA **errors**

**Comment by robjhyndman** [comment]
You can reparameterize that model to be a linear regression with AR(1) errors. See https://robjhyndman.com/hyndsight/arimax/
Note: this is not a Q&A site. It is intended to report bugs or request features for the forecast package. Please ask such questions on crossvalidated.com or stackoverflow.com
