### ISSUE TITLE
Error in class(y) %in% c("data.frame", "list", "matrix", "mts") :    object 'usnetelec' not found

### ISSUE THREAD

**Issue by korterling** [robjhyndman/forecast#869]
R>>> etsfit <- ets(usnetelec)
Error in class(y) %in% c("data.frame", "list", "matrix", "mts") : 
  object 'usnetelec' not found

where to get the data usnetelec,thanks!

**Comment by robjhyndman** [comment]
They are part of the expsmooth package, and will be loaded when you use library(fpp2).
