### ISSUE TITLE
tbats strange behaviour

### ISSUE THREAD

**Issue by denadai2** [robjhyndman/forecast#87]
I write this issue because tbats is behaving strangely and I think it's a bug.

File: https://dl.dropboxusercontent.com/u/1118905/bug.RData
Source:

    library(forecast)
    load("bug.RData")
    y <- msts(dat.ts, seasonal.periods=c(24, (7*24)))
    fit <- tbats(y)
    plot(fit)

It doesn't show the slope and season. Maybe it doesn't find the seasonality, but so why doesn't it show a warning message?
![screen shot 2014-09-18 at 17 46 13](https://cloud.githubusercontent.com/assets/190799/4322742/fc62ef1e-3f4a-11e4-843f-f447ff026128.png)
It behaves normally with 

    y <- msts(dat.ts, seasonal.periods=c(24))

Thanks

**Comment by robjhyndman** [comment]
These problems have now been fixed by modifying the admissibility check to be stricter. i.e., the roots of the ARMA component and the eigenvalues of the matrix must now be further away from 1.
