### ISSUE TITLE
auto.arima with lambda=-1 gives wrong forecast on series close to 0

### ISSUE THREAD

**Issue by MartinBonde** [robjhyndman/forecast#873]
This bug has troubled me in the past and I managed to find an easily reproducible example:
```
> c(0.006, 0.005, 0.01, 0.007) %>% auto.arima(lambda="auto") %>% forecast(h=3)
  Point Forecast       Lo 80 Hi 80       Lo 95 Hi 95
5              1 0.004986502    NA 0.003266033    NA
6              1 0.004986502    NA 0.003266033    NA
7              1 0.004986502    NA 0.003266033    NA
```
In this example a Box Cox transformation with lambda= -0.9999242 is applied.
A lambda close to or lower than -1 seems to cause some numerical issues with the small numbers and a point forecast of 1 is returned. An error message would be much preferable!

Slightly changing the input, a positive lambda is used instead, and a sensible forecast (given the miserable input) is returned:
```
> c(0.005, 0.005, 0.01, 0.007) %>% auto.arima(lambda="auto") %>% forecast(h=3)
  Point Forecast       Lo 80       Hi 80       Lo 95     Hi 95
5    0.006533439 0.004141789 0.009848095 0.003182706 0.0120493
6    0.006533439 0.004141789 0.009848095 0.003182706 0.0120493
7    0.006533439 0.004141789 0.009848095 0.003182706 0.0120493
```

Thank you for the wonderful package!

**Comment by robjhyndman** [comment]
It would probably be safer to prevent automated selection of lambda choosing such a low value. The results are very unstable when lambda is close to -1. I've now implemented this in https://github.com/robjhyndman/forecast/commit/6f99e125901cc34fc88f5c98b9f7d9d41ebf5f1c so that -0.9 is the new lower bound (rather than -1).
