### ISSUE TITLE
ggCcf not showing lag=0

### ISSUE THREAD

**Issue by espher1987** [robjhyndman/forecast#894]
Hi to everyone, this is my MWE:

The exact problem is with `ggCff` not showing lag = 0 coefficient . i don't understand why not showing this value when `ccf` and `forecast::Ccf` show this values.

``` r
library(forecast)
#> Registered S3 method overwritten by 'quantmod':
#>   method            from
#>   as.zoo.data.frame zoo
library(vars)
#> Loading required package: MASS
#> Loading required package: strucchange
#> Loading required package: zoo
#> 
#> Attaching package: 'zoo'
#> The following objects are masked from 'package:base':
#> 
#>     as.Date, as.Date.numeric
#> Loading required package: sandwich
#> Loading required package: urca
#> Loading required package: lmtest
a <- Canada[,3]
b <- Canada[,4]

ccf(x = a,y = b)
```

![](https://i.imgur.com/fLandU5.png)

``` r
Ccf(x = a,y = b)
```

![](https://i.imgur.com/YsmPxAj.png)

``` r
ggCcf(x = a,y = b)
```

![](https://i.imgur.com/Xld253q.png)

<sup>Created on 2021-11-22 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

Thanks for this amazing package!!!

**Comment by robjhyndman** [comment]
Thanks. Fixed in https://github.com/robjhyndman/forecast/commit/105223ed4b08c6a7c283862d1fc8b9b73bda859b
