### ISSUE TITLE
could not find function "Acf"

### ISSUE THREAD

**Issue by AlissonRP** [robjhyndman/forecast#896]
I'm trying to run `forecast::ggAcf(rnorm(100))`
```r 
forecast::ggAcf(rnorm(100))
Error in Acf(x = rnorm(100), plot = FALSE) : 
  could not find function "Acf"
```
 but `ggAcf` has dependency on `Acf` and `autoplot`, but `AcF` is in the forecast namespace, and since I didn't give library/require, ggAcf can't find this function (I'm not giving library/require because it doesn't I need all of the forecast functions), since your package has a dependency on ggplot2 wouldn't it be interesting to write ggAcf that way?
``` r
ggAcf <- function(x, lag.max = NULL,
                  type = c("correlation", "covariance", "partial"),
                  plot = TRUE, na.action = na.contiguous, demean=TRUE, ...) {
  cl <- match.call()
  if (plot) {
    cl$plot <- FALSE
  }
  cl[[1]] <- quote(forecast::Acf)
  object <- eval.parent(cl)
  object$tsp <- tsp(x)
  object$periods <- attributes(x)$msts
  if (plot) {
    return(ggplot2::autoplot(object, ...))
  }
  else {
    return(object)
  }
}

ggAcf(rnorm(100))


```
![Rplot](https://user-images.githubusercontent.com/62574371/144677787-8d846439-1a57-450b-b7be-49cf9c5c3999.png)

**Comment by mitchelloharawild** [comment]
Fixed in 432d6a1125a9c481231a042de7c2d76bc95aa84a

``` r
forecast::ggAcf(rnorm(100))
#> Registered S3 method overwritten by 'quantmod':
#>   method            from
#>   as.zoo.data.frame zoo
```

![](https://i.imgur.com/cf8EmQv.png)

``` r
forecast::ggPacf(rnorm(100))
```

![](https://i.imgur.com/K61KqJc.png)

``` r
forecast::ggCcf(rnorm(100),rnorm(100))
```

![](https://i.imgur.com/5ipJxOQ.png)

<sup>Created on 2021-12-06 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>
