### ISSUE TITLE
NNAR in forecast package 

### ISSUE THREAD

**Issue by Farahyas73** [robjhyndman/forecast#915]
Hi,
I was trying to use neural network autoregression (NNAR) using the function 'nnetar'  for global temperature. I tried to get prediction intervals. they are good up to h=20, but for a longer forecast horizon, (e.g. h=60), the upper limits of prediction intervals are not satisfactory and they are smaller than the mean forecasts. The figures are plotted below. Thanks 

![image](https://user-images.githubusercontent.com/44271363/179887490-edeb2ce7-286c-4888-89f5-d4f9ac09359b.png)

![image](https://user-images.githubusercontent.com/44271363/179887779-39f6adbf-4257-4bc4-9246-8cb1f8a9ca8f.png)

**Comment by robjhyndman** [comment]
This is not reproducible. Please provide a reproducible example.
