### ISSUE TITLE
auto.arima and fixed

### ISSUE THREAD

**Issue by AlbertoAlmuinha** [robjhyndman/forecast#918]
Hi,

Is there a way for `auto.arima` to only check models in which the only coefficients with value are those of the order being tested and the rest are 0, similar to what can be achieved with the `fixed` argument in the `Arima` function?

For example, for order p = 4, d = 1 and q = 4, I would like auto.arima to check model:

```
forecast::auto.arima(y, order = c(4, 0, 4), fixed = (0, 0, 0, NA, 0, 0, 0, NA))
```

Is this possible?

Thanks,

**Comment by robjhyndman** [comment]
No, that's not possible. Sorry

**Comment by AlbertoAlmuinha** [comment]
Ok, thanks for the answer. I’ll close the issue.
