### ISSUE TITLE
Problem with ggAcf

### ISSUE THREAD

**Issue by agustinggza** [robjhyndman/forecast#919]
Hi.
Thanks for your great work.
I've a problem with this library: I obtain same plot with ggAcf and ggPacf. I think are Partial ACF plot both. 
This is my code:
-------------------------
library("quantmod")
library("forecast")  # version 8.17.0

getSymbols("^GSPC", from="1970-01-02")
head(GSPC)
diff(log(Cl(GSPC)))

ggAcf( diff(log(Cl(GSPC))), plot=T)
ggPacf( diff(log(Cl(GSPC))), plot=T)
--------------------

Thank you . Greetings from Spain.

**Comment by mitchelloharawild** [comment]
I can't reproduce this. Could you show what you get using the `{reprex}` package?

``` r
library("forecast") # version 8.17.0
#> Registered S3 method overwritten by 'quantmod':
#>   method            from
#>   as.zoo.data.frame zoo
GSPC <- ts(abs(rnorm(100)))
diff(log(GSPC))
#> Time Series:
#> Start = 2 
#> End = 100 
#> Frequency = 1 
#>  [1] -0.72018170 -2.26810531  1.97675348  0.28169965 -0.34653287  0.91231954
#>  [7] -1.02797521 -0.02751398  0.09385724 -0.77348169  0.49857535  0.06165555
#> [13]  0.67592790 -0.68507668 -0.18178902  0.66457307 -2.98774745  1.53558220
#> [19]  2.00246027 -1.76584361 -1.10077552  2.43934472 -0.92521203 -1.14087250
#> [25]  2.45907708 -4.93836662  4.76321785 -1.10667518  0.70909886 -2.49508587
#> [31]  2.99051750 -0.60291242 -1.67804795  2.09434304 -0.28104077 -0.74158150
#> [37]  0.21835229 -0.51052443 -0.23093410  1.26575935 -0.03067969 -3.74068480
#> [43]  2.70441814 -1.86101321  2.56587497  0.12150267 -0.03424013 -2.43875449
#> [49]  1.55473348  0.48215418 -0.22685738 -0.90901034  1.03249565  0.64619291
#> [55] -0.18338233  0.38422570  0.06740295 -0.33897380  0.52269708 -8.32621767
#> [61]  8.02064012 -0.40728307 -0.68927705  0.41438203 -1.22593505  2.22836590
#> [67] -0.68908706 -0.38328520  0.93492225  0.13798574 -0.06431084 -2.04443676
#> [73]  1.84295696 -0.48668188 -0.82850791  0.96187343 -0.23132672  0.07664745
#> [79]  0.37055344  0.22398718 -3.63470297  3.10342533 -0.61852331  1.21664409
#> [85] -3.11919057  3.06141409 -1.90491849  0.28439760  1.55871061 -0.12550502
#> [91] -0.17651018 -0.97569630  0.74787184  0.12268970 -1.46035550  2.05535034
#> [97] -2.77194250  2.98013320  0.41233697
ggAcf( diff(log(GSPC)), plot=T)
```

![](https://i.imgur.com/68jp1Gk.png)

``` r
ggPacf( diff(log(GSPC)), plot=T)
```

![](https://i.imgur.com/PuXVe3W.png)

<sup>Created on 2022-08-14 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by agustinggza** [comment]
Ok, I' ll try. 

However, the problem is the expected ggAcf plot.
For example, if you run acff, I expect acf between 0 ~ 1 and de first value is always 1.
This is the correct result:
------------
stats::acf( data, na.action = na.omit )
stats::pacf( data, na.action = na.omit )
-----------
... but I prefer your library with ggplot.

Thank you.

**Comment by agustinggza** [comment]
Sorry, this de complete code:
library("quantmod")
library("forecast")  # version 8.17.0
getSymbols("^GSPC", from="1970-01-02")
head(GSPC)
data <- diff(log(Cl(GSPC)))
ggAcf( data, plot=T)
ggPacf( data, plot=T)
# ------------------
stats::acf( data, na.action = na.omit )
stats::pacf( data, na.action = na.omit )

**Comment by mitchelloharawild** [comment]
We plot from lag 1 onwards, showing lag 0 is not valuable and can produce issues with the plot's y-axis scale.

**Comment by agustinggza** [comment]
Ah! Ok, thanks. 
Have a good day!
