### ISSUE TITLE
damping  in ets()

### ISSUE THREAD

**Issue by Alexej36** [robjhyndman/forecast#920]
Hi,

a perhaps cosmetic issue, but one cannot pass 1 or 0 to the "damped" argument in the ets() function

```
set.seed(1)
my_ts <- rnorm(36,0,1)

# this works fine
forecast::forecast(ets(my_ts, model="AAN", damped = TRUE))
forecast::forecast(ets(my_ts, model="AAN", damped = FALSE))

# however this does not work
forecast::forecast(ets(my_ts, model="AAN", damped = 1))
forecast::forecast(ets(my_ts, model="AAN", damped = 0))
```
The last two lines generate

`Error in if (damped) { : missing value where TRUE/FALSE needed`

**Comment by robjhyndman** [comment]
Why do you want to? damped is a logical argument, so 0 and 1 are not correct inputs.

**Comment by Alexej36** [comment]
Because TRUE/FALSE and 1/0 are often used  interchangeably 
E.g. in auto.arima it works both ways:

```
set.seed(1)
my_ts <- rnorm(36,0,1) + (1:36)
auto.arima(my_ts, stationary = 1)
auto.arima(my_ts, stationary = TRUE)
```

**Comment by robjhyndman** [comment]
Just because it sometimes works doesn't mean we should always allow it.
