### ISSUE TITLE
typo in documentation of box-cox transformation

### ISSUE THREAD

**Issue by AQLT** [robjhyndman/forecast#923]
Hi,
I think there is a typo in the documentation of the Box-Cox transformation
https://github.com/robjhyndman/forecast/blob/5cb1510af7a165c9511764dfbf16d199029f609a/R/forecast2.R#L125-L126
should be replaced by 

```
#' The Box-Cox transformation (as given by Bickel & Doksum 1981) is given by \deqn{f_\lambda(x) =(sign(x)|x|^\lambda -
#' 1)/\lambda}{f(x;lambda)=(sign(x)|x|^lambda - 1)/lambda} if \eqn{\lambda\ne0}{lambda
```
(sign(x)|x|^\lambda -1) and not sign(x)(|x|^\lambda -1)

**Comment by robjhyndman** [comment]
Thanks. Fixed in https://github.com/robjhyndman/forecast/commit/5bce9d8c82b42b8b8013229c839adea91157e0bf
