### ISSUE TITLE
Replace aes_() calls

### ISSUE THREAD

**Issue by robjhyndman** [robjhyndman/forecast#934]
`aes_()` is deprecated and now giving warnings:

```
`aes_()` was deprecated in ggplot2 3.0.0.
i Please use tidy evaluation ideoms with `aes()`
```

Needed for release 8.2.1 #933

**Comment by robjhyndman** [comment]
This is due on CRAN in a few days. Any progress?

**Comment by mitchelloharawild** [comment]
Yes, I have planned to finish it tonight.
