### ISSUE TITLE
Unpredictable behavior when calling nnetar() with p = 0

### ISSUE THREAD

**Issue by joranE** [robjhyndman/forecast#935]
I realize that the intent is for p >= 1. However, not to name any names, but if a "careless user" happens to think to themselves that they'd like to fit a nnetar model using only seasonal lags, but no non-seasonal lags, they might do something like this:

```
library(forecast)
set.seed(42)
fit <- nnetar(nottem,p = 0,P = 3) 
fcast <- forecast(fit,h = 24) 
```

In this careless person's experience, what happens is that `nnetar()` always runs without error or warning, and then `forecast()` on the resulting object usually runs without error or warning (generating possibly nonsense predictions), but *occasionally* throws this error:

```
> fcast <- forecast(fit,h = 24) 
Error in forecast.nnetar(fit, h = 24) : 
  I can't forecast when there are missing values near the end of the series.
```

I'm not sure why the behavior is so unstable when forecasting, but the ultimate cause is the use of `1:p` in the generation of the set of lags, which means there's always a lag of 1 and 0 in this case, rather than not including any lags from `p` at all. I think that means that you end up with duplicated columns in the `lags.X` matrix from the "0" lag, but I'm not 100% sure of that.

Would you be open to a pull request that either

1. Allows setting `p = 0` and only includes seasonal lags in that case, or
2. Checks for `p = 0` and throws an error in that case, if you think that there is absolutely no case in which a nnetar model with only seasonal lags would yield sensible output at all?

**Comment by robjhyndman** [comment]
A nnetar with only seasonal lags is a feasible model, so we should allow it. Happy to take a PR to handle it.

**Comment by joranE** [comment]
Ok, I'll put something together this weekend.
