### ISSUE TITLE
dm.test function

### ISSUE THREAD

**Issue by SantiagoD999** [robjhyndman/forecast#939]
Good morning professor Hyndman, 

Working with your excellent package _forecast_, I am using the dm.test function. I want to compare twenty 21 step-ahead forecasts, but I am not sure if the correct way of defining the dm.test function is dm.test(e1,e2),**h=21**, varestimator = "bartlett"), because I get this warning: 

Warning message:
In 2 * (1 - b/(m + 1)) * d.cov[-1] :
  longer object length is not a multiple of shorter object length

Here I send an small reproducible example supposing x and y are twenty 21-step ahead forecasts produced by some model. 

set.seed(1)
x<-ts(rnorm(20))
y<-ts(rnorm(20))
autoplot(x)+autolayer(y)
dm.test(as.numeric(x),as.numeric(y),h=21,varestimator = "bartlett")

Thank you ver much.

**Comment by robjhyndman** [comment]
With only 20 observations, you can't have `h=21`. I've added a check to return a better error message when this occurs.

**Comment by SantiagoD999** [comment]
Then how could I define the dm.test function for twenty 21-step ahead forecasts?

Thank you.

**Comment by robjhyndman** [comment]
Yes, I believe the function is correct.
