### ISSUE TITLE
Select the number of harmonics in the TBATS model

### ISSUE THREAD

**Issue by MMenchero** [robjhyndman/forecast#942]
I’ve been reviewing the code of the TBATS model and found that the approach based on multiple linear regression to select the number of harmonics in the TBATS model is no longer implemented. This approach is described in De Livera et al. (2011) and in this paper, the authors say that the multiple linear regression approach

> is preferred over letting $k^*_i = 1$ for each component since the latter was found to be unnecessarily time consuming. 

Could you please provide some clarification on why this approach was removed? For reference, here’s a [fork](https://github.com/bedatadriven/forecast/blob/master/R/tbats.R) where the multiple linear regression approach appears but it's not used (lines 93-114)."

**Comment by robjhyndman** [comment]
No idea. That code has been commented out for more than 10 years, and presumably was part of the code originally written by Alysha De Livera who was a PhD student working with me.

**Comment by MMenchero** [comment]
Thank you for your response. I'll try to get in touch with Alysha since I'm working on an implementation of the BATS and TBATS models in Python.

**Comment by robjhyndman** [comment]
There are at least three existing python implementations which might be helpful:

- https://www.sktime.net/en/latest/api_reference/auto_generated/sktime.forecasting.tbats.TBATS.html
- https://pypi.org/project/tbats/
- https://unit8co.github.io/darts/generated_api/darts.models.forecasting.tbats_model.html

I've not used any of these.
