### ISSUE TITLE
tsCV not accepting other arguments passed to forecastfunction when xreg is present

### ISSUE THREAD

**Issue by tamas-ferenci** [robjhyndman/forecast#943]
The `tsCV` function has an `...` argument that is passed to `forecastfunction`, however, it doesn't seem to work when `xreg` is provided.

My guess it that the problem is the following: when `xreg` is not present, `...` is passed:

    fc <- try(suppressWarnings(
            forecastfunction(y_subset, h = h, ...)
            ), silent = TRUE)

But, interestingly, not when `xreg` is used:

         fc <- try(suppressWarnings(
           forecastfunction(y_subset, h = h, xreg = xreg_subset, newxreg=xreg_future)
           ), silent = TRUE)

**Comment by robjhyndman** [comment]
Thanks. Now fixed
