### ISSUE TITLE
Differentiation xregs in Arima

### ISSUE THREAD

**Issue by CorRuckDS** [robjhyndman/forecast#948]
Hi,

I am trying to do something similar to this:

```
model <- forecast::Arima(y = y, xreg = xreg, order = c(2, 1, 1))
```

The parameter `d` is equal to 1, so I understand that the dependent variable will be differenced. Will the independent variables in `xreg` also be differenced?

I have not found a concise answer to this question. 

Thanks

**Comment by robjhyndman** [comment]
Yes, all variables are differenced as explained here: https://otexts.com/fpp2/regarima.html
