### ISSUE TITLE
Faster `auto.arima` estimation

### ISSUE THREAD

**Issue by studsttat** [robjhyndman/forecast#951]

**Comment by robjhyndman** [comment]
What makes you think this is possible? Any ideas how?

**Comment by studsttat** [comment]
It made me think of it since there is a python package named `statsforecast`, where it has a function named `auto_arima()`. The difference between `auto.arima()` and `auto_arima()` in `statsforecast` is that the `auto_arima()` function in `statsforecast` is 1.5x faster than `auto.arima()` (according to the GitHub page of `statsforecast`).

And so, I thought it can be done with the use of _parallel computing_.

**Comment by robjhyndman** [comment]
`statsforecast` achieves its speed using JIT computing through [Numba](https://numba.pydata.org), a Python compiler. There is no such facility available for R. This has nothing to do with parallel computing, which is already available in both the Python and R implementations.

**Comment by studsttat** [comment]
Nevermind, the `auto.arima()` function can achieve such speed. I tried fitting ARIMA in 50.000 obs. using `auto.arima()`, and the ARIMA was fitted in just an average of 3 seconds.
