### ISSUE TITLE
Why the specific lags used in kpss unit root test in **ndiffs**?

### ISSUE THREAD

**Issue by pgg1309** [robjhyndman/forecast#959]
Hi,
The function `ndiffs` uses a specific number of lags for the `ur.kpss` test 

`use.lag = trunc(3 * sqrt(length(x)) / 13)`

Questions:
(a) why is this lag used ? would it make sense regardless of the periodicity of the series ? 
(b) why not pick lags for the other two tests ? (`ur.df` and `ur.pp`) 

Thanks!

**Comment by robjhyndman** [comment]
See https://stats.stackexchange.com/a/350363/159
Periodicity is irrelevant -- this is a unit root test, not a seasonality test.

We use the default lags for the other tests. This was purely about backwards compatibility.

**Comment by pgg1309** [comment]
Thanks!
