### ISSUE TITLE
ggsubseriesplot() throws error when only labels argument is provided; needs xlab argument to work

### ISSUE THREAD

**Issue by drgomulka** [robjhyndman/forecast#964]
This throws an error:
> ggsubseriesplot(AirPassengers, labels = 1:12)
Error in ggAddExtras(ylab = deparse(substitute(x)), xlab = xlab) : 
  object 'xlab' not found
> ggsubseriesplot(AirPassengers, labels = letters[1:12] )
Error in ggAddExtras(ylab = deparse(substitute(x)), xlab = xlab) : 
  object 'xlab' not found

Providing the function with a xlab argument makes it work: 
> ggsubseriesplot(AirPassengers, labels = 1:12, xlab="xlab argument needs to be set")
> ggsubseriesplot(AirPassengers, labels = letters[1:12], xlab="Please set xlab argument")

The problem comes from this if block. It sets xbreaks, but does not set xlab.  
https://github.com/robjhyndman/forecast/blob/ace207eaef9c11ecef10204101d9c7e5e40b69ad/R/ggplot.R#L1254-L1260
The if blocks on lines 1261 to 1279 set both xbreaks and xlab. 
https://github.com/robjhyndman/forecast/blob/ace207eaef9c11ecef10204101d9c7e5e40b69ad/R/ggplot.R#L1261-L1279

**Comment by robjhyndman** [comment]
Thanks. Fixed in https://github.com/robjhyndman/forecast/commit/97a0a4a251dd67bca192c64fb45e23c29505b655
