### ISSUE TITLE
non-automatic TBATS?

### ISSUE THREAD

**Issue by smxzehvb** [robjhyndman/forecast#965]
Is there a way to force TBATS to run with a certain configuration? Say, I *don't* want the function to try and find the best model out of many parameter configurations. I only want a single *specific* configuration.

e.g. if I want exactly this model, and nothing else tested under the hood:

  * use.box.cox=TRUE
  * use.trend=TRUE
  * use.damped.trend=FASLE
  * use.arma.errors=TRUE (and specifically supply the order, e.g. (1,0) )
  * seasonal.periods= some integer

Is this possible? Thanks.

**Comment by robjhyndman** [comment]
Yes. Please read the documentation. `help(tbats)` or https://pkg.robjhyndman.com/forecast/reference/tbats.html

**Comment by robjhyndman** [comment]
The automatic selection of the ARMA errors can choose $p=q=0$ if that gives the lowest AICc value. 
Additional arguments to `tbats()` are passed on to `auto.arima()` which gives you some control over the model selected, but not enough to fully specify the model.

**Comment by smxzehvb** [comment]
thanks
