### ISSUE TITLE
Missing values in BoxCox.lambda

### ISSUE THREAD

**Issue by diegopujoni** [robjhyndman/forecast#99]
Dear professor Hyndman,

I'm using you package 'forecast' to make some missing values interpolation. The function 'na.interp' asks for a lambda value, but when I use the BoxCox.lambda I get this warning: 

> BoxCox.lambda(AirPassengers,lower=0)
[1] 4.102259e-05
> TS = AirPassengers
> TS[50] = NA
> BoxCox.lambda(TS,lower=0)
Error in if (any(x <= 0)) lower <- 0 : 
  missing value where TRUE/FALSE needed

So I cannot get the lambda value to use in the na.interp function. Do you know how to solve this issue? 

Thank you very much

**Comment by robjhyndman** [comment]
Fixed in https://github.com/robjhyndman/forecast/commit/ac904531614f037923cb0a6e77625142bf8df747
